(function(){
/* ---------------- Flashcards: [domain, Q en, A en, Q zh, A zh] ---------------- */
var C = [
['d1','How do AI, ML, deep learning and GenAI relate?','Nested: AI ⊃ ML ⊃ deep learning ⊃ generative AI. Agentic AI uses generative models to plan and act with tools.','AI、ML、深度学习和生成式 AI 是什么关系？','层层包含：AI ⊃ ML ⊃ 深度学习 ⊃ 生成式 AI。智能体 AI 利用生成式模型规划并借助工具行动。'],
['d1','Training vs inference?','Training fits the model to data (expensive, occasional). Inference uses the trained model on new data (every request, billed per use).','训练与推理的区别？','训练让模型拟合数据（昂贵、偶尔进行）；推理用训练好的模型处理新数据（每次请求都发生，按用量计费）。'],
['d1','Parameter vs hyperparameter?','Parameters (weights) are learned by the model. Hyperparameters (learning rate, epochs, batch size) are set by people before training.','参数与超参数的区别？','参数（权重）由模型学习得到；超参数（学习率、轮数、批大小）由人在训练前设定。'],
['d1','Classification vs regression?','Both supervised. Classification predicts a category (spam / not spam); regression predicts a number (price).','分类与回归的区别？','都是监督学习。分类预测类别（是否垃圾邮件）；回归预测数值（价格）。'],
['d1','Which learning type finds groups in unlabeled data?','Unsupervised learning: clustering (e.g. customer segmentation).','哪种学习在无标签数据中发现分组？','无监督学习中的聚类（如客户分群）。'],
['d1','What is reinforcement learning?','An agent learns by trial and error to maximize cumulative reward from an environment (e.g. AWS DeepRacer, robotics).','什么是强化学习？','智能体通过试错，从环境中获得奖励并使累计奖励最大化（如 AWS DeepRacer、机器人）。'],
['d1','How are LLMs pre-trained?','Self-supervised learning on unlabeled text: predict the next (or a masked) token.','LLM 是如何预训练的？','在无标签文本上进行自监督学习：预测下一个（或被遮盖的）Token。'],
['d1','Real-time vs serverless inference?','Real-time: persistent endpoint, low latency, steady traffic. Serverless: intermittent traffic, scales to zero, tolerates cold starts.','实时推理与无服务器推理的区别？','实时：常驻端点、低延迟、流量稳定。无服务器：流量间歇、可缩容到零、可接受冷启动。'],
['d1','When is asynchronous inference the answer?','Large payloads (up to 1 GB) or long processing (up to 1 hour) where the caller can wait for a notification.','什么时候选异步推理？','负载大（最大 1 GB）或处理时间长（最长 1 小时），调用方可以等待通知时。'],
['d1','When is batch transform the answer?','Scoring a whole dataset offline (e.g. nightly) with no persistent endpoint, at lowest cost.','什么时候选批量转换？','离线对整个数据集打分（如每晚），不需要常驻端点，成本最低。'],
['d1','Structured vs unstructured data?','Structured = tables with a fixed schema. Unstructured = text, images, audio, video. Semi-structured = JSON, XML, logs.','结构化与非结构化数据？','结构化 = 有固定模式的表格；非结构化 = 文本、图像、音频、视频；半结构化 = JSON、XML、日志。'],
['d1','Name two situations where ML is NOT appropriate.','When an exact, rule-defined outcome is required, and when costs outweigh benefits (also: no good data, no tolerance for error).','举出两种不适合用 ML 的情况。','需要由规则确定的精确结果时；成本大于收益时（还有：缺乏优质数据、完全不能容错）。'],
['d1','Precision formula and when to prioritize it','TP / (TP + FP). Prioritize when false positives are costly (a spam filter hiding real email).','精确率公式及何时优先考虑','TP / (TP + FP)。误报代价高时优先（垃圾邮件过滤误拦真实邮件）。'],
['d1','Recall formula and when to prioritize it','TP / (TP + FN). Prioritize when false negatives are costly (missing cancer or fraud).','召回率公式及何时优先考虑','TP / (TP + FN)。漏报代价高时优先（漏诊癌症、漏掉欺诈）。'],
['d1','What does F1 score balance?','Precision and recall (their harmonic mean). Useful on imbalanced data.','F1 分数平衡了什么？','精确率和召回率（二者的调和平均）。适用于不平衡数据。'],
['d1','Data drift vs concept drift?','Data drift: input distribution changes. Concept drift: the relationship between inputs and target changes.','数据漂移与概念漂移？','数据漂移：输入分布变化；概念漂移：输入与目标之间的关系变化。'],
['d1','Which SageMaker feature monitors models in production for drift?','SageMaker Model Monitor (data quality, model quality, bias drift, feature attribution drift).','哪个 SageMaker 功能监控生产模型的漂移？','SageMaker Model Monitor（数据质量、模型质量、偏差漂移、特征归因漂移）。'],
['d1','SageMaker Data Wrangler vs Feature Store?','Data Wrangler prepares and explores data; Feature Store stores and shares engineered features for training and inference.','SageMaker Data Wrangler 与 Feature Store 的区别？','Data Wrangler 用于准备和探索数据；Feature Store 存储并共享工程化特征，供训练和推理使用。'],
['d1','Which service labels training data?','Amazon SageMaker Ground Truth.','哪个服务用于标注训练数据？','Amazon SageMaker Ground Truth。'],
['d1','Managed API vs self-hosted model?','Managed API (Bedrock): no infrastructure, pay per token. Self-hosted (SageMaker endpoint, EC2): full control, you manage scaling and patching.','托管 API 与自托管模型的区别？','托管 API（Bedrock）：无需管理基础设施、按 Token 付费。自托管（SageMaker 端点、EC2）：完全控制，但要自己负责扩缩容和补丁。'],
['d1','Transcribe vs Polly?','Transcribe: speech → text. Polly: text → speech.','Transcribe 与 Polly 的区别？','Transcribe：语音 → 文字；Polly：文字 → 语音。'],
['d1','Comprehend vs Textract?','Comprehend analyzes text meaning (sentiment, entities, PII). Textract extracts text, forms and tables from documents.','Comprehend 与 Textract 的区别？','Comprehend 分析文本含义（情感、实体、PII）；Textract 从文档中提取文字、表单和表格。'],
['d1','Which service builds chatbots with intents and slots?','Amazon Lex.','哪个服务用意图和槽位构建聊天机器人？','Amazon Lex。'],
['d1','When is traditional ML better than an FM?','Regulated decisions needing explanations, structured tabular prediction, strict latency/cost budgets for one narrow task.','什么时候传统 ML 比 FM 更合适？','需要解释的受监管决策、结构化表格预测、单一窄任务且延迟/成本要求严格时。'],
['d2','What is a token? Rule of thumb?','A unit of text the model processes. ≈ 4 characters ≈ 0.75 English words.','什么是 Token？经验值？','模型处理文本的单位。约 4 个字符 ≈ 0.75 个英文单词。'],
['d2','What is an embedding?','A numeric vector representing meaning; similar meanings produce nearby vectors.','什么是嵌入？','表示语义的数值向量；含义相近，向量就相近。'],
['d2','Why chunk documents?','So each piece fits the embedding model and retrieval returns focused, relevant passages.','为什么要对文档分块？','让每一块适合嵌入模型，并使检索返回聚焦、相关的段落。'],
['d2','What makes transformers powerful?','Self-attention: each token attends to every other token in parallel, capturing context.','Transformer 强大的原因？','自注意力：每个 Token 并行关注所有其他 Token，从而捕捉上下文。'],
['d2','What is a diffusion model?','A model that generates images (or video) by denoising random noise step by step, guided by a prompt.','什么是扩散模型？','在提示引导下，从随机噪声逐步去噪来生成图像（或视频）的模型。'],
['d2','What is a multimodal model?','A model that accepts or produces multiple data types: text, images, audio, video.','什么是多模态模型？','能输入或输出多种数据类型（文本、图像、音频、视频）的模型。'],
['d2','FM lifecycle stages','Data selection → model selection → pre-training → fine-tuning → evaluation → deployment → feedback.','FM 生命周期阶段','数据选择 → 模型选择 → 预训练 → 微调 → 评估 → 部署 → 反馈。'],
['d2','How is Bedrock on-demand priced?','Per input token and per output token (output usually costs more).','Bedrock 按需如何计费？','按输入 Token 和输出 Token 分别计费（输出通常更贵）。'],
['d2','Name four ways to cut token cost.','Shorter prompts, fewer retrieved chunks, max-token limits, prompt caching (also smaller/distilled models, batch inference).','举出四种降低 Token 成本的方法。','更短的提示、更少的检索块、限制最大 Token、提示缓存（还有更小/蒸馏模型、批量推理）。'],
['d2','What is context engineering?','Managing what goes into the context window each call: instructions, retrieved docs, history, tool results, memory.','什么是上下文工程？','管理每次调用放入上下文窗口的内容：指令、检索文档、历史、工具结果、记忆。'],
['d2','What is the context window?','The maximum tokens (input + output) a model can handle in one request.','什么是上下文窗口？','模型单次请求能处理的最大 Token 数（输入 + 输出）。'],
['d2','What is MCP?','Model Context Protocol: an open standard connecting AI agents to external tools and data via MCP servers and clients.','什么是 MCP？','模型上下文协议：通过 MCP 服务器和客户端把 AI 智能体连接到外部工具和数据的开放标准。'],
['d2','Core components of an AI agent','Model (reasoning), tools, memory (short- and long-term), planning/orchestration, reflection.','AI 智能体的核心组成','模型（推理）、工具、记忆（短期与长期）、规划/编排、反思。'],
['d2','Supervisor vs swarm multi-agent pattern?','Supervisor: a lead agent delegates and combines. Swarm: peers hand off to each other with no central controller.','主管模式与蜂群模式的区别？','主管：主智能体分派并汇总；蜂群：智能体之间直接交接，没有中央控制者。'],
['d2','Deterministic workflow vs agent-driven flow?','Workflow: fixed steps, predictable, auditable (Bedrock Flows, Step Functions). Agent-driven: model picks next step, flexible, less predictable.','确定性工作流与智能体驱动流程？','工作流：步骤固定、可预测、可审计（Bedrock Flows、Step Functions）；智能体驱动：模型决定下一步，灵活但不易预测。'],
['d2','Four limitations of GenAI named in the guide','Hallucinations, interpretability, inaccuracy, nondeterminism.','考纲列出的生成式 AI 四个局限','幻觉、可解释性差、不准确、非确定性。'],
['d2','Does lowering temperature fix hallucinations?','No. It reduces variation. Use grounding (RAG, contextual grounding checks, citations).','调低温度能解决幻觉吗？','不能，只能减少波动。要用依据增强（RAG、上下文依据检查、引用）。'],
['d2','Bedrock vs SageMaker AI?','Bedrock: serverless API to FMs, no infrastructure. SageMaker AI: full ML platform, you control training, instances and models.','Bedrock 与 SageMaker AI 的区别？','Bedrock：通过无服务器 API 使用 FM，无需基础设施。SageMaker AI：完整 ML 平台，自行控制训练、实例和模型。'],
['d2','What is SageMaker JumpStart?','A hub of pre-trained (mostly open) models and solutions you can deploy and fine-tune in SageMaker quickly.','什么是 SageMaker JumpStart？','预训练（多为开源）模型和解决方案中心，可在 SageMaker 中快速部署和微调。'],
['d2','Trainium vs Inferentia?','Trainium: AWS chip optimized for training. Inferentia: AWS chip optimized for low-cost, high-throughput inference.','Trainium 与 Inferentia 的区别？','Trainium：为训练优化的 AWS 芯片；Inferentia：为低成本、高吞吐推理优化的 AWS 芯片。'],
['d2','What is Amazon Quick?','An agentic AI workspace for business users: chat with company data, research, BI dashboards and automations.','什么是 Amazon Quick？','面向业务用户的智能体 AI 工作空间：与公司数据对话、调研、BI 仪表板和自动化。'],
['d2','What is Kiro?','An agentic IDE for developers with spec-driven development (requirements → design → tasks).','什么是 Kiro？','面向开发者的智能体 IDE，支持规格驱动开发（需求 → 设计 → 任务）。'],
['d2','What is Amazon Bedrock AgentCore?','Services to run and operate agents securely at scale: Runtime, Memory, Gateway, Identity, Policy, Observability, Browser, Code Interpreter.','什么是 Amazon Bedrock AgentCore？','安全、大规模运行和运维智能体的服务集合：Runtime、Memory、Gateway、Identity、Policy、Observability、Browser、Code Interpreter。'],
['d2','What is Strands Agents?','AWS\'s open-source SDK for building AI agents in code.','什么是 Strands Agents？','AWS 用代码构建 AI 智能体的开源 SDK。'],
['d2','When to choose Provisioned Throughput?','Steady, high-volume workloads needing guaranteed throughput. It is also AWS\'s default requirement for serving a customized model (a few customized models can now run on-demand).','什么时候选预置吞吐量？','稳定、高流量、需要有保障吞吐量的工作负载。它也是 AWS 为定制模型提供服务的默认要求（少数定制模型现已可按需运行）。'],
['d2','Batch inference vs on-demand?','Batch: asynchronous, large volumes, about 50% cheaper for supported models. On-demand: real-time, per token.','批量推理与按需的区别？','批量：异步、大批量，受支持模型约便宜 50%；按需：实时、按 Token 计费。'],
['d2','Does Bedrock train on your prompts?','No. Prompts and outputs are not used to train base models or shared with model providers.','Bedrock 会用你的提示训练模型吗？','不会。提示和输出不会用于训练基础模型，也不会共享给模型提供商。'],
['d3','Temperature: low vs high?','Low = focused, consistent (extraction, code). High = varied, creative (brainstorming).','温度：低与高？','低 = 集中、一致（信息提取、代码）；高 = 多样、有创意（头脑风暴）。'],
['d3','Top-P vs Top-K?','Top-P samples from the smallest set whose cumulative probability ≥ P. Top-K samples from the K most likely tokens.','Top-P 与 Top-K？','Top-P 从累计概率 ≥ P 的最小集合中采样；Top-K 从概率最高的 K 个 Token 中采样。'],
['d3','Answers are cut off mid-sentence. Fix?','Increase maximum tokens (response length).','回答在句中被截断，怎么办？','调高最大 Token 数（回答长度）。'],
['d3','What are stop sequences?','Strings that end generation when the model produces them.','什么是停止序列？','模型生成到这些字符串时即停止。'],
['d3','RAG in one sentence','Retrieve relevant passages from your data at query time and add them to the prompt, without changing model weights.','一句话说明 RAG','查询时从你的数据中检索相关段落加入提示，不改变模型权重。'],
['d3','Five RAG stages','Ingest (chunk + embed) → ask → retrieve → augment prompt → generate with citations.','RAG 的五个阶段','导入（分块 + 嵌入）→ 提问 → 检索 → 增强提示 → 生成并引用。'],
['d3','Managed RAG on AWS?','Amazon Bedrock Knowledge Bases.','AWS 上的托管 RAG？','Amazon Bedrock 知识库 (Knowledge Bases)。'],
['d3','Four vector stores named in the guide','Amazon OpenSearch Service, Amazon Aurora, Amazon Neptune, Amazon RDS for PostgreSQL (pgvector).','考纲点名的四种向量存储','Amazon OpenSearch Service、Amazon Aurora、Amazon Neptune、Amazon RDS for PostgreSQL (pgvector)。'],
['d3','Customization ladder, cheapest to most expensive','Prompt engineering → RAG → fine-tuning → continued pre-training → pre-training.','定制阶梯（从便宜到昂贵）','提示工程 → RAG → 微调 → 持续预训练 → 预训练。'],
['d3','What is model distillation?','A large teacher model\'s outputs train a smaller student model that is cheaper and faster with similar accuracy on your task.','什么是模型蒸馏？','用大型教师模型的输出训练较小的学生模型，在你的任务上准确率相近但更便宜更快。'],
['d3','Frequently changing facts: fine-tune or RAG?','RAG. Fine-tuning would need retraining for every change.','频繁变化的事实：微调还是 RAG？','RAG。微调每次变化都要重新训练。'],
['d3','Main parts of a prompt','Instruction, context, input data, output indicator (plus role/system prompt and negative prompt).','提示的主要组成','指令、上下文、输入数据、输出指示（以及角色/系统提示和否定提示）。'],
['d3','What is a negative prompt?','Instructions on what the output must NOT contain (for images: elements to exclude).','什么是否定提示？','说明输出中不得包含的内容（对图像而言：要排除的元素）。'],
['d3','Zero-, one- and few-shot?','0, 1 or several examples in the prompt. All are in-context learning.','零样本、单样本、少样本？','提示中给 0 个、1 个或多个示例，都属于上下文学习。'],
['d3','Chain-of-thought prompting?','Ask the model to reason step by step before answering; helps math and logic.','思维链提示？','让模型先逐步推理再作答；有助于数学和逻辑问题。'],
['d3','Prompt injection vs jailbreaking?','Injection: malicious instructions in input or data hijack the task. Jailbreaking: tricking the model into ignoring its safety rules.','提示注入与越狱的区别？','注入：输入或数据中的恶意指令劫持任务；越狱：诱使模型无视安全规则。'],
['d3','What is poisoning?','Inserting malicious or wrong data into training data or a knowledge base to corrupt outputs.','什么是投毒？','向训练数据或知识库中植入恶意或错误数据以污染输出。'],
['d3','What does Bedrock Prompt Management do?','Stores prompts with variables, creates versions, compares variants across models, shares them across teams.','Bedrock Prompt Management 做什么？','存储带变量的提示、创建版本、跨模型比较不同写法、在团队间共享。'],
['d3','Continued pre-training vs fine-tuning data?','Continued pre-training: unlabeled domain text. Fine-tuning: labeled prompt–response pairs.','持续预训练与微调所用数据？','持续预训练：无标签领域文本；微调：有标签的提示-回答对。'],
['d3','What is instruction tuning?','Fine-tuning on instruction → response examples so the model follows instructions reliably.','什么是指令微调？','用“指令 → 回答”示例微调，让模型可靠地遵循指令。'],
['d3','Three steps of RLHF','Supervised fine-tuning → humans rank answers to train a reward model → optimize the LLM with RL against the reward.','RLHF 的三个步骤','监督微调 → 人类对回答排序以训练奖励模型 → 用强化学习依据奖励优化 LLM。'],
['d3','Data prep factors for fine-tuning','Curation, governance, size, labeling quality, representativeness.','微调数据准备要素','数据筛选、治理、规模、标注质量、代表性。'],
['d3','ROUGE vs BLEU?','ROUGE: recall-oriented overlap, for summarization. BLEU: precision-oriented overlap, for translation.','ROUGE 与 BLEU 的区别？','ROUGE：侧重召回的重合度，用于摘要；BLEU：侧重精确的重合度，用于翻译。'],
['d3','What does BERTScore measure?','Semantic similarity using contextual embeddings; rewards paraphrases with the same meaning.','BERTScore 衡量什么？','用上下文嵌入衡量语义相似度；意思相同的改写也能得高分。'],
['d3','What is LLM-as-a-judge?','Using a strong model to score other models\' responses against criteria; scalable proxy for human review.','什么是 LLM 作为评审？','用强模型按标准给其他模型的回答打分；可扩展地替代人工评审。'],
['d3','Three FM evaluation approaches in the guide','Human-in-the-loop evaluation, benchmark datasets, Amazon Bedrock Model Evaluation.','考纲中的三种 FM 评估方法','人在回路评估、基准数据集、Amazon Bedrock 模型评估。'],
['d3','How do you evaluate a RAG app?','Retrieval quality (context relevance/coverage) + generation quality (faithfulness, answer relevance, correctness, citations).','如何评估 RAG 应用？','检索质量（上下文相关性/覆盖度）+ 生成质量（忠实度、答案相关性、正确性、引用）。'],
['d3','How do you evaluate an agent?','Task completion rate, correct tool selection, steps, cost and latency per task, safety adherence.','如何评估智能体？','任务完成率、工具选择是否正确、步骤数、每项任务成本和延迟、安全合规情况。'],
['d3','Three business alignment metrics in the guide','Task completion rate, user satisfaction, cost per interaction.','考纲中的三个业务对齐指标','任务完成率、用户满意度、每次交互成本。'],
['d4','AWS core dimensions of responsible AI','Fairness, explainability, privacy & security, safety, controllability, veracity & robustness, governance, transparency.','AWS 负责任 AI 的核心维度','公平性、可解释性、隐私与安全、安全性、可控性、真实性与鲁棒性、治理、透明度。'],
['d4','Six Bedrock Guardrails policies','Content filters (incl. prompt attacks), denied topics, word filters, sensitive information (PII) filters, contextual grounding check, Automated Reasoning checks.','Bedrock 护栏的六类策略','内容过滤器（含提示攻击）、拒绝话题、词语过滤器、敏感信息 (PII) 过滤器、上下文依据检查、自动推理检查。'],
['d4','Denied topics vs word filters?','Denied topics block whole subjects described in natural language. Word filters block specific words or phrases.','拒绝话题与词语过滤器的区别？','拒绝话题拦截用自然语言描述的整个主题；词语过滤器拦截具体词语或短语。'],
['d4','Can Guardrails work with models outside Bedrock?','Yes, through the ApplyGuardrail API.','护栏能用于 Bedrock 以外的模型吗？','可以，通过 ApplyGuardrail API。'],
['d4','Underfitting signs and fixes','Poor on training AND test. Fix: more features, more complex model, train longer.','欠拟合的表现与解决办法','训练集和测试集都差。解决：增加特征、更复杂的模型、训练更久。'],
['d4','Overfitting signs and fixes','Great on training, poor on test. Fix: more data, regularization, simpler model, early stopping.','过拟合的表现与解决办法','训练集很好、测试集差。解决：更多数据、正则化、简化模型、提前停止。'],
['d4','What does SageMaker Clarify do?','Detects bias (before and after training) and explains predictions with feature attributions (SHAP).','SageMaker Clarify 做什么？','检测偏差（训练前后），并用特征归因 (SHAP) 解释预测。'],
['d4','What is Amazon A2I?','Amazon Augmented AI: human review workflows for ML predictions (e.g. low-confidence cases).','什么是 Amazon A2I？','Amazon Augmented AI：为 ML 预测（如低置信度情况）构建人工复核工作流。'],
['d4','Qualities of a responsible dataset','Inclusive, diverse, balanced, from curated sources, accurately labeled, representative.','负责任的数据集具备哪些特征？','包容、多样、均衡、来源经筛选、标注准确、有代表性。'],
['d4','Ways to detect bias named in the guide','Label quality analysis, human audits, subgroup analysis.','考纲中检测偏见的方法','标注质量分析、人工审计、子群体分析。'],
['d4','Sustainable model choices','Smallest adequate model, reuse and fine-tune pre-trained models, efficient chips (Trainium, Inferentia), batching and caching.','可持续的模型选择','满足需求的最小模型、复用并微调预训练模型、高能效芯片（Trainium、Inferentia）、批处理和缓存。'],
['d4','Legal risks of GenAI','IP infringement claims, biased outputs, loss of customer trust, end-user risk, hallucinations.','生成式 AI 的法律风险','知识产权侵权索赔、有偏见的输出、失去客户信任、终端用户风险、幻觉。'],
['d4','Transparent model examples','Linear/logistic regression, decision trees, rule-based systems.','透明模型的例子','线性/逻辑回归、决策树、基于规则的系统。'],
['d4','What are SageMaker Model Cards?','Standard documentation of a model: intended use, risk rating, training details, evaluation results.','什么是 SageMaker Model Cards？','模型的标准化文档：预期用途、风险评级、训练细节、评估结果。'],
['d4','What are AWS AI Service Cards?','AWS documentation of its own AI services: intended uses, limitations, responsible AI design.','什么是 AWS AI Service Cards？','AWS 为自家 AI 服务编写的文档：预期用途、局限、负责任 AI 设计。'],
['d4','Main tradeoff of explainability','Interpretability vs performance; also transparency vs safety/security.','可解释性的主要权衡','可解释性 vs 性能；以及透明度 vs 安全。'],
['d4','Human-centered design principles for XAI','User feedback mechanisms, AI decision transparency, human override, design for errors, plain-language explanations.','可解释 AI 的以人为本设计原则','用户反馈机制、AI 决策透明、人工覆盖、为错误而设计、通俗解释。'],
['d5','Shared responsibility for Bedrock','AWS: infrastructure and model hosting. Customer: data, IAM, encryption settings, network config, prompts, guardrails, use of outputs.','Bedrock 的责任共担','AWS：基础设施和模型托管；客户：数据、IAM、加密设置、网络配置、提示、护栏、输出的使用。'],
['d5','Service to find PII in S3','Amazon Macie.','在 S3 中查找 PII 的服务','Amazon Macie。'],
['d5','Keep Bedrock traffic off the internet','AWS PrivateLink (interface VPC endpoint).','让 Bedrock 流量不经过公网','AWS PrivateLink（接口型 VPC 终端节点）。'],
['d5','Encrypt data at rest vs in transit','At rest: AWS KMS keys. In transit: TLS.','静态加密与传输中加密','静态：AWS KMS 密钥；传输中：TLS。'],
['d5','Where to store API keys used by an AI app','AWS Secrets Manager (never in prompts or code).','AI 应用使用的 API 密钥存放在哪里','AWS Secrets Manager（绝不放在提示或代码中）。'],
['d5','What does Amazon Inspector do?','Scans EC2, container images and Lambda for software vulnerabilities (CVEs) and network exposure.','Amazon Inspector 做什么？','扫描 EC2、容器镜像和 Lambda 中的软件漏洞 (CVE) 和网络暴露。'],
['d5','AgentCore Identity vs Policy in AgentCore?','Identity: who can call the agent and how the agent gets credentials for other systems. Policy: rules allowing or denying the agent\'s tool calls.','AgentCore Identity 与 AgentCore 中的 Policy？','Identity：谁能调用智能体、智能体如何获取访问其他系统的凭证；Policy：允许或拒绝智能体工具调用的规则。'],
['d5','Data lineage?','A record of where data came from and every transformation it went through.','数据血缘？','记录数据从何而来以及经历的每一次转换。'],
['d5','Which service catalogs datasets and their metadata?','AWS Glue Data Catalog.','哪个服务对数据集及其元数据编目？','AWS Glue Data Catalog。'],
['d5','Four secure data engineering practices','Assess data quality, privacy-enhancing technologies, data access control, data integrity.','安全数据工程的四项实践','评估数据质量、隐私增强技术、数据访问控制、数据完整性。'],
['d5','Fine-grained (column/row) access to data lake tables','AWS Lake Formation.','数据湖表的细粒度（列/行）访问控制','AWS Lake Formation。'],
['d5','CloudTrail vs model invocation logging?','CloudTrail: who called which API, when. Invocation logging: the actual prompts and responses.','CloudTrail 与模型调用日志的区别？','CloudTrail：谁在何时调用了哪个 API；调用日志：实际的提示和回答内容。'],
['d5','Hallucination detection methods in the guide','RAG grounding, output validation, confidence scoring.','考纲中的幻觉检测方法','RAG 依据、输出校验、置信度评分。'],
['d5','CloudTrail vs Config?','CloudTrail = actions (API calls). Config = resource configuration state and compliance.','CloudTrail 与 Config 的区别？','CloudTrail = 行为（API 调用）；Config = 资源配置状态与合规。'],
['d5','Where do you download AWS SOC and ISO reports?','AWS Artifact.','在哪里下载 AWS 的 SOC 和 ISO 报告？','AWS Artifact。'],
['d5','What does AWS Trusted Advisor check?','Best practices for cost optimization, performance, security, fault tolerance and service quotas.','AWS Trusted Advisor 检查什么？','成本优化、性能、安全、容错和服务配额方面的最佳实践。'],
['d5','Generative AI Security Scoping Matrix: the five scopes','1 Consumer app · 2 Enterprise app · 3 Pre-trained models · 4 Fine-tuned models · 5 Self-trained models.','生成式 AI 安全范围矩阵的五个范围','1 消费级应用 · 2 企业级应用 · 3 预训练模型 · 4 微调模型 · 5 自训练模型。'],
['d5','Bedrock app with RAG: which scope?','Scope 3 (pre-trained model via API). RAG does not change weights.','带 RAG 的 Bedrock 应用属于哪个范围？','范围 3（通过 API 使用预训练模型）。RAG 不改变权重。'],
['d5','Data governance strategies in the guide','Data lifecycle, logging, residency, monitoring, observation, retention.','考纲中的数据治理策略','数据生命周期、日志、驻留、监控、可观测性、保留。'],
['d5','Governance protocol elements','Policies, review cadence, review strategies, frameworks (Scoping Matrix, NIST AI RMF, ISO 42001), transparency standards, team training.','治理规程的要素','政策、审查频率、审查策略、框架（范围矩阵、NIST AI RMF、ISO 42001）、透明度标准、团队培训。']
];
C.forEach(function(c){AIF.cards.push({d:c[0],en:{q:c[1],a:c[2]},zh:{q:c[3],a:c[4]}});});

/* ---------------- Services: [name, cat, what en, pick-when en, what zh, pick-when zh] ---------------- */
var S = [
['Amazon Bedrock','genai','Serverless API to many foundation models, plus RAG, agents, guardrails, evaluation and customization.','Build a GenAI app without managing infrastructure.','通过无服务器 API 使用多种基础模型，并提供 RAG、智能体、护栏、评估和定制。','无需管理基础设施即可构建生成式 AI 应用。'],
['Bedrock Knowledge Bases','genai','Fully managed RAG: ingest, chunk, embed, store and retrieve your documents with citations.','Answers from company documents that change often.','全托管 RAG：导入、分块、嵌入、存储并检索文档，附带引用。','需要依据经常变化的公司文档作答。'],
['Bedrock Agents','genai','Managed agents with action groups (Lambda/OpenAPI), knowledge bases and multi-agent collaboration.','A managed assistant that takes actions through APIs.','托管智能体，支持操作组（Lambda/OpenAPI）、知识库和多智能体协作。','需要通过 API 执行操作的托管助手。'],
['Bedrock AgentCore','genai','Run any agent framework securely at scale: Runtime, Memory, Gateway, Identity, Policy, Observability, Browser, Code Interpreter.','Production agents built with your own framework or model.','安全、大规模运行任何框架的智能体：Runtime、Memory、Gateway、Identity、Policy、Observability、Browser、Code Interpreter。','用自选框架或模型构建的生产级智能体。'],
['Bedrock Guardrails','genai','Content filters, denied topics, word filters, PII filters, contextual grounding and Automated Reasoning checks on inputs and outputs.','Block harmful content, mask PII, catch hallucinations, stop prompt attacks.','对输入和输出应用内容过滤、拒绝话题、词语过滤、PII 过滤、上下文依据检查和自动推理检查。','拦截有害内容、掩码 PII、发现幻觉、阻止提示攻击。'],
['Bedrock Model Evaluation','genai','Automatic, human and LLM-as-a-judge evaluation of models and RAG.','Compare FMs on your own data before choosing.','对模型和 RAG 进行自动、人工和 LLM 评审式评估。','选型前用自己的数据比较 FM。'],
['Bedrock Prompt Management','genai','Store, version, compare and share prompts with variables.','Govern prompts across teams and roll back changes.','存储、版本化、比较和共享带变量的提示。','在团队中管理提示并可回滚。'],
['Amazon Nova','genai','Amazon\'s foundation models: Micro, Lite, Pro, Premier (text/multimodal), Canvas (image), Reel (video), Sonic (speech).','Cost-effective Amazon-built models on Bedrock.','亚马逊的基础模型：Micro、Lite、Pro、Premier（文本/多模态）、Canvas（图像）、Reel（视频）、Sonic（语音）。','在 Bedrock 上使用高性价比的亚马逊自研模型。'],
['SageMaker JumpStart','genai','Hub of pre-trained open models and solution templates to deploy and fine-tune.','Quickly run an open-source model on your own endpoint.','预训练开源模型与解决方案模板中心，可部署和微调。','快速在自己的端点上运行开源模型。'],
['Strands Agents','genai','Open-source SDK for building agents in code.','Developers writing custom agents.','用代码构建智能体的开源 SDK。','开发者编写自定义智能体。'],
['Amazon Quick','genai','Agentic workspace for business users: chat with data, research, BI dashboards, automations.','Employees need answers and insights across company data.','面向业务用户的智能体工作空间：数据对话、调研、BI 仪表板、自动化。','员工需要跨公司数据获取答案和洞察。'],
['Amazon Q Developer','genai','AI assistant for developers in the IDE, CLI and console.','Code suggestions, explanations, upgrades.','面向开发者的 AI 助手，支持 IDE、CLI 和控制台。','代码建议、解释、升级。'],
['Kiro','genai','Agentic IDE with spec-driven development and agent hooks.','Build features from specs with AI agents.','支持规格驱动开发和智能体钩子的智能体 IDE。','借助 AI 智能体按规格开发功能。'],
['AWS Transform','genai','Agentic AI for migrating and modernizing .NET, mainframe, VMware and Java workloads.','Modernize legacy applications.','用于迁移和现代化 .NET、大型机、VMware 和 Java 工作负载的智能体 AI。','现代化遗留应用。'],
['Amazon SageMaker AI','ml','Build, train, tune, deploy and monitor custom ML models; includes Canvas, Data Wrangler, Feature Store, Clarify, Model Monitor, Pipelines.','Custom models and full control.','构建、训练、调优、部署和监控自定义 ML 模型；包含 Canvas、Data Wrangler、Feature Store、Clarify、Model Monitor、Pipelines。','需要自定义模型和完全控制。'],
['SageMaker Clarify','ml','Bias detection and explainability (SHAP).','Measure bias across groups; explain predictions.','偏差检测与可解释性 (SHAP)。','衡量群体间偏差；解释预测。'],
['SageMaker Model Monitor','ml','Monitors deployed models for data, quality and bias drift.','Detect drift in production.','监控已部署模型的数据漂移、质量漂移和偏差漂移。','发现生产环境中的漂移。'],
['SageMaker Ground Truth','ml','Data labeling with human workforces; collects human feedback.','Create labeled training data.','借助人工标注团队进行数据标注；收集人类反馈。','制作有标签的训练数据。'],
['SageMaker Model Cards','ml','Standard documentation of a model\'s purpose, training and evaluation.','Audit and governance records.','记录模型用途、训练和评估的标准化文档。','审计与治理记录。'],
['Amazon A2I','ml','Human review workflows for ML predictions.','Route low-confidence results to people.','ML 预测的人工复核工作流。','把低置信度结果交给人工。'],
['Amazon Comprehend','ai','NLP: sentiment, entities, key phrases, language, PII, topics, custom classification.','Analyze meaning in text.','NLP：情感、实体、关键短语、语种、PII、主题、自定义分类。','分析文本含义。'],
['Amazon Transcribe','ai','Speech to text with speaker labels, custom vocabulary, PII redaction.','Transcribe calls, meetings, videos.','语音转文字，支持说话人标记、自定义词汇、PII 脱敏。','转写通话、会议、视频。'],
['Amazon Translate','ai','Neural machine translation with custom terminology.','Localize text into other languages.','支持自定义术语的神经机器翻译。','把文本本地化为其他语言。'],
['Amazon Polly','ai','Text to lifelike speech.','Voice output for apps and IVR.','文字转逼真语音。','为应用和语音导航提供语音输出。'],
['Amazon Lex','ai','Conversational voice and text bots (intents, slots).','Build a chatbot or voice bot.','对话式语音和文本机器人（意图、槽位）。','构建聊天机器人或语音机器人。'],
['Amazon Rekognition','ai','Image and video analysis: objects, faces, text, moderation.','Detect content in images or video.','图像和视频分析：物体、人脸、文字、内容审核。','识别图像或视频中的内容。'],
['Amazon Textract','ai','Extract text, forms and tables from documents.','Digitize scanned invoices and forms.','从文档中提取文字、表单和表格。','数字化扫描的发票和表单。'],
['Amazon Personalize','ai','Real-time personalized recommendations.','"Recommended for you" features.','实时个性化推荐。','“为你推荐”功能。'],
['AWS Trainium','infra','AWS chips optimized for training (and cost-efficient inference).','Lower-cost, energy-efficient model training.','为训练（及高性价比推理）优化的 AWS 芯片。','低成本、高能效的模型训练。'],
['AWS Inferentia','infra','AWS chips optimized for high-throughput, low-cost inference.','Serve models cheaply at scale.','为高吞吐、低成本推理优化的 AWS 芯片。','大规模低成本提供模型服务。'],
['Amazon EC2','infra','Virtual servers, including GPU and accelerator instances.','Self-host models with full control.','虚拟服务器，包括 GPU 和加速实例。','完全自主地托管模型。'],
['Amazon S3','infra','Object storage for datasets, documents, model artifacts and logs.','Store training data and RAG source documents.','存放数据集、文档、模型产物和日志的对象存储。','存放训练数据和 RAG 源文档。'],
['Amazon OpenSearch Service','data','Search and analytics with a vector engine (k-NN, hybrid search).','Vector store for RAG.','带向量引擎的搜索与分析服务（k-NN、混合搜索）。','作为 RAG 的向量存储。'],
['Amazon Aurora / RDS for PostgreSQL','data','Relational databases with pgvector for embeddings.','Keep vectors next to relational data.','带 pgvector 嵌入支持的关系型数据库。','把向量与关系数据放在一起。'],
['Amazon Neptune','data','Graph database; Neptune Analytics supports vector search and GraphRAG.','Relationship-rich knowledge for RAG.','图数据库；Neptune Analytics 支持向量搜索和 GraphRAG。','关系丰富的知识用于 RAG。'],
['AWS Glue / DataBrew','data','ETL, Data Catalog, data quality; DataBrew for no-code data preparation.','Prepare and catalog data.','ETL、数据目录、数据质量；DataBrew 提供无代码数据准备。','准备和编目数据。'],
['AWS Lake Formation','data','Build data lakes with fine-grained (table/column/row) permissions.','Control who sees which data.','构建数据湖并提供细粒度（表/列/行）权限。','控制谁能看到哪些数据。'],
['AWS IAM','sec','Users, roles, policies; least-privilege access.','Control who can invoke models or read data.','用户、角色、策略；最小权限访问。','控制谁能调用模型或读取数据。'],
['AWS KMS','sec','Create and control encryption keys.','Encrypt data, custom models and logs at rest.','创建并管理加密密钥。','对数据、定制模型和日志进行静态加密。'],
['Amazon Macie','sec','ML-based discovery of sensitive data (PII) in S3.','Find PII before training or indexing.','基于 ML 在 S3 中发现敏感数据 (PII)。','训练或建索引前查找 PII。'],
['AWS PrivateLink','sec','Private VPC interface endpoints to AWS services.','Reach Bedrock/SageMaker without the internet.','通往 AWS 服务的私有 VPC 接口终端节点。','不经公网访问 Bedrock/SageMaker。'],
['AWS Secrets Manager','sec','Store and rotate secrets and API keys.','Keep credentials out of code and prompts.','存储并轮换密钥和 API 凭证。','让凭证远离代码和提示。'],
['Amazon Inspector','sec','Automated vulnerability scanning of EC2, containers, Lambda.','Find CVEs in AI workloads.','自动扫描 EC2、容器、Lambda 的漏洞。','发现 AI 工作负载中的 CVE。'],
['AWS Artifact','gov','Self-service AWS compliance reports and agreements.','Get SOC/ISO/PCI reports for auditors.','自助获取 AWS 合规报告和协议。','为审计人员获取 SOC/ISO/PCI 报告。'],
['AWS CloudTrail','gov','Log of API activity: who did what, when.','Audit changes and API calls.','API 活动日志：谁在何时做了什么。','审计变更和 API 调用。'],
['AWS Config','gov','Configuration history and compliance rules for resources.','Continuously check resources meet policy.','资源的配置历史和合规规则。','持续检查资源是否符合策略。'],
['AWS Trusted Advisor','gov','Best-practice checks: cost, performance, security, fault tolerance, quotas.','Find risky or wasteful setups.','最佳实践检查：成本、性能、安全、容错、配额。','发现有风险或浪费的配置。'],
['Amazon CloudWatch','gov','Metrics, logs, alarms, dashboards.','Monitor usage, errors, latency; store invocation logs.','指标、日志、告警、仪表板。','监控用量、错误、延迟；存储调用日志。'],
['AWS Well-Architected Tool','gov','Review workloads against best-practice pillars and lenses (ML, GenAI).','Structured architecture review.','按最佳实践支柱和透镜（ML、生成式 AI）评审工作负载。','结构化的架构评审。']
];
S.forEach(function(s){AIF.svc.push({n:s[0],c:s[1],en:{w:s[2],p:s[3]},zh:{w:s[4],p:s[5]}});});

/* ---------------- Glossary: [term en, def en, term zh, def zh] ---------------- */
var G = [
['Agentic AI','Systems where a model plans, uses tools and memory, and acts toward a goal with limited human input.','智能体 AI','由模型规划、使用工具和记忆，在较少人工干预下朝目标行动的系统。'],
['Algorithm','The procedure used to learn from data (e.g. linear regression, k-means).','算法','从数据中学习所用的方法（如线性回归、k-means）。'],
['Anomaly detection','Finding rare items or events that differ from the norm.','异常检测','发现与常态不同的罕见项目或事件。'],
['AUC-ROC','How well a classifier separates classes across all thresholds; 0.5 random, 1.0 perfect.','AUC-ROC','分类器在所有阈值下区分类别的能力；0.5 为随机，1.0 为完美。'],
['Automated Reasoning checks','Guardrails policy that verifies responses against formal logic rules from your policies.','自动推理检查','依据从政策中构建的形式化逻辑规则验证回答的护栏策略。'],
['Batch inference','Processing many requests asynchronously at lower cost, results returned later.','批量推理','以较低成本异步处理大量请求，结果稍后返回。'],
['BERTScore','Metric comparing texts by semantic similarity of contextual embeddings.','BERTScore','通过上下文嵌入的语义相似度比较文本的指标。'],
['Bias (fairness)','Outcomes that systematically disadvantage a group of people.','偏见（公平性）','系统性地对某类人群不利的结果。'],
['Bias (statistical)','Error from over-simple assumptions; causes underfitting.','偏差（统计）','过于简单的假设造成的误差，导致欠拟合。'],
['BLEU','Bilingual Evaluation Understudy: precision-based n-gram overlap, used for translation.','BLEU','基于精确率的 n-gram 重合度指标，用于机器翻译。'],
['Chain-of-thought (CoT)','Prompting the model to reason step by step before answering.','思维链 (CoT)','提示模型先逐步推理再作答。'],
['Chunking','Splitting documents into smaller passages before embedding.','分块','在嵌入前把文档切分为较小的段落。'],
['Classification','Predicting a category.','分类','预测类别。'],
['Clustering','Grouping unlabeled data by similarity.','聚类','按相似度对无标签数据分组。'],
['Computer vision','AI that interprets images and video.','计算机视觉','理解图像和视频的 AI。'],
['Concept drift','Change in the relationship between inputs and the target over time.','概念漂移','输入与目标之间的关系随时间变化。'],
['Confusion matrix','Table of TP, FP, FN, TN used to compute classification metrics.','混淆矩阵','由 TP、FP、FN、TN 组成、用于计算分类指标的表格。'],
['Context engineering','Managing what information goes into the model\'s context window on each call.','上下文工程','管理每次调用时放入模型上下文窗口的信息。'],
['Context window','Maximum tokens (input + output) a model can handle per request.','上下文窗口','模型单次请求能处理的最大 Token 数（输入 + 输出）。'],
['Contextual grounding check','Guardrails policy that blocks responses not grounded in the source or not relevant to the query.','上下文依据检查','拦截缺乏源材料依据或与问题无关的回答的护栏策略。'],
['Continued pre-training','Further training an FM on unlabeled domain data.','持续预训练','用无标签领域数据进一步训练 FM。'],
['Data drift','Change in the distribution of input data over time.','数据漂移','输入数据分布随时间变化。'],
['Data lineage','Record of data\'s origin and transformations.','数据血缘','数据来源和转换过程的记录。'],
['Data residency','Keeping data in specific geographic locations.','数据驻留','把数据保存在特定地理位置。'],
['Deep learning','ML using multi-layer neural networks.','深度学习','使用多层神经网络的机器学习。'],
['Denied topics','Guardrails policy that blocks subjects you describe in natural language.','拒绝话题','拦截你用自然语言描述的话题的护栏策略。'],
['Diffusion model','Generative model that creates images by removing noise step by step.','扩散模型','通过逐步去噪生成图像的生成式模型。'],
['Distillation','Training a smaller student model from a larger teacher model\'s outputs.','蒸馏','用大型教师模型的输出训练较小的学生模型。'],
['Embedding','Numeric vector representing meaning.','嵌入','表示语义的数值向量。'],
['Epoch','One full pass over the training data.','轮 (Epoch)','完整遍历一次训练数据。'],
['F1 score','Harmonic mean of precision and recall.','F1 分数','精确率和召回率的调和平均。'],
['Feature','An input variable used by a model.','特征','模型使用的输入变量。'],
['Few-shot prompting','Including several examples in the prompt.','少样本提示','在提示中包含若干示例。'],
['Fine-tuning','Training an FM further on labeled examples; changes weights.','微调','用有标签示例进一步训练 FM；会改变权重。'],
['Foundation model (FM)','Large model pre-trained on broad data, adaptable to many tasks.','基础模型 (FM)','在广泛数据上预训练、可适配多种任务的大模型。'],
['Generative AI','AI that creates new content: text, images, audio, video, code.','生成式 AI','创造新内容（文本、图像、音频、视频、代码）的 AI。'],
['Ground truth','Verified correct labels.','真实值 (Ground truth)','经过核实的正确标签。'],
['Hallucination','Confident but false or fabricated model output.','幻觉','模型自信但错误或编造的输出。'],
['Hyperparameter','Setting chosen before training (learning rate, epochs).','超参数','训练前设定的参数（学习率、轮数）。'],
['In-context learning','Model learns a task from instructions and examples in the prompt, without training.','上下文学习','模型通过提示中的指令和示例学习任务，无需训练。'],
['Inference','Using a trained model to make predictions.','推理','使用训练好的模型进行预测。'],
['Instruction tuning','Fine-tuning on instruction → response pairs.','指令微调','用“指令 → 回答”对进行微调。'],
['Jailbreaking','Tricking a model into ignoring its safety rules.','越狱','诱使模型无视其安全规则。'],
['k-NN','k-nearest neighbors: finding the k closest vectors to a query.','k 近邻 (k-NN)','找出与查询最接近的 k 个向量。'],
['Label','The answer a supervised model learns to predict.','标签','监督模型要学会预测的答案。'],
['LLM','Large language model: a large transformer trained on text to predict tokens.','大语言模型 (LLM)','在文本上训练、用于预测 Token 的大型 Transformer 模型。'],
['LLM-as-a-judge','Using a model to score other models\' outputs.','LLM 作为评审','用一个模型为其他模型的输出打分。'],
['MCP','Model Context Protocol: open standard to connect agents to tools and data.','MCP','模型上下文协议：把智能体连接到工具和数据的开放标准。'],
['MLOps','Practices to deploy and maintain ML models reliably in production.','MLOps','在生产环境中可靠部署和维护 ML 模型的实践。'],
['Model','The artifact produced by training that makes predictions.','模型','训练得到、用于预测的产物。'],
['Multimodal','Handling multiple data types (text, image, audio, video).','多模态','处理多种数据类型（文本、图像、音频、视频）。'],
['Negative prompt','Instruction stating what the output should not contain.','否定提示','说明输出中不应包含内容的指令。'],
['Neural network','Layers of connected nodes with learned weights.','神经网络','由带学习权重的节点分层连接而成。'],
['NLP','Natural language processing: AI for human language.','自然语言处理 (NLP)','处理人类语言的 AI。'],
['Nondeterminism','Same input can give different outputs.','非确定性','相同输入可能得到不同输出。'],
['Overfitting','Model memorizes training data; great on training, poor on new data.','过拟合','模型记住训练数据；训练集好、新数据差。'],
['Parameter','Value (weight) the model learns during training.','参数','模型在训练中学到的值（权重）。'],
['Perplexity','How well a language model predicts text; lower is better.','困惑度','语言模型预测文本的能力；越低越好。'],
['PII','Personally identifiable information.','PII','个人身份信息。'],
['Poisoning','Corrupting training data or a knowledge base to manipulate outputs.','投毒','污染训练数据或知识库以操纵输出。'],
['Precision','TP / (TP + FP): correctness of positive predictions.','精确率','TP / (TP + FP)：正向预测的正确程度。'],
['Pre-training','Initial training of an FM on huge unlabeled data.','预训练','在海量无标签数据上对 FM 进行初始训练。'],
['Prompt caching','Reusing a processed prompt prefix to cut cost and latency.','提示缓存','复用已处理的提示前缀以降低成本和延迟。'],
['Prompt injection','Malicious instructions in input or data that hijack the model.','提示注入','输入或数据中劫持模型的恶意指令。'],
['Prompt template','Reusable prompt with variables.','提示模板','带变量的可复用提示。'],
['Provisioned Throughput','Reserved model capacity billed hourly for consistent throughput.','预置吞吐量','按小时计费的预留模型容量，提供稳定吞吐。'],
['RAG','Retrieval Augmented Generation: add retrieved passages to the prompt so the model answers from them.','RAG','检索增强生成：把检索到的段落加入提示，让模型据此作答。'],
['Recall','TP / (TP + FN): share of real positives found.','召回率','TP / (TP + FN)：找到的真实正例比例。'],
['Regression','Predicting a number.','回归','预测数值。'],
['Reinforcement learning','Learning by trial and error from rewards.','强化学习','通过试错从奖励中学习。'],
['RLHF','Reinforcement learning from human feedback: aligns models using human preference rankings.','RLHF','基于人类反馈的强化学习：利用人类偏好排序对齐模型。'],
['ROUGE','Recall-Oriented Understudy for Gisting Evaluation: recall-based overlap, used for summarization.','ROUGE','基于召回率的重合度指标，用于摘要。'],
['Scoping Matrix','AWS Generative AI Security Scoping Matrix: five scopes from consumer app to self-trained model.','范围矩阵','AWS 生成式 AI 安全范围矩阵：从消费级应用到自训练模型的五个范围。'],
['Self-attention','Transformer mechanism relating every token to every other token.','自注意力','Transformer 中让每个 Token 与所有其他 Token 建立关联的机制。'],
['Semantic search','Search by meaning using embeddings, not exact keywords.','语义搜索','用嵌入按含义而非精确关键词搜索。'],
['Stop sequence','String that ends generation.','停止序列','使生成停止的字符串。'],
['Supervised learning','Learning from labeled data.','监督学习','从有标签数据中学习。'],
['Temperature','Parameter controlling randomness of output.','温度','控制输出随机性的参数。'],
['Token','Unit of text a model processes (≈ 0.75 English words).','Token（词元）','模型处理的文本单位（约 0.75 个英文单词）。'],
['Top-K','Sample only from the K most likely tokens.','Top-K','只从概率最高的 K 个 Token 中采样。'],
['Top-P','Sample from the smallest token set whose probabilities sum to P.','Top-P','从累计概率达到 P 的最小 Token 集合中采样。'],
['Transfer learning','Reusing a pre-trained model for a new task.','迁移学习','把预训练模型复用于新任务。'],
['Transformer','Neural network architecture based on self-attention; basis of LLMs.','Transformer','基于自注意力的神经网络架构；LLM 的基础。'],
['Underfitting','Model too simple; poor on training and test data.','欠拟合','模型太简单；训练集和测试集都表现差。'],
['Unsupervised learning','Finding structure in unlabeled data.','无监督学习','在无标签数据中发现结构。'],
['Vector database','Store optimized for similarity search over embeddings.','向量数据库','针对嵌入相似度搜索优化的存储。'],
['Zero-shot prompting','Asking for a task with no examples.','零样本提示','不给示例直接提出任务。']
];
G.forEach(function(g){AIF.gloss.push({en:{t:g[0],d:g[1]},zh:{t:g[2],d:g[3]}});});

/* ---------------- 7-day plan ---------------- */
AIF.plan = [
 {en:'Domain 1 vocabulary and the ML lifecycle', zh:'领域 1 术语与 ML 生命周期', items:[
  ['t:1.1','Read Task 1.1 and say each core term out loud in your own words','阅读任务 1.1，用自己的话大声复述每个核心术语'],
  ['t:1.2','Read Task 1.2; memorize the managed AI services table','阅读任务 1.2，记住托管 AI 服务表'],
  ['t:1.3','Read Task 1.3; work the spam-filter metric example by hand','阅读任务 1.3，手算垃圾邮件指标示例'],
  ['c:d1','Flip all Domain 1 flashcards','翻完领域 1 的全部闪卡']]},
 {en:'Domain 2: GenAI concepts and AWS stack', zh:'领域 2：生成式 AI 概念与 AWS 技术栈', items:[
  ['t:2.1','Read Task 2.1: tokens, embeddings, MCP, agent patterns','阅读任务 2.1：Token、嵌入、MCP、智能体模式'],
  ['t:2.2','Read Task 2.2: strengths, limits, model selection','阅读任务 2.2：优势、局限、模型选择'],
  ['t:2.3','Read Task 2.3: Bedrock vs SageMaker, cost options','阅读任务 2.3：Bedrock 与 SageMaker 对比、成本选项'],
  ['c:d2','Flip all Domain 2 flashcards','翻完领域 2 的全部闪卡']]},
 {en:'Domain 3 part 1: design, RAG, prompts', zh:'领域 3（上）：设计、RAG、提示', items:[
  ['t:3.1','Read Task 3.1; redraw the RAG flow and the customization ladder from memory','阅读任务 3.1，凭记忆画出 RAG 流程和定制阶梯'],
  ['t:3.2','Read Task 3.2; write one prompt using all five techniques','阅读任务 3.2，用五种技术各写一个提示'],
  ['q:d3','Practice Domain 3 questions','练习领域 3 题目']]},
 {en:'Domain 3 part 2: training and evaluation', zh:'领域 3（下）：训练与评估', items:[
  ['t:3.3','Read Task 3.3: labeled vs unlabeled training, RLHF','阅读任务 3.3：有标签与无标签训练、RLHF'],
  ['t:3.4','Read Task 3.4: ROUGE, BLEU, BERTScore, LLM-as-a-judge, RAG/agent evaluation','阅读任务 3.4：ROUGE、BLEU、BERTScore、LLM 评审、RAG/智能体评估'],
  ['c:d3','Flip all Domain 3 flashcards','翻完领域 3 的全部闪卡']]},
 {en:'Domain 4: responsible AI', zh:'领域 4：负责任 AI', items:[
  ['t:4.1','Read Task 4.1; list the six Guardrails policies from memory','阅读任务 4.1，凭记忆列出六类护栏策略'],
  ['t:4.2','Read Task 4.2: Model Cards, Clarify, tradeoffs','阅读任务 4.2：Model Cards、Clarify、权衡'],
  ['q:d4','Practice Domain 4 questions','练习领域 4 题目']]},
 {en:'Domain 5: security and governance', zh:'领域 5：安全与治理', items:[
  ['t:5.1','Read Task 5.1: shared responsibility, security services, grounding','阅读任务 5.1：责任共担、安全服务、依据增强'],
  ['t:5.2','Read Task 5.2; recite the five Scoping Matrix scopes','阅读任务 5.2，背诵范围矩阵的五个范围'],
  ['q:d5','Practice Domain 5 questions','练习领域 5 题目']]},
 {en:'Full review and mock exams', zh:'全面复习与模拟考试', items:[
  ['m:1','Take mock exam #1 and review every wrong answer','完成第 1 次模拟考试并复盘每道错题'],
  ['s:','Scan the Services map; cover the right column and recall it','浏览服务速查表，遮住右列进行回忆'],
  ['c:all','Flip every flashcard you have not marked "I know this"','翻完所有未标记“已掌握”的闪卡'],
  ['r:','Retry your Missed questions until the list is empty','重做“错题”列表，直到清空'],
  ['m:2','Take the full 65-question exam simulation; aim for an estimated 750 or higher','完成 65 题真实考试模拟，目标估算分 750 以上']]}
];
})();
