/* Second question set. First argument is the task id (lesson); correct options are authored first
   and shuffled on screen. */
(function(){
/* tag the original 76 questions with their lesson */
var K = ['1.2','1.1','1.3','1.1','1.2','1.1','1.2','1.2','1.3','1.3','1.2','1.1','1.3','1.3',
 '2.1','2.1','2.1','2.2','2.1','2.1','2.1','2.3','2.3','2.3','2.3','2.1','2.3','2.2','2.1','2.2',
 '3.1','3.1','3.1','3.1','3.1','3.3','3.1','3.2','3.2','3.2','3.4','3.4','3.4','3.3','3.3','3.2','3.1','3.4','3.4',
 '4.1','4.1','4.1','4.1','4.1','4.1','4.2','4.1','4.2','4.2','4.1','4.1',
 '5.1','5.1','5.2','5.2','5.2','5.2','5.2','5.1','5.1','5.1','5.1','5.1','5.2','5.2','5.1'];
K.forEach(function(k, i){ if (AIF.qs[i]) AIF.qs[i].k = k; });

function Q(k,t,a,en,zh){AIF.qs.push({k:k,d:'d'+k.charAt(0),t:t,a:a,en:{q:en[0],o:en[1],x:en[2]},zh:{q:zh[0],o:zh[1],x:zh[2]}});}

/* ===== 1.1 ===== */
Q('1.1','multi',[0,1],
['Which of the following are examples of unstructured data? (Choose TWO.)',
 ['Recorded customer phone calls','Product photos uploaded by sellers','A relational table of orders','A CSV file of daily sales totals','A spreadsheet of employee IDs and salaries'],
 'Audio and images have no fixed schema, so they are unstructured. Tables, CSV files and spreadsheets are structured (tabular) data.'],
['以下哪些属于非结构化数据？（选择两项）',
 ['录制的客户电话','卖家上传的商品照片','订单关系表','每日销售总额的 CSV 文件','员工编号与薪资的电子表格'],
 '音频和图像没有固定模式，属于非结构化数据；表格、CSV 和电子表格都是结构化（表格）数据。']);
Q('1.1','single',[0],
['A utility company has three years of electricity meter readings recorded every hour. What type of data is this?',
 ['Time-series data','Image data','Unlabeled text data','Semi-structured JSON data'],
 'Values ordered by timestamp are time-series data, typically used for forecasting and anomaly detection.'],
['一家公用事业公司有三年来每小时记录一次的电表读数。这属于哪类数据？',
 ['时间序列数据','图像数据','无标签文本数据','半结构化 JSON 数据'],
 '按时间戳排序的数值是时间序列数据，常用于预测和异常检测。']);
Q('1.1','single',[0],
['Which statement best describes deep learning?',
 ['It uses multi-layer neural networks that learn features directly from raw data such as images, audio and text','It relies only on hand-written if-then rules','It always needs less training data than traditional ML','It cannot process images or audio'],
 'Deep learning is a subset of ML built on multi-layer neural networks; it excels on unstructured data and usually needs a lot of data.'],
['哪种说法最能描述深度学习？',
 ['使用多层神经网络，直接从图像、音频、文本等原始数据中学习特征','只依赖人工编写的 if-then 规则','总是比传统 ML 需要更少的训练数据','无法处理图像或音频'],
 '深度学习是基于多层神经网络的 ML 子集，擅长非结构化数据，通常需要大量数据。']);
Q('1.1','single',[0],
['An internal HR model is called only a few times a day and sits idle for hours in between. The team wants the lowest cost and can accept a short delay on the first request after idle time. Which SageMaker AI inference option fits?',
 ['Serverless inference','Real-time inference on a dedicated instance','Batch transform','Asynchronous inference with a 1 GB payload'],
 'Serverless inference scales to zero when idle and charges per use; cold starts are the tradeoff.'],
['某内部人事模型每天只被调用几次，中间长时间空闲。团队希望成本最低，并能接受空闲后首个请求有短暂延迟。应选哪种 SageMaker AI 推理方式？',
 ['无服务器推理','专用实例上的实时推理','批量转换','负载 1 GB 的异步推理'],
 '无服务器推理空闲时缩容到零、按使用付费，代价是冷启动延迟。']);
Q('1.1','match',[],
['Match each dataset split to its purpose.',
 [['Training set','Learn the model parameters'],['Validation set','Tune hyperparameters and choose between models'],['Test set','Give a final, unbiased estimate of performance']],
 'Train to learn, validate to tune, test once at the end.'],
['将每个数据集划分与其用途匹配。',
 [['训练集','学习模型参数'],['验证集','调整超参数并在模型之间选择'],['测试集','给出最终、无偏的性能评估']],
 '训练集用来学习，验证集用来调优，测试集在最后使用一次。']);
Q('1.1','single',[0],
['Which scenario is an example of agentic AI rather than a single generative AI response?',
 ['An assistant checks stock levels through an API, places a reorder, and emails the supplier a confirmation','A model writes a product description from bullet points','A model translates a manual into French','A model summarizes a meeting transcript'],
 'Agentic AI plans multiple steps and takes actions with tools. The other options are single content-generation tasks.'],
['以下哪个场景属于智能体 AI，而不是一次性的生成式 AI 回答？',
 ['助手通过 API 查询库存、下补货单，并给供应商发确认邮件','模型根据要点写商品描述','模型把手册翻译成法语','模型总结会议记录'],
 '智能体 AI 会规划多个步骤并借助工具执行操作；其他选项都是单次内容生成。']);

/* ===== 1.2 ===== */
Q('1.2','single',[0],
['A retail chain wants to predict each store\'s sales for next quarter from several years of weekly sales history. Which technique fits best?',
 ['Time-series forecasting','Clustering','Binary classification','Dimensionality reduction'],
 'Predicting future values from ordered historical values is forecasting.'],
['某零售连锁希望根据多年的每周销售历史，预测每家门店下季度的销售额。哪种技术最合适？',
 ['时间序列预测','聚类','二分类','降维'],
 '根据有序的历史数值预测未来值，就是时间序列预测。']);
Q('1.2','single',[0],
['A bank wants to flag card transactions that look unusual compared with each customer\'s normal behavior. It has very few confirmed fraud labels. Which technique fits best?',
 ['Anomaly detection','Regression','Recommendation','Text summarization'],
 'Anomaly detection finds rare events that differ from normal patterns and works even with few labeled examples.'],
['银行希望标记与客户平时行为相比显得异常的刷卡交易，但已确认的欺诈标签极少。哪种技术最合适？',
 ['异常检测','回归','推荐','文本摘要'],
 '异常检测能发现偏离正常模式的罕见事件，即使有标签的样本很少也适用。']);
Q('1.2','single',[0],
['A clinic wants a voice bot on its phone line that understands when callers want to reschedule, collects the new date, and works with Amazon Connect. Which service should it use?',
 ['Amazon Lex','Amazon Polly','Amazon Transcribe','Amazon Personalize'],
 'Lex builds conversational bots using intents and slots and integrates with Amazon Connect. Polly and Transcribe only convert speech.'],
['诊所希望在电话线路上部署语音机器人，理解来电者想改约、收集新日期，并与 Amazon Connect 配合使用。应该用哪个服务？',
 ['Amazon Lex','Amazon Polly','Amazon Transcribe','Amazon Personalize'],
 'Lex 基于意图和槽位构建对话机器人，并与 Amazon Connect 集成。Polly 和 Transcribe 只负责语音转换。']);
Q('1.2','multi',[0,1],
['Which of these are good uses of AI/ML? (Choose TWO.)',
 ['Inspecting millions of product images for defects','Flagging scans that a radiologist should review first','Calculating sales tax from fixed statutory rates','Producing contract totals that must always be exact','Sorting a list of names alphabetically'],
 'AI adds value through scale and decision support. Exact, rule-defined calculations and simple sorting should be ordinary code.'],
['以下哪些适合使用 AI/ML？（选择两项）',
 ['检查数百万张商品图片中的缺陷','标记出放射科医生应优先查看的影像','按固定法定税率计算销售税','生成必须始终精确的合同金额','按字母顺序排列姓名列表'],
 'AI 的价值在于规模化和辅助决策。精确的规则计算和简单排序应使用普通代码。']);
Q('1.2','single',[0],
['An insurer receives thousands of scanned claim forms, many filled in by hand. It needs the field names and values as structured data. Which service fits?',
 ['Amazon Textract','Amazon Comprehend','Amazon Rekognition','Amazon Translate'],
 'Textract extracts printed and handwritten text, key-value pairs and tables from documents.'],
['保险公司每天收到数千份扫描的理赔表，很多是手写的。需要把字段名和值提取为结构化数据。应选哪个服务？',
 ['Amazon Textract','Amazon Comprehend','Amazon Rekognition','Amazon Translate'],
 'Textract 可从文档中提取印刷体和手写文字、键值对和表格。']);
Q('1.2','single',[0],
['A startup with no ML expertise must add sentiment analysis of customer reviews within a week. What is the best approach?',
 ['Call Amazon Comprehend\'s pre-trained sentiment API','Collect labeled data and train a custom model on SageMaker AI','Pre-train a new language model','Use Amazon Rekognition'],
 'A managed AI service delivers the capability immediately without training or ML skills.'],
['一家没有 ML 经验的初创公司必须在一周内加上客户评论的情感分析。最佳做法是什么？',
 ['调用 Amazon Comprehend 预训练的情感分析 API','收集有标签数据并在 SageMaker AI 上训练自定义模型','预训练一个新的语言模型','使用 Amazon Rekognition'],
 '托管 AI 服务无需训练和 ML 技能即可立即提供该能力。']);
Q('1.2','single',[0],
['Support agents chat in English with customers who write in Spanish, Japanese and German. Messages must be converted between languages in real time. Which service fits?',
 ['Amazon Translate','Amazon Polly','Amazon Lex','Amazon Textract'],
 'Translate provides real-time neural machine translation.'],
['客服人员用英语与使用西班牙语、日语和德语的客户聊天，消息需要实时在语言之间转换。应选哪个服务？',
 ['Amazon Translate','Amazon Polly','Amazon Lex','Amazon Textract'],
 'Translate 提供实时神经机器翻译。']);

/* ===== 1.3 ===== */
Q('1.3','single',[0],
['A team wants the same engineered features to be available for model training and for low-latency lookups at inference time. Which SageMaker AI feature fits?',
 ['SageMaker Feature Store','SageMaker Ground Truth','SageMaker Clarify','SageMaker Model Cards'],
 'Feature Store keeps features in offline (training) and online (inference) stores so both use consistent values.'],
['团队希望同一套工程化特征既能用于模型训练，也能在推理时低延迟查询。应选 SageMaker AI 的哪个功能？',
 ['SageMaker Feature Store','SageMaker Ground Truth','SageMaker Clarify','SageMaker Model Cards'],
 'Feature Store 提供离线（训练）和在线（推理）存储，确保两边使用一致的特征值。']);
Q('1.3','single',[0],
['Every time new data lands in S3, a team wants to automatically run data preparation, training, evaluation and model registration in a repeatable way. What should it use?',
 ['SageMaker Pipelines','Amazon Polly','AWS Artifact','Amazon Macie'],
 'SageMaker Pipelines orchestrates ML workflows as repeatable CI/CD pipelines, a core MLOps practice.'],
['每当有新数据进入 S3，团队希望以可重复的方式自动执行数据准备、训练、评估和模型注册。应该使用什么？',
 ['SageMaker Pipelines','Amazon Polly','AWS Artifact','Amazon Macie'],
 'SageMaker Pipelines 把 ML 工作流编排成可重复的 CI/CD 流水线，是 MLOps 的核心实践。']);
Q('1.3','single',[0],
['Where should a team keep versions of trained models along with their approval status before deployment?',
 ['SageMaker Model Registry','Amazon S3 Glacier','AWS Trusted Advisor','Amazon CloudFront'],
 'Model Registry catalogs model versions, metadata and approval status, supporting production readiness.'],
['团队应该把训练好的模型版本及其审批状态保存在哪里，以便部署前管理？',
 ['SageMaker Model Registry','Amazon S3 Glacier','AWS Trusted Advisor','Amazon CloudFront'],
 'Model Registry 记录模型版本、元数据和审批状态，支持生产就绪。']);
Q('1.3','single',[0],
['A startup needs a generative AI feature live next week. It has no ML operations team and usage is unpredictable. Which way of using a model fits best?',
 ['A managed API service such as Amazon Bedrock','Self-hosting an open model on EC2 GPU instances','Training a custom model from scratch','Running a SageMaker real-time endpoint 24/7'],
 'A managed API needs no infrastructure, starts fast and bills per use.'],
['一家初创公司下周就要上线生成式 AI 功能，没有 ML 运维团队，使用量不可预测。哪种使用模型的方式最合适？',
 ['使用 Amazon Bedrock 等托管 API 服务','在 EC2 GPU 实例上自托管开源模型','从零训练自定义模型','全天候运行 SageMaker 实时端点'],
 '托管 API 无需基础设施、上手快、按用量计费。']);
Q('1.3','multi',[0,1],
['Which of the following are MLOps practices? (Choose TWO.)',
 ['Track every experiment\'s data version, parameters and metrics','Automatically retrain when monitoring detects drift','Copy model files to production servers by hand','Skip testing to release models faster','Keep undocumented notebooks as the only record of a model'],
 'MLOps emphasizes experiment tracking, automation, monitoring and re-training, and reducing technical debt.'],
['以下哪些属于 MLOps 实践？（选择两项）',
 ['记录每次实验的数据版本、参数和指标','监控发现漂移时自动重新训练','手动把模型文件复制到生产服务器','为加快发布而跳过测试','只用无文档的笔记本作为模型的唯一记录'],
 'MLOps 强调实验跟踪、自动化、监控与再训练，以及减少技术债。']);
Q('1.3','single',[0],
['A classifier has precision 0.60 and recall 0.90. What is its F1 score?',
 ['0.72','0.75','0.54','0.90'],
 'F1 = 2 × P × R / (P + R) = 2 × 0.54 / 1.5 = 0.72.'],
['某分类器精确率为 0.60，召回率为 0.90。它的 F1 分数是多少？',
 ['0.72','0.75','0.54','0.90'],
 'F1 = 2 × P × R / (P + R) = 2 × 0.54 / 1.5 = 0.72。']);
Q('1.3','single',[0],
['An ML project cost $200,000 to build and run for a year and saved $500,000. What is its ROI?',
 ['150%','250%','60%','40%'],
 'ROI = (benefit − cost) ÷ cost = (500,000 − 200,000) ÷ 200,000 = 1.5 = 150%.'],
['某 ML 项目一年的建设和运行成本为 20 万美元，节省了 50 万美元。它的 ROI 是多少？',
 ['150%','250%','60%','40%'],
 'ROI = (收益 − 成本) ÷ 成本 = (500,000 − 200,000) ÷ 200,000 = 1.5 = 150%。']);

/* ===== 2.1 ===== */
Q('2.1','single',[0],
['What does the embedding model do in a RAG application?',
 ['Converts document chunks and user questions into vectors so similar meanings can be found','Generates the final answer shown to the user','Encrypts documents at rest','Splits documents into pages'],
 'Embeddings turn text into vectors; similarity search over those vectors finds relevant chunks.'],
['在 RAG 应用中，嵌入模型的作用是什么？',
 ['把文档块和用户问题转换为向量，以便找到语义相近的内容','生成展示给用户的最终答案','对静态文档加密','把文档按页拆分'],
 '嵌入把文本转换为向量，再对这些向量做相似度搜索以找到相关块。']);
Q('2.1','order',[],
['Put the steps of preparing and searching documents for semantic search in order.',
 ['Split the documents into chunks','Convert each chunk into an embedding','Store the vectors in a vector database','Embed the user\'s query','Retrieve the nearest chunks'],
 'Documents are chunked, embedded and stored ahead of time; at query time the question is embedded and compared with the stored vectors.'],
['请按顺序排列为语义搜索准备并检索文档的步骤。',
 ['把文档切分成块','把每个块转换为嵌入向量','把向量存入向量数据库','对用户查询做嵌入','检索最接近的块'],
 '文档预先分块、嵌入并存储；查询时把问题嵌入后与已存向量比较。']);
Q('2.1','single',[0],
['A user pastes a 400-page contract into a chat app and the model returns an error. What is the most likely cause?',
 ['The input exceeds the model\'s context window','The temperature is set too low','The model has not been fine-tuned','The stop sequence is missing'],
 'Each model has a maximum number of tokens per request. Chunking with RAG, or a model with a larger context window, solves it.'],
['用户把一份 400 页的合同粘贴到聊天应用中，模型返回错误。最可能的原因是什么？',
 ['输入超出了模型的上下文窗口','温度设得太低','模型没有经过微调','缺少停止序列'],
 '每个模型单次请求都有最大 Token 数。用 RAG 分块处理，或换上下文窗口更大的模型即可解决。']);
Q('2.1','single',[0],
['Which statement about output tokens is correct?',
 ['Generating more output tokens increases both cost and response time','Output tokens are always free on Amazon Bedrock','Output length has no effect on latency','Output tokens cost less than input tokens for every model'],
 'Output tokens are billed and generated one at a time, so longer answers cost more and take longer. They usually cost more per token than input.'],
['关于输出 Token，哪种说法正确？',
 ['生成更多输出 Token 会同时增加成本和响应时间','在 Amazon Bedrock 上输出 Token 始终免费','输出长度对延迟没有影响','对所有模型而言，输出 Token 都比输入 Token 便宜'],
 '输出 Token 要计费，且逐个生成，因此回答越长越贵越慢。输出单价通常高于输入。']);
Q('2.1','multi',[0,1],
['Which are core components of an AI agent? (Choose TWO.)',
 ['Tools the agent can call, such as APIs','Memory of the conversation and past sessions','ROUGE score','Provisioned Throughput','Top-K sampling'],
 'Agents combine a reasoning model with tools, memory and planning. The other options are metrics or settings.'],
['以下哪些是 AI 智能体的核心组成？（选择两项）',
 ['智能体可调用的工具，如 API','对话和历史会话的记忆','ROUGE 分数','预置吞吐量','Top-K 采样'],
 '智能体由推理模型结合工具、记忆和规划组成；其他选项是指标或参数设置。']);
Q('2.1','single',[0],
['A travel assistant should remember each customer\'s preferred seat and language across separate conversations weeks apart. What does this require?',
 ['Long-term memory stored outside the context window','A larger max-tokens setting','A lower temperature','A stop sequence'],
 'Short-term memory lives in the current context window. Preferences that persist across sessions need long-term memory, such as AgentCore Memory.'],
['旅行助手需要在相隔数周的不同对话中，记住每位客户偏好的座位和语言。这需要什么？',
 ['保存在上下文窗口之外的长期记忆','更大的最大 Token 设置','更低的温度','停止序列'],
 '短期记忆位于当前上下文窗口中；跨会话保留的偏好需要长期记忆，例如 AgentCore Memory。']);
Q('2.1','match',[],
['Match each multi-agent pattern to how it works.',
 [['Sequential','Each agent\'s output becomes the next agent\'s input'],['Parallel','Agents work on independent sub-tasks at the same time'],['Supervisor','A lead agent delegates work and combines the results'],['Swarm','Peers hand work to each other with no central controller']],
 'These are the common patterns for multi-agent systems.'],
['将每种多智能体模式与其工作方式匹配。',
 [['顺序式','每个智能体的输出成为下一个智能体的输入'],['并行式','智能体同时处理互不依赖的子任务'],['主管式','主智能体分派工作并汇总结果'],['蜂群式','智能体之间直接交接，没有中央控制者']],
 '这些是多智能体系统的常见模式。']);
Q('2.1','single',[0],
['An insurer\'s claim process must follow the same fixed, auditable steps every time. Which approach fits best?',
 ['A deterministic workflow, such as Amazon Bedrock Flows or AWS Step Functions','A fully autonomous swarm of agents','A single prompt with high temperature','Continued pre-training'],
 'When the process is known and must be predictable and auditable, a fixed workflow is better than letting an agent choose each step.'],
['保险公司的理赔流程每次都必须遵循相同、固定且可审计的步骤。哪种方式最合适？',
 ['确定性工作流，如 Amazon Bedrock Flows 或 AWS Step Functions','完全自主的智能体蜂群','单个高温度提示','持续预训练'],
 '流程已知且必须可预测、可审计时，固定工作流比让智能体自行决定每一步更合适。']);
Q('2.1','single',[0],
['In the Model Context Protocol, what does an MCP server do?',
 ['Exposes a system\'s tools, resources and prompts so that MCP clients in AI applications can use them','Trains foundation models','Stores embeddings for RAG','Encrypts prompts in transit'],
 'An MCP server wraps a system (for example a ticketing tool) and exposes capabilities; MCP clients inside agents discover and call them.'],
['在模型上下文协议中，MCP 服务器的作用是什么？',
 ['对外暴露某个系统的工具、资源和提示，供 AI 应用中的 MCP 客户端使用','训练基础模型','为 RAG 存储嵌入','在传输中加密提示'],
 'MCP 服务器封装某个系统（如工单工具）并暴露其能力；智能体中的 MCP 客户端负责发现并调用。']);
Q('2.1','single',[0],
['Which stage of the foundation model lifecycle is usually the most expensive?',
 ['Pre-training','Prompt engineering','Evaluation','Collecting user feedback'],
 'Pre-training processes trillions of tokens on thousands of accelerators for weeks or months.'],
['基础模型生命周期中哪个阶段通常最昂贵？',
 ['预训练','提示工程','评估','收集用户反馈'],
 '预训练要在数千块加速卡上处理数万亿 Token，持续数周到数月。']);

/* ===== 2.2 ===== */
Q('2.2','single',[0],
['A support team complains that the same customer question gets noticeably different answers each time. Which change helps most?',
 ['Lower the temperature and use a prompt template with a fixed output format','Increase the temperature','Remove the system prompt','Increase Top-K'],
 'Nondeterminism is reduced by lower temperature and structured, templated prompts.'],
['客服团队反映同一个客户问题每次得到的回答差异明显。哪种调整最有帮助？',
 ['调低温度，并使用固定输出格式的提示模板','调高温度','去掉系统提示','调高 Top-K'],
 '调低温度并使用结构化的模板提示，可以减少非确定性。']);
Q('2.2','multi',[0,1],
['Which are advantages of generative AI? (Choose TWO.)',
 ['One model adapts to many tasks through prompts','A natural, conversational interface','Guaranteed factual accuracy','Full interpretability of every answer','Identical output for identical input'],
 'Adaptability and conversational capability are strengths. Accuracy, interpretability and determinism are known limitations.'],
['以下哪些是生成式 AI 的优势？（选择两项）',
 ['一个模型通过提示适应多种任务','自然的对话式交互界面','保证事实准确','每个答案都完全可解释','相同输入必定得到相同输出'],
 '适应性和对话能力是优势；准确性、可解释性和确定性是已知局限。']);
Q('2.2','single',[0],
['A legal team needs to analyze 300-page contracts in a single request. Which model selection factor matters most?',
 ['Context window size (maximum input length)','Image generation quality','Number of voices supported','Embedding dimensions'],
 'The whole document must fit in the model\'s context window, so input length capacity is the deciding factor.'],
['法务团队需要在一次请求中分析 300 页的合同。选择模型时哪个因素最重要？',
 ['上下文窗口大小（最大输入长度）','图像生成质量','支持的语音数量','嵌入维度'],
 '整份文档必须放进模型的上下文窗口，因此输入长度容量是决定性因素。']);
Q('2.2','single',[0],
['A regulator asks why an LLM-based system rejected a claim, and the team cannot trace the reasoning. Which GenAI limitation is this?',
 ['Interpretability','Adaptability','Responsiveness','Low barrier to entry'],
 'Large neural models are hard to interpret. Where decisions must be explained, consider interpretable models, citations and human review.'],
['监管机构询问基于 LLM 的系统为何拒绝某笔理赔，团队无法追溯其推理过程。这是生成式 AI 的哪项局限？',
 ['可解释性差','适应性','响应速度','上手门槛低'],
 '大型神经网络模型难以解释。必须说明决策依据时，应考虑可解释模型、引用来源和人工复核。']);
Q('2.2','single',[0],
['Which metric estimates the total revenue a business expects from one customer over the whole relationship?',
 ['Customer lifetime value (CLV)','Average revenue per user (ARPU)','Conversion rate','Perplexity'],
 'CLV looks at the whole customer relationship; ARPU is revenue per user over a period.'],
['哪个指标估算企业在整个客户关系期间预计从一位客户获得的总收入？',
 ['客户终身价值 (CLV)','每用户平均收入 (ARPU)','转化率','困惑度'],
 'CLV 着眼于整个客户关系周期；ARPU 是某段时间内的人均收入。']);
Q('2.2','single',[0],
['A company wants one foundation model to serve its HR, legal and marketing teams instead of a separate model for each. Which business metric describes how well that works?',
 ['Cross-domain performance','Perplexity','Average handle time','Epoch count'],
 'Cross-domain performance measures how well a model handles different departments and task types.'],
['公司希望用一个基础模型同时服务人事、法务和市场团队，而不是各用一个模型。哪个业务指标描述这种做法的效果？',
 ['跨领域表现','困惑度','平均处理时长','训练轮数'],
 '跨领域表现衡量模型在不同部门和任务类型上的效果。']);

/* ===== 2.3 ===== */
Q('2.3','single',[0],
['Which AWS-designed chip is built for high-throughput, low-cost inference?',
 ['AWS Inferentia','AWS Trainium','AWS Graviton for storage','Amazon S3 Glacier'],
 'Inferentia is optimized for inference; Trainium is optimized for training.'],
['哪款 AWS 自研芯片专为高吞吐、低成本推理而设计？',
 ['AWS Inferentia','AWS Trainium','用于存储的 AWS Graviton','Amazon S3 Glacier'],
 'Inferentia 针对推理优化；Trainium 针对训练优化。']);
Q('2.3','single',[0],
['Data scientists want to fine-tune an open-source Llama model and host it on an endpoint they control, starting from a curated model hub. Which option fits?',
 ['Amazon SageMaker JumpStart','Amazon Quick','Amazon Polly','AWS Artifact'],
 'JumpStart offers pre-trained open models that can be fine-tuned and deployed to SageMaker endpoints in a few clicks.'],
['数据科学家希望从精选模型中心出发，微调开源的 Llama 模型，并托管在自己控制的端点上。哪个选项合适？',
 ['Amazon SageMaker JumpStart','Amazon Quick','Amazon Polly','AWS Artifact'],
 'JumpStart 提供预训练开源模型，几次点击即可微调并部署到 SageMaker 端点。']);
Q('2.3','single',[0],
['Business users without coding skills want an AI assistant that answers questions across company data, builds dashboards and automates routine tasks. Which service fits?',
 ['Amazon Quick','Amazon SageMaker AI','AWS Trainium','Strands Agents'],
 'Amazon Quick is the ready-made agentic workspace for business users.'],
['不会编程的业务用户希望有一个 AI 助手，能跨公司数据回答问题、制作仪表板并自动完成日常任务。哪个服务合适？',
 ['Amazon Quick','Amazon SageMaker AI','AWS Trainium','Strands Agents'],
 'Amazon Quick 是面向业务用户的现成智能体工作空间。']);
Q('2.3','single',[0],
['A development team wants an IDE where AI agents turn written requirements into a design and a task list, then implement the tasks. Which tool fits?',
 ['Kiro','Amazon Lex','AWS Config','Amazon Textract'],
 'Kiro is an agentic IDE built around spec-driven development.'],
['开发团队希望使用一种 IDE，让 AI 智能体把书面需求转化为设计和任务清单，再逐项实现。哪个工具合适？',
 ['Kiro','Amazon Lex','AWS Config','Amazon Textract'],
 'Kiro 是围绕规格驱动开发构建的智能体 IDE。']);
Q('2.3','single',[0],
['A company wants agentic AI to help migrate legacy .NET Framework and mainframe applications to modern architectures. Which service fits?',
 ['AWS Transform','Amazon Personalize','Amazon Comprehend','AWS Trusted Advisor'],
 'AWS Transform uses agents to accelerate migration and modernization.'],
['公司希望借助智能体 AI 把遗留的 .NET Framework 和大型机应用迁移到现代架构。哪个服务合适？',
 ['AWS Transform','Amazon Personalize','Amazon Comprehend','AWS Trusted Advisor'],
 'AWS Transform 利用智能体加速迁移和现代化。']);
Q('2.3','multi',[0,1],
['Which are benefits of building generative AI applications on Amazon Bedrock? (Choose TWO.)',
 ['No infrastructure to provision or manage','Access to foundation models from several providers through one API','You must buy and install your own GPUs','Model providers receive your prompts for training','Only Amazon-built models are available'],
 'Bedrock is serverless and offers many providers\' models. It does not share your data with providers or use it for training.'],
['在 Amazon Bedrock 上构建生成式 AI 应用有哪些好处？（选择两项）',
 ['无需预置或管理基础设施','通过一个 API 使用多家提供商的基础模型','必须自行购买并安装 GPU','模型提供商会收到你的提示用于训练','只能使用亚马逊自研模型'],
 'Bedrock 是无服务器的，提供多家提供商的模型，不会与提供商共享数据或用于训练。']);
Q('2.3','single',[0],
['Thousands of requests a day start with the same 20-page policy document followed by a short user question. Which Bedrock feature cuts cost and latency most?',
 ['Prompt caching','Provisioned Throughput','A higher temperature','Model evaluation'],
 'Prompt caching reuses the processed shared prefix; cached tokens are billed at a steep discount (up to about 90% for supported models).'],
['每天数千个请求都以同一份 20 页政策文档开头，后接一个简短的用户问题。Bedrock 的哪个功能最能降低成本和延迟？',
 ['提示缓存','预置吞吐量','调高温度','模型评估'],
 '提示缓存复用已处理的共享前缀，缓存 Token 按大幅折扣计费（受支持模型最高约 90%）。']);
Q('2.3','single',[0],
['A team fine-tuned a model in Amazon Bedrock. According to Bedrock\'s general rule, what must it purchase to run inference on the custom model?',
 ['Provisioned Throughput','A SageMaker Savings Plan','Batch inference credits','An AWS Artifact agreement'],
 'AWS documents that customized models require Provisioned Throughput. As an exception, some customized models (certain Amazon Nova and Llama models in specific Regions) can now use on-demand deployment.'],
['团队在 Amazon Bedrock 中微调了一个模型。按照 Bedrock 的一般规则，要对这个定制模型进行推理必须购买什么？',
 ['预置吞吐量','SageMaker Savings Plan','批量推理额度','AWS Artifact 协议'],
 'AWS 文档说明定制模型需要预置吞吐量。例外是：部分定制模型（特定区域的某些 Amazon Nova 和 Llama 模型）现在可以按需部署。']);
Q('2.3','single',[0],
['During traffic peaks a Bedrock application hits throughput limits in one Region. What can spread requests across Regions in the same geography automatically?',
 ['Cross-Region inference','Amazon CloudFront caching','Batch inference','AWS Artifact'],
 'Cross-Region inference routes requests to other Regions within a geography to increase throughput and availability. Check data residency requirements.'],
['流量高峰时，某 Bedrock 应用在一个区域触及吞吐量上限。什么能自动把请求分散到同一地理范围内的其他区域？',
 ['跨区域推理','Amazon CloudFront 缓存','批量推理','AWS Artifact'],
 '跨区域推理把请求路由到同一地理范围内的其他区域，以提升吞吐量和可用性。需核对数据驻留要求。']);
Q('2.3','match',[],
['Match each Amazon Bedrock pricing option to when it fits.',
 [['On-demand','Pay per token for variable or unpredictable traffic'],['Batch inference','Large offline jobs at a lower price, results later'],['Provisioned Throughput','Reserved model units for guaranteed, steady throughput'],['Prompt caching','Cheaper, faster requests that share a long prompt prefix']],
 'These are the main cost levers for Bedrock workloads.'],
['将每种 Amazon Bedrock 计费方式与适用场景匹配。',
 [['按需','流量多变或不可预测，按 Token 付费'],['批量推理','大型离线任务，价格更低，结果稍后返回'],['预置吞吐量','预留模型单元，获得有保障的稳定吞吐'],['提示缓存','共享长提示前缀的请求更便宜更快']],
 '这些是 Bedrock 工作负载的主要成本手段。']);

/* ===== 3.1 ===== */
Q('3.1','single',[0],
['A chatbot sometimes produces odd, unlikely words. The team wants to cut these out while keeping some variety. Which change fits?',
 ['Lower Top-P so only the most probable tokens are considered','Increase the maximum tokens','Increase Top-P to 1.0','Remove the stop sequences'],
 'Lower Top-P restricts sampling to the most probable tokens, removing the long tail of unlikely words.'],
['聊天机器人偶尔会生成奇怪、罕见的词。团队希望去掉这些词，同时保留一定多样性。哪种调整合适？',
 ['调低 Top-P，只考虑概率最高的 Token','调高最大 Token 数','把 Top-P 调到 1.0','移除停止序列'],
 '调低 Top-P 会把采样限制在高概率 Token 中，去掉罕见词的长尾。']);
Q('3.1','single',[0],
['A model should stop generating as soon as it writes the closing tag </answer>. What should be configured?',
 ['A stop sequence','A higher temperature','Top-K','Provisioned Throughput'],
 'Stop sequences end generation when a specified string is produced.'],
['模型应在写出闭合标签 </answer> 后立即停止生成。应该配置什么？',
 ['停止序列','更高的温度','Top-K','预置吞吐量'],
 '停止序列会在生成指定字符串时结束生成。']);
Q('3.1','single',[0],
['A RAG application needs to use relationships between entities (customers, products, suppliers) when retrieving context. Which vector store fits?',
 ['Amazon Neptune Analytics (GraphRAG)','Amazon S3 Glacier','Amazon DynamoDB','AWS Artifact'],
 'Neptune Analytics combines a graph with vector search, enabling GraphRAG in Bedrock Knowledge Bases.'],
['某 RAG 应用在检索上下文时需要利用实体（客户、产品、供应商）之间的关系。哪种向量存储合适？',
 ['Amazon Neptune Analytics (GraphRAG)','Amazon S3 Glacier','Amazon DynamoDB','AWS Artifact'],
 'Neptune Analytics 将图与向量搜索结合，可在 Bedrock 知识库中实现 GraphRAG。']);
Q('3.1','single',[0],
['A company must store billions of embeddings as cheaply as possible, and they are queried only occasionally. Which option supported by Bedrock Knowledge Bases fits best?',
 ['Amazon S3 Vectors','Amazon ElastiCache','A SageMaker real-time endpoint','Amazon CloudFront'],
 'S3 Vectors provides low-cost, durable vector storage with sub-second queries, best for infrequent query workloads.'],
['公司必须以尽可能低的成本存储数十亿个嵌入，而且只是偶尔查询。Bedrock 知识库支持的哪个选项最合适？',
 ['Amazon S3 Vectors','Amazon ElastiCache','SageMaker 实时端点','Amazon CloudFront'],
 'S3 Vectors 提供低成本、持久的向量存储和亚秒级查询，最适合低频查询场景。']);
Q('3.1','multi',[0,1],
['Which are advantages of RAG compared with fine-tuning? (Choose TWO.)',
 ['Knowledge can be updated by re-syncing documents, without retraining','Answers can cite their source documents','It permanently changes the model\'s writing style','It needs no data at all','It always has lower latency than any other approach'],
 'RAG keeps knowledge fresh without training and supports citations. Changing style is what fine-tuning does.'],
['与微调相比，RAG 有哪些优势？（选择两项）',
 ['重新同步文档即可更新知识，无需重新训练','答案可以引用来源文档','会永久改变模型的写作风格','完全不需要数据','延迟始终低于其他任何方法'],
 'RAG 无需训练就能保持知识新鲜，并支持引用。改变风格是微调的作用。']);
Q('3.1','single',[0],
['Which Amazon Bedrock Knowledge Bases API retrieves relevant chunks AND returns a generated answer with citations in one call?',
 ['RetrieveAndGenerate','Retrieve','ApplyGuardrail','CreateModelCustomizationJob'],
 'Retrieve returns only the chunks; RetrieveAndGenerate also calls the model and returns a cited answer.'],
['Amazon Bedrock 知识库的哪个 API 能在一次调用中检索相关块并返回带引用的生成答案？',
 ['RetrieveAndGenerate','Retrieve','ApplyGuardrail','CreateModelCustomizationJob'],
 'Retrieve 只返回块；RetrieveAndGenerate 还会调用模型并返回带引用的答案。']);
Q('3.1','order',[],
['Put the stages of a RAG request in order.',
 ['Documents are chunked, embedded and stored','The user submits a question','The most similar chunks are retrieved','The chunks are added to the prompt','The model generates an answer with citations'],
 'Ingest → ask → retrieve → augment → generate.'],
['请按顺序排列一次 RAG 请求的各个阶段。',
 ['文档被分块、嵌入并存储','用户提交问题','检索最相似的块','把这些块加入提示','模型生成带引用的答案'],
 '导入 → 提问 → 检索 → 增强 → 生成。']);
Q('3.1','single',[0],
['Which task is best suited to an AI agent rather than a single prompt to a model?',
 ['Processing an insurance claim: check the policy database, validate documents, calculate the payout and request approval','Writing a tagline for a product','Translating a paragraph into Spanish','Summarizing a news article'],
 'Agents shine on multi-step tasks that need tools and decisions along the way.'],
['哪项任务最适合交给 AI 智能体，而不是对模型发一次提示？',
 ['处理保险理赔：查询保单数据库、核验材料、计算赔付金额并申请审批','为产品写一句广告语','把一段文字翻译成西班牙语','总结一篇新闻'],
 '智能体擅长需要工具和中途决策的多步骤任务。']);
Q('3.1','single',[0],
['An Amazon Bedrock agent can cancel bookings. The business wants the customer to confirm before any cancellation is executed. What should be configured?',
 ['User confirmation for that action before the agent invokes it','A higher temperature','Batch inference','A larger context window'],
 'Bedrock Agents can require user confirmation (or return control to the app) before invoking an action, keeping a human in the loop for sensitive operations.'],
['某 Amazon Bedrock 智能体可以取消预订。业务要求执行任何取消前必须由客户确认。应该配置什么？',
 ['在智能体调用该操作前要求用户确认','更高的温度','批量推理','更大的上下文窗口'],
 'Bedrock Agents 可在调用操作前要求用户确认（或把控制权交还应用），让敏感操作保留人工把关。']);
Q('3.1','single',[0],
['Which customization approach adds cost mainly through longer prompts on every call, with no training at all?',
 ['In-context learning (few-shot prompting)','Fine-tuning','Continued pre-training','Pre-training from scratch'],
 'In-context learning puts examples in the prompt, so the cost appears as extra input tokens on each request.'],
['哪种定制方式完全不需要训练，主要通过每次调用时更长的提示增加成本？',
 ['上下文学习（少样本提示）','微调','持续预训练','从零预训练'],
 '上下文学习把示例放在提示中，所以成本体现为每次请求额外的输入 Token。']);

/* ===== 3.2 ===== */
Q('3.2','single',[0],
['A prompt begins: "You are an experienced tax accountant who explains things simply." What is this part of the prompt?',
 ['A role (persona) instruction, often set in the system prompt','A negative prompt','A stop sequence','An embedding'],
 'Assigning a role sets tone and expertise for the whole conversation.'],
['某提示以“你是一位经验丰富、讲解通俗易懂的税务会计师。”开头。这是提示的哪一部分？',
 ['角色（人设）指令，通常放在系统提示中','否定提示','停止序列','嵌入'],
 '设定角色可以为整个对话确定语气和专业程度。']);
Q('3.2','single',[0],
['A health-insurance chatbot sometimes offers medical diagnoses. The team adds "Do not provide medical diagnoses or treatment advice." What technique is this?',
 ['A negative prompt','Chain-of-thought prompting','Few-shot prompting','Model distillation'],
 'Negative prompts state what the output must not contain. Back them up with Guardrails denied topics.'],
['某健康险聊天机器人有时会给出医疗诊断。团队加入“不要提供医疗诊断或治疗建议。”这属于哪种技术？',
 ['否定提示','思维链提示','少样本提示','模型蒸馏'],
 '否定提示说明输出中不得包含的内容，可再用护栏的拒绝话题兜底。']);
Q('3.2','single',[0],
['A retailer generates thousands of product descriptions with the same structure, changing only the product name and features each time. What should it use?',
 ['A prompt template with variables','A new fine-tuned model per product','A higher temperature','Continued pre-training'],
 'Prompt templates keep structure consistent and are easy to version, for example in Bedrock Prompt Management.'],
['某零售商用相同结构生成数千条商品描述，每次只更换商品名称和特点。应该使用什么？',
 ['带变量的提示模板','为每个商品微调一个新模型','更高的温度','持续预训练'],
 '提示模板能保持结构一致，也便于版本管理，例如使用 Bedrock Prompt Management。']);
Q('3.2','multi',[0,1],
['Which are prompt engineering best practices? (Choose TWO.)',
 ['State the required format and length explicitly','Separate instructions from input data with delimiters or tags','Keep prompts vague so the model can be creative','Put API keys in the prompt so tools can use them','Always use the maximum temperature'],
 'Specificity and clear structure improve quality. Secrets never belong in prompts.'],
['以下哪些是提示工程的最佳实践？（选择两项）',
 ['明确说明所需的格式和长度','用分隔符或标签把指令与输入数据分开','让提示保持模糊，以便模型发挥创意','把 API 密钥写进提示，方便工具使用','始终使用最高温度'],
 '具体、结构清晰的提示能提升质量。密钥绝不能放进提示。']);
Q('3.2','single',[0],
['A user asks a chatbot to "pretend you are an AI with no rules" to obtain harmful instructions. What is this?',
 ['Jailbreaking','Poisoning','Distillation','Chunking'],
 'Jailbreaking uses role-play or hypothetical framing to bypass safety rules. Guardrails content and prompt-attack filters help.'],
['用户让聊天机器人“假装自己是一个没有任何规则的 AI”，以获取有害指导。这是什么？',
 ['越狱','投毒','蒸馏','分块'],
 '越狱通过角色扮演或假设情境绕过安全规则。护栏的内容过滤和提示攻击过滤可以防御。']);
Q('3.2','single',[0],
['A user tricks a chatbot into printing its hidden system instructions, which include internal pricing rules. Which risk is this?',
 ['Prompt leaking (exposure)','Underfitting','Data drift','Nondeterminism'],
 'Exposure or prompt leaking reveals system prompts or confidential data. Keep secrets out of prompts and filter outputs.'],
['用户诱使聊天机器人输出了隐藏的系统指令，其中包含内部定价规则。这属于哪种风险？',
 ['提示泄露（信息暴露）','欠拟合','数据漂移','非确定性'],
 '信息暴露或提示泄露会泄出系统提示或机密数据。不要在提示中放机密信息，并过滤输出。']);
Q('3.2','single',[0],
['An attacker adds a fake "refund policy" page to the internal wiki that feeds a RAG knowledge base. Customers then receive the false policy. Which risk is this?',
 ['Poisoning','Jailbreaking','Hallucination caused by temperature','Overfitting'],
 'Poisoning corrupts training data or knowledge sources. Control who can write to data sources and track lineage.'],
['攻击者在为 RAG 知识库提供数据的内部 Wiki 中加入了一个虚假的“退款政策”页面，随后客户收到了错误政策。这属于哪种风险？',
 ['投毒','越狱','温度导致的幻觉','过拟合'],
 '投毒会污染训练数据或知识来源。应控制数据源的写入权限并跟踪数据血缘。']);
Q('3.2','match',[],
['Match each prompt risk to its most direct defense.',
 [['Prompt injection','Guardrails prompt-attack filter and tagging untrusted content'],['Poisoning','Vetting and restricting who can change data sources'],['Prompt leaking','Keeping secrets out of prompts and filtering outputs'],['Jailbreaking','Content filters plus a firm system prompt']],
 'Each risk has a primary control; in practice they are layered together.'],
['将每种提示风险与最直接的防御措施匹配。',
 [['提示注入','护栏提示攻击过滤，并标记不可信内容'],['投毒','审核并限制谁能修改数据源'],['提示泄露','不在提示中放机密信息，并过滤输出'],['越狱','内容过滤加上严格的系统提示']],
 '每种风险都有主要控制措施，实际中会多层叠加使用。']);
Q('3.2','single',[0],
['A model\'s output format is inconsistent, and the team has several good examples of the desired output. What is the quickest improvement?',
 ['Few-shot prompting with those examples','Pre-training a new model','Increasing Top-K','Buying Provisioned Throughput'],
 'Few-shot examples show the model the exact format, with no training needed.'],
['模型的输出格式不一致，而团队手头有几个理想输出的好例子。最快的改进方法是什么？',
 ['用这些例子做少样本提示','预训练一个新模型','调高 Top-K','购买预置吞吐量'],
 '少样本示例能直接向模型展示格式，无需训练。']);

/* ===== 3.3 ===== */
Q('3.3','single',[0],
['What is instruction tuning?',
 ['Fine-tuning a model on many instruction → response examples so it follows instructions reliably','Adding instructions to the system prompt at run time','Training a reward model from human rankings','Compressing a model into a smaller one'],
 'Instruction tuning is a form of supervised fine-tuning on labeled instruction-response pairs across many tasks.'],
['什么是指令微调？',
 ['用大量“指令 → 回答”示例微调模型，使其可靠地遵循指令','在运行时把指令加入系统提示','根据人类排序训练奖励模型','把模型压缩成更小的模型'],
 '指令微调是一种监督微调，使用覆盖多种任务的有标签指令-回答对。']);
Q('3.3','single',[0],
['How must training data for an Amazon Bedrock fine-tuning job be provided?',
 ['As JSONL files of prompt-completion records stored in Amazon S3','As a PDF uploaded in the console chat window','As rows in an Amazon DynamoDB table','As embeddings in OpenSearch'],
 'Bedrock customization jobs read JSONL training (and optional validation) files from S3.'],
['Amazon Bedrock 微调任务的训练数据必须以什么形式提供？',
 ['存放在 Amazon S3 中、由 prompt-completion 记录组成的 JSONL 文件','在控制台聊天窗口上传的 PDF','Amazon DynamoDB 表中的行','OpenSearch 中的嵌入'],
 'Bedrock 定制任务从 S3 读取 JSONL 格式的训练（及可选验证）文件。']);
Q('3.3','multi',[0,1],
['Which practices improve a fine-tuning dataset? (Choose TWO.)',
 ['Remove duplicates, errors and toxic examples','Make sure examples represent all the user groups the model will serve','Add as much unfiltered web text as possible','Keep customer PII to improve personalization','Let each labeler use their own labeling rules'],
 'Curated, representative data with consistent labels and no PII makes a better, fairer model.'],
['哪些做法能改进微调数据集？（选择两项）',
 ['去除重复、错误和有害的示例','确保示例覆盖模型将服务的所有用户群体','尽可能多地加入未经筛选的网络文本','保留客户 PII 以改善个性化','让每位标注员按自己的规则标注'],
 '经过筛选、有代表性、标注一致且不含 PII 的数据，能训练出更好、更公平的模型。']);
Q('3.3','single',[0],
['A factory takes a model pre-trained on millions of general images and trains it further on 2,000 labeled photos of its own product defects. What is this?',
 ['Transfer learning','Unsupervised clustering','Reinforcement learning','Pre-training from scratch'],
 'Reusing a pre-trained model\'s knowledge and adapting it with a smaller task dataset is transfer learning.'],
['一家工厂把在数百万张通用图片上预训练的模型，再用 2,000 张自家产品缺陷的标注照片继续训练。这是什么？',
 ['迁移学习','无监督聚类','强化学习','从零预训练'],
 '复用预训练模型的知识，再用较小的任务数据集进行适配，就是迁移学习。']);
Q('3.3','order',[],
['Put the steps of reinforcement learning from human feedback (RLHF) in order.',
 ['Fine-tune the model on human-written demonstration answers','Have humans rank several model responses to the same prompt','Train a reward model on those rankings','Optimize the model with reinforcement learning against the reward model'],
 'RLHF: supervised fine-tuning → human rankings → reward model → RL optimization.'],
['请按顺序排列基于人类反馈的强化学习 (RLHF) 的步骤。',
 ['用人工撰写的示范答案微调模型','让人对同一提示的多个模型回答进行排序','用这些排序训练奖励模型','以奖励模型为目标，用强化学习优化模型'],
 'RLHF：监督微调 → 人工排序 → 奖励模型 → 强化学习优化。']);
Q('3.3','single',[0],
['A team wants to fine-tune a large model cheaply by training only a small set of added weights while keeping the original weights frozen. What is this approach called?',
 ['Parameter-efficient fine-tuning (PEFT), for example LoRA','Pre-training','Prompt caching','Batch inference'],
 'PEFT methods such as LoRA train small adapters, cutting compute and storage costs.'],
['团队希望低成本地微调大模型：只训练少量新增权重，而冻结原有权重。这种方法叫什么？',
 ['参数高效微调 (PEFT)，例如 LoRA','预训练','提示缓存','批量推理'],
 'LoRA 等 PEFT 方法只训练小型适配器，降低算力和存储成本。']);
Q('3.3','single',[0],
['Which AWS service provides workflows and a human workforce to label training data and collect human preference rankings?',
 ['Amazon SageMaker Ground Truth','Amazon Macie','AWS Glue Data Catalog','Amazon Inspector'],
 'Ground Truth supports data labeling and human feedback collection, including for RLHF.'],
['哪个 AWS 服务提供标注训练数据、收集人类偏好排序的工作流和人工团队？',
 ['Amazon SageMaker Ground Truth','Amazon Macie','AWS Glue Data Catalog','Amazon Inspector'],
 'Ground Truth 支持数据标注和人类反馈收集，也可用于 RLHF。']);

/* ===== 3.4 ===== */
Q('3.4','single',[0],
['A team is evaluating a system that converts English product manuals into Japanese. Which automatic metric is traditionally used?',
 ['BLEU','ROUGE','RMSE','AUC-ROC'],
 'BLEU measures n-gram precision against reference translations.'],
['团队正在评估把英文产品手册翻译成日文的系统。传统上使用哪个自动指标？',
 ['BLEU','ROUGE','RMSE','AUC-ROC'],
 'BLEU 衡量与参考译文的 n-gram 精确率。']);
Q('3.4','single',[0],
['Answers that correctly paraphrase the reference get low scores from an n-gram metric. The team wants a metric based on meaning. Which should it use?',
 ['BERTScore','BLEU','Word count','Perplexity'],
 'BERTScore compares contextual embeddings, so paraphrases with the same meaning score well.'],
['正确改写参考答案的回答在 n-gram 指标上得分很低。团队希望使用基于语义的指标。应该用哪个？',
 ['BERTScore','BLEU','字数','困惑度'],
 'BERTScore 比较上下文嵌入，意思相同的改写也能得高分。']);
Q('3.4','single',[0],
['A bank wants to judge whether chatbot answers show empathy and follow its brand tone. Which evaluation approach is most suitable?',
 ['Human evaluation by trained reviewers','BLEU against reference answers','Perplexity','Counting tokens'],
 'Subjective qualities such as tone and empathy are best judged by people (possibly supplemented by LLM-as-a-judge).'],
['银行想评判聊天机器人的回答是否有同理心、是否符合品牌语气。哪种评估方式最合适？',
 ['由经过培训的评审员进行人工评估','对照参考答案计算 BLEU','困惑度','统计 Token 数'],
 '语气、同理心等主观质量最适合由人来评判（可辅以 LLM 作为评审）。']);
Q('3.4','single',[0],
['A team wants to compare candidate models consistently on the same fixed set of questions with known reference answers. What should it use?',
 ['A benchmark (golden) dataset','Random user conversations','Model Cards','CloudTrail logs'],
 'Benchmark datasets give repeatable, comparable scores across models.'],
['团队希望在同一组带参考答案的固定问题上，一致地比较候选模型。应该使用什么？',
 ['基准（黄金）数据集','随机的用户对话','Model Cards','CloudTrail 日志'],
 '基准数据集能提供可重复、可比较的跨模型分数。']);
Q('3.4','multi',[0,1],
['Which metrics are most useful for evaluating an AI agent? (Choose TWO.)',
 ['Task completion rate','Tool selection accuracy','BLEU score','Perplexity','Number of model parameters'],
 'Agents are judged on whether they finish tasks and use the right tools correctly, plus cost, latency and safety.'],
['评估 AI 智能体时，哪些指标最有用？（选择两项）',
 ['任务完成率','工具选择准确率','BLEU 分数','困惑度','模型参数数量'],
 '评估智能体要看能否完成任务、是否正确选择和使用工具，以及成本、延迟和安全性。']);
Q('3.4','match',[],
['Match each metric to what it is mainly used for.',
 [['ROUGE','Summarization quality (recall-oriented)'],['BLEU','Machine translation quality (precision-oriented)'],['BERTScore','Semantic similarity to a reference'],['Perplexity','How well a language model predicts text']],
 'Know which metric belongs to which task.'],
['将每个指标与其主要用途匹配。',
 [['ROUGE','摘要质量（侧重召回）'],['BLEU','机器翻译质量（侧重精确）'],['BERTScore','与参考答案的语义相似度'],['困惑度','语言模型预测文本的能力']],
 '要清楚每个指标对应哪类任务。']);
Q('3.4','single',[0],
['A RAG assistant gives wrong answers, and investigation shows it is fetching irrelevant documents. Which aspect should the team measure and improve first?',
 ['Retrieval quality: context relevance and coverage','Output token count','Temperature','BLEU score of the answers'],
 'If retrieval fails, generation cannot recover. Measure context relevance and coverage, then tune chunking, embeddings or queries.'],
['某 RAG 助手给出错误答案，排查发现它检索到了不相关的文档。团队应首先衡量并改进哪方面？',
 ['检索质量：上下文相关性和覆盖度','输出 Token 数','温度','答案的 BLEU 分数'],
 '检索出了问题，生成阶段也无法补救。应衡量上下文相关性和覆盖度，再调整分块、嵌入或查询。']);
Q('3.4','single',[0],
['A contact center wants to know how much each AI-handled customer conversation costs on average. Which business alignment metric is this?',
 ['Cost per interaction','Task completion rate','User satisfaction','ROUGE'],
 'Cost per interaction divides total model, tool and infrastructure cost by the number of conversations.'],
['联络中心想知道每次由 AI 处理的客户对话平均花费多少。这是哪个业务对齐指标？',
 ['每次交互成本','任务完成率','用户满意度','ROUGE'],
 '每次交互成本 = 模型、工具和基础设施总成本 ÷ 对话数。']);

/* ===== 4.1 ===== */
Q('4.1','single',[0],
['A company wants its assistant to never output a specific list of competitor product names. Which Guardrails policy is simplest?',
 ['Word filters','Contextual grounding check','Automated Reasoning checks','Sensitive information filters'],
 'Word filters block exact words and phrases you list, including profanity.'],
['公司希望助手绝不输出一份指定的竞争对手产品名称清单。哪项护栏策略最简单？',
 ['词语过滤器','上下文依据检查','自动推理检查','敏感信息过滤器'],
 '词语过滤器会屏蔽你列出的具体词语和短语，包括脏话。']);
Q('4.1','single',[0],
['An HR policy assistant must have its answers checked against formal logic rules derived from the leave policy, with verifiable explanations. Which Guardrails feature fits?',
 ['Automated Reasoning checks','Word filters','Denied topics','Content filters for violence'],
 'Automated Reasoning checks validate responses against logical rules built from your policy documents.'],
['人事政策助手的回答必须依据从休假政策中提炼的形式化逻辑规则进行校验，并给出可验证的解释。应选哪个护栏功能？',
 ['自动推理检查','词语过滤器','拒绝话题','暴力内容过滤器'],
 '自动推理检查依据从政策文档构建的逻辑规则验证回答。']);
Q('4.1','single',[0],
['A team wants to apply the same Bedrock guardrail to a model hosted on a SageMaker AI endpoint. How?',
 ['Call the ApplyGuardrail API on the inputs and outputs','It is impossible; guardrails only work inside Bedrock model calls','Copy the guardrail into the model weights','Use AWS Artifact'],
 'The ApplyGuardrail API evaluates text against a guardrail independently of which model produced it.'],
['团队想把同一个 Bedrock 护栏应用到托管在 SageMaker AI 端点上的模型。怎么做？',
 ['对输入和输出调用 ApplyGuardrail API','做不到，护栏只能用于 Bedrock 内的模型调用','把护栏复制进模型权重','使用 AWS Artifact'],
 'ApplyGuardrail API 可独立于生成文本的模型，用护栏评估任意文本。']);
Q('4.1','multi',[0,1],
['Which are among AWS\'s core dimensions of responsible AI? (Choose TWO.)',
 ['Controllability','Veracity and robustness','Profitability','Virality','Lowest latency'],
 'AWS lists fairness, explainability, privacy and security, safety, controllability, veracity and robustness, governance and transparency.'],
['以下哪些属于 AWS 负责任 AI 的核心维度？（选择两项）',
 ['可控性','真实性与鲁棒性','盈利能力','传播性','最低延迟'],
 'AWS 列出的维度包括公平性、可解释性、隐私与安全、安全性、可控性、真实性与鲁棒性、治理和透明度。']);
Q('4.1','single',[0],
['A team computes the model\'s accuracy separately for each age group and compares the results. What is this technique called?',
 ['Subgroup analysis','Chunking','Hyperparameter tuning','Distillation'],
 'Subgroup analysis reveals whether some groups get worse results, a key bias check.'],
['团队分别计算模型在各年龄段上的准确率并进行比较。这种方法叫什么？',
 ['子群体分析','分块','超参数调优','蒸馏'],
 '子群体分析能发现某些群体是否得到更差的结果，是关键的偏见检查。']);
Q('4.1','single',[0],
['Reviewers find that different annotators often gave the same example different labels. What should the team perform?',
 ['Label quality analysis, then clearer labeling guidelines','Increase the temperature','Add more epochs','Switch to batch inference'],
 'Inconsistent labels teach the model noise and can embed bias. Measure agreement and fix the guidelines.'],
['评审发现不同标注员经常给同一个样本打不同的标签。团队应该做什么？',
 ['进行标注质量分析，再制定更清晰的标注指南','调高温度','增加训练轮数','改用批量推理'],
 '不一致的标签会让模型学到噪声，还可能引入偏见。应衡量一致性并修订指南。']);
Q('4.1','single',[0],
['An airline\'s chatbot invents a bereavement refund policy, and a court orders the airline to honor it. Which legal risk does this illustrate?',
 ['Hallucinations creating liability','Intellectual property infringement','Data residency violation','Underfitting'],
 'Hallucinated statements can bind the company. Grounding with RAG, contextual grounding checks and human review reduce the risk.'],
['某航空公司的聊天机器人编造了一条丧亲退款政策，法院判令航空公司兑现。这说明了哪种法律风险？',
 ['幻觉带来的法律责任','知识产权侵权','违反数据驻留','欠拟合'],
 '幻觉陈述可能约束公司。用 RAG 提供依据、上下文依据检查和人工复核可以降低风险。']);
Q('4.1','single',[0],
['Which action reduces overfitting?',
 ['Adding regularization and more varied training data','Training for many more epochs','Making the model much more complex','Removing the validation set'],
 'Regularization, more data, simpler models and early stopping all reduce variance.'],
['哪种做法能减轻过拟合？',
 ['加入正则化并使用更多样的训练数据','大幅增加训练轮数','让模型复杂得多','去掉验证集'],
 '正则化、更多数据、更简单的模型和提前停止都能降低方差。']);
Q('4.1','single',[0],
['A voice assistant works well for most users but often fails for people with strong regional accents. What is the most likely root cause?',
 ['The training data was not diverse or inclusive enough','The temperature was too high','The stop sequence was wrong','The model was served with batch inference'],
 'Under-represented groups get worse accuracy. Collect inclusive, balanced audio data.'],
['某语音助手对大多数用户效果很好，但对口音较重的用户经常失败。最可能的根本原因是什么？',
 ['训练数据的多样性和包容性不足','温度太高','停止序列错误','模型使用了批量推理'],
 '占比不足的群体准确率更低。应收集包容、均衡的音频数据。']);
Q('4.1','single',[0],
['A model was fair at launch, but over months its approval rates for one group drift lower. Which service can detect this in production?',
 ['Amazon SageMaker Model Monitor (bias drift)','AWS Artifact','Amazon Polly','Amazon CloudFront'],
 'Model Monitor integrates with Clarify to watch bias drift and feature attribution drift over time.'],
['某模型上线时是公平的，但几个月后对某一群体的批准率逐渐下降。哪个服务能在生产中发现这一点？',
 ['Amazon SageMaker Model Monitor（偏差漂移）','AWS Artifact','Amazon Polly','Amazon CloudFront'],
 'Model Monitor 与 Clarify 集成，持续监控偏差漂移和特征归因漂移。']);

/* ===== 4.2 ===== */
Q('4.2','single',[0],
['Where does AWS document the intended use cases, limitations and responsible AI design of its own AI services, such as Amazon Rekognition?',
 ['AWS AI Service Cards','SageMaker Model Cards','AWS Artifact','AWS CloudTrail'],
 'AI Service Cards are AWS\'s transparency documents for its AI services. Model Cards are for documenting your own models.'],
['AWS 在哪里记录其自家 AI 服务（如 Amazon Rekognition）的预期用例、局限性和负责任 AI 设计？',
 ['AWS AI Service Cards','SageMaker Model Cards','AWS Artifact','AWS CloudTrail'],
 'AI Service Cards 是 AWS 为自家 AI 服务提供的透明度文档；Model Cards 用于记录你自己的模型。']);
Q('4.2','single',[0],
['A loan officer wants to see which input features pushed a particular application\'s risk score up or down. Which tool provides this?',
 ['SageMaker Clarify feature attributions (SHAP values)','Amazon Bedrock batch inference','AWS Budgets','Amazon Translate'],
 'Clarify explains individual predictions and overall feature importance.'],
['信贷员想知道哪些输入特征推高或拉低了某份申请的风险评分。哪个工具提供这一功能？',
 ['SageMaker Clarify 的特征归因（SHAP 值）','Amazon Bedrock 批量推理','AWS Budgets','Amazon Translate'],
 'Clarify 可解释单个预测以及整体特征重要性。']);
Q('4.2','single',[0],
['Why might a company choose NOT to publish its full system prompt and guardrail configuration, even though it values transparency?',
 ['Attackers could use the details to bypass the protections','It would make the model more accurate','It is illegal to publish prompts','It would increase token costs'],
 'This is the transparency vs safety/security tradeoff.'],
['即使公司重视透明度，为什么可能选择不公开完整的系统提示和护栏配置？',
 ['攻击者可能利用这些细节绕过防护','这会让模型更准确','公开提示是违法的','这会增加 Token 成本'],
 '这就是透明度与安全之间的权衡。']);
Q('4.2','single',[0],
['A research team must be able to inspect a model\'s architecture and weights for an audit. Which kind of model best supports this?',
 ['An open-source (open-weight) model','A proprietary model available only through an API','Any model with a higher temperature','A model hosted behind Amazon CloudFront'],
 'Open models allow inspection and testing; licensing terms still apply.'],
['研究团队必须能够检查模型的架构和权重以便审计。哪种模型最能支持这一点？',
 ['开源（开放权重）模型','只能通过 API 使用的商业模型','温度更高的任意模型','部署在 Amazon CloudFront 后面的模型'],
 '开放模型允许检查和测试，但仍需遵守许可条款。']);
Q('4.2','multi',[0,1],
['Which AWS tools help make ML models transparent and explainable? (Choose TWO.)',
 ['Amazon SageMaker Model Cards','Amazon SageMaker Clarify','Amazon Polly','AWS Budgets','Amazon Translate'],
 'Model Cards document models; Clarify explains predictions and detects bias.'],
['哪些 AWS 工具有助于让 ML 模型透明、可解释？（选择两项）',
 ['Amazon SageMaker Model Cards','Amazon SageMaker Clarify','Amazon Polly','AWS Budgets','Amazon Translate'],
 'Model Cards 记录模型信息；Clarify 解释预测并检测偏差。']);
Q('4.2','single',[0],
['A loan app shows the AI\'s recommendation together with its top three reasons, and a loan officer makes the final decision. Which human-centered design principle is this?',
 ['Amplifying human decision-making with transparent AI recommendations','Removing humans from high-stakes decisions','Hiding AI involvement','Maximizing model complexity'],
 'AI supports and explains; the human keeps authority over high-stakes outcomes.'],
['某贷款应用展示 AI 的建议及其三大理由，由信贷员做最终决定。这体现了哪项以人为本的设计原则？',
 ['用透明的 AI 建议增强人的决策','让人退出高风险决策','隐藏 AI 的参与','最大化模型复杂度'],
 'AI 提供支持和解释，人保留对高风险结果的决定权。']);

/* ===== 5.1 ===== */
Q('5.1','single',[0],
['A company must control and rotate its own encryption keys for training data in S3 and for its custom models. What should it use?',
 ['AWS KMS customer managed keys','AWS Artifact','Amazon Inspector','Amazon CloudFront'],
 'Customer managed KMS keys give you control over key policies, rotation and usage for encryption at rest.'],
['公司必须自行控制并轮换用于加密 S3 训练数据和定制模型的密钥。应该使用什么？',
 ['AWS KMS 客户托管密钥','AWS Artifact','Amazon Inspector','Amazon CloudFront'],
 '客户托管的 KMS 密钥让你掌控密钥策略、轮换和使用，用于静态加密。']);
Q('5.1','single',[0],
['An AI application calls a third-party API with an API key. Where should the key be stored?',
 ['AWS Secrets Manager','In the system prompt','Hard-coded in the source code','In a public S3 bucket'],
 'Secrets Manager stores and rotates secrets; they should never appear in prompts or code.'],
['某 AI 应用使用 API 密钥调用第三方 API。密钥应该存放在哪里？',
 ['AWS Secrets Manager','系统提示中','硬编码在源代码里','公开的 S3 存储桶中'],
 'Secrets Manager 负责存储和轮换密钥；密钥绝不应出现在提示或代码中。']);
Q('5.1','single',[0],
['An application\'s role should be able to invoke only one approved Bedrock model and nothing else. What implements this?',
 ['An IAM policy allowing bedrock:InvokeModel only on that model\'s ARN','A Guardrails word filter','AWS Artifact','A higher temperature'],
 'Least-privilege IAM policies scope actions to specific resources.'],
['某应用的角色只能调用一个经批准的 Bedrock 模型，不能调用其他任何模型。用什么实现？',
 ['只对该模型 ARN 允许 bedrock:InvokeModel 的 IAM 策略','护栏词语过滤器','AWS Artifact','更高的温度'],
 '最小权限的 IAM 策略会把操作限定在特定资源上。']);
Q('5.1','single',[0],
['An agent must never call the refund tool for amounts over $500, and this rule must be enforced deterministically, outside the agent\'s own code. What fits?',
 ['Policy in Amazon Bedrock AgentCore (enforced at the Gateway)','A sentence in the system prompt','A lower temperature','Amazon Macie'],
 'Policy in AgentCore evaluates every tool call at the Gateway against Cedar policies (which can be authored in natural language) before allowing it.'],
['智能体绝不能对超过 500 美元的金额调用退款工具，且这条规则必须在智能体自身代码之外确定性地强制执行。什么合适？',
 ['Amazon Bedrock AgentCore 中的 Policy（在 Gateway 处执行）','系统提示中的一句话','更低的温度','Amazon Macie'],
 'AgentCore 中的 Policy 会在 Gateway 处依据 Cedar 策略（可用自然语言编写）评估每次工具调用后再放行。']);
Q('5.1','multi',[0,1],
['Which are privacy-enhancing technologies for AI training data? (Choose TWO.)',
 ['Pseudonymization or tokenization of identifiers','Masking sensitive fields','Raising the model temperature','Publishing the raw dataset openly','Disabling encryption to speed up training'],
 'Privacy-enhancing technologies include anonymization, pseudonymization, masking, aggregation, differential privacy and encryption.'],
['以下哪些属于 AI 训练数据的隐私增强技术？（选择两项）',
 ['对标识符进行假名化或令牌化','对敏感字段进行掩码','调高模型温度','公开发布原始数据集','为加快训练而关闭加密'],
 '隐私增强技术包括匿名化、假名化、掩码、聚合、差分隐私和加密。']);
Q('5.1','single',[0],
['A company must prove its training data files in S3 were never altered or deleted after approval. What helps most?',
 ['S3 Versioning with S3 Object Lock','A larger context window','Amazon Polly','Top-P sampling'],
 'Object Lock makes objects immutable for a retention period, supporting data integrity.'],
['公司必须证明审批后 S3 中的训练数据文件从未被修改或删除。什么最有帮助？',
 ['S3 版本控制加 S3 对象锁定','更大的上下文窗口','Amazon Polly','Top-P 采样'],
 '对象锁定可在保留期内使对象不可更改，保障数据完整性。']);
Q('5.1','single',[0],
['An LLM generates SQL queries from user questions. What should happen before a query runs against the database?',
 ['Validate the query (read-only, allowed tables) and run it with a least-privilege database user','Run it immediately; model output is trustworthy','Ask the model if the query is safe and skip other checks','Increase the temperature'],
 'Treat model output as untrusted input: validate and filter it, and limit what it can do.'],
['某 LLM 根据用户问题生成 SQL 查询。查询在数据库上执行前应该怎么做？',
 ['校验查询（只读、仅允许的表），并用最小权限的数据库用户执行','立即执行，模型输出可信','问模型查询是否安全，然后跳过其他检查','调高温度'],
 '要把模型输出当作不可信输入：校验、过滤，并限制其权限。']);
Q('5.1','single',[0],
['Data scientists may query a customer table in the data lake but must not see the email and phone columns. Which service enforces this?',
 ['AWS Lake Formation fine-grained (column-level) permissions','Amazon Rekognition','Amazon Bedrock Knowledge Bases','Amazon CloudFront'],
 'Lake Formation provides table-, column- and row-level access control for data lakes.'],
['数据科学家可以查询数据湖中的客户表，但不能看到邮箱和电话列。哪个服务能实现这一点？',
 ['AWS Lake Formation 细粒度（列级）权限','Amazon Rekognition','Amazon Bedrock 知识库','Amazon CloudFront'],
 'Lake Formation 为数据湖提供表级、列级和行级访问控制。']);
Q('5.1','single',[0],
['A RAG assistant should send answers with a low grounding score to a human agent instead of showing them. Which technique is this?',
 ['Confidence scoring with a threshold','Prompt caching','Model distillation','Batch inference'],
 'Confidence scores (such as grounding and relevance scores) let you route uncertain answers to "I don\'t know" or a person.'],
['某 RAG 助手应把依据分数低的答案转给人工客服，而不是直接展示。这是哪种技术？',
 ['带阈值的置信度评分','提示缓存','模型蒸馏','批量推理'],
 '置信度分数（如依据分和相关性分）可以把不确定的答案转为“我不知道”或交给人工。']);

/* ===== 5.2 ===== */
Q('5.2','single',[0],
['Which service checks an account for idle or underused resources, open security groups and approaching service quotas?',
 ['AWS Trusted Advisor','AWS Artifact','Amazon Macie','Amazon Translate'],
 'Trusted Advisor gives best-practice checks across cost, performance, security, fault tolerance and service quotas.'],
['哪个服务会检查账户中闲置或利用率低的资源、对外开放的安全组以及即将触顶的服务配额？',
 ['AWS Trusted Advisor','AWS Artifact','Amazon Macie','Amazon Translate'],
 'Trusted Advisor 提供成本、性能、安全、容错和服务配额方面的最佳实践检查。']);
Q('5.2','single',[0],
['Employees use a free, public generative AI chatbot website to draft emails. Which scope of the Generative AI Security Scoping Matrix is this?',
 ['Scope 1: Consumer app','Scope 3: Pre-trained models','Scope 4: Fine-tuned models','Scope 5: Self-trained models'],
 'Using a public consumer GenAI service as-is is Scope 1; the company controls only what staff type in.'],
['员工使用免费的公共生成式 AI 聊天网站起草邮件。这属于生成式 AI 安全范围矩阵的哪个范围？',
 ['范围 1：消费级应用','范围 3：预训练模型','范围 4：微调模型','范围 5：自训练模型'],
 '直接使用公共消费级生成式 AI 服务属于范围 1，公司只能控制员工输入的内容。']);
Q('5.2','single',[0],
['A company licenses a SaaS customer-support platform that includes built-in generative AI features, under an enterprise agreement. Which scope applies?',
 ['Scope 2: Enterprise app','Scope 1: Consumer app','Scope 3: Pre-trained models','Scope 5: Self-trained models'],
 'Third-party business applications with GenAI features, used under an enterprise agreement, are Scope 2.'],
['公司在企业协议下采购了一款内置生成式 AI 功能的 SaaS 客服平台。适用哪个范围？',
 ['范围 2：企业级应用','范围 1：消费级应用','范围 3：预训练模型','范围 5：自训练模型'],
 '在企业协议下使用带生成式 AI 功能的第三方商业应用，属于范围 2。']);
Q('5.2','order',[],
['Order the Generative AI Security Scoping Matrix scopes from LEAST to MOST customer ownership and control.',
 ['Consumer app','Enterprise app','Pre-trained models','Fine-tuned models','Self-trained models'],
 'Scopes 1 to 5: responsibility grows as you own more of the model and application.'],
['按客户掌控程度从低到高排列生成式 AI 安全范围矩阵的各个范围。',
 ['消费级应用','企业级应用','预训练模型','微调模型','自训练模型'],
 '范围 1 到 5：拥有的模型和应用越多，责任越大。']);
Q('5.2','single',[0],
['Policy says chat transcripts must be deleted 90 days after creation. Which data governance strategy is this, and how can it be automated in S3?',
 ['Data retention, automated with S3 Lifecycle expiration rules','Data residency, automated with CloudFront','Data lineage, automated with Macie','Observability, automated with Polly'],
 'Retention defines how long data is kept; S3 Lifecycle rules can expire objects automatically.'],
['政策规定聊天记录必须在创建 90 天后删除。这属于哪项数据治理策略，如何在 S3 中自动实现？',
 ['数据保留，用 S3 生命周期过期规则自动实现','数据驻留，用 CloudFront 自动实现','数据血缘，用 Macie 自动实现','可观测性，用 Polly 自动实现'],
 '保留策略规定数据保存多久；S3 生命周期规则可自动让对象过期删除。']);
Q('5.2','single',[0],
['Which AI governance framework is organized around the functions Govern, Map, Measure and Manage?',
 ['NIST AI Risk Management Framework','ISO/IEC 27001','PCI DSS','The AWS shared responsibility model'],
 'The NIST AI RMF uses these four functions. ISO/IEC 42001 is the AI management system standard.'],
['哪个 AI 治理框架围绕“治理、映射、衡量、管理”四项职能组织？',
 ['NIST AI 风险管理框架','ISO/IEC 27001','PCI DSS','AWS 责任共担模型'],
 'NIST AI RMF 使用这四项职能；ISO/IEC 42001 是 AI 管理体系标准。']);
Q('5.2','multi',[0,1],
['Which are sound governance protocols for AI systems? (Choose TWO.)',
 ['Scheduled reviews plus an extra review whenever the model or data changes','Required training for staff on responsible AI use','Skipping documentation to move faster','Letting each developer set their own AI policy','Turning off audit logs to save cost'],
 'Governance relies on policies, review cadence, documentation, transparency standards and training.'],
['以下哪些是合理的 AI 系统治理规程？（选择两项）',
 ['定期审查，并在模型或数据变化时额外审查','要求员工接受负责任 AI 使用培训','为了加快进度而省略文档','让每位开发者自行制定 AI 政策','为节省成本关闭审计日志'],
 '治理依靠政策、审查频率、文档、透明度标准和培训。']);
Q('5.2','single',[0],
['Before launch, an architect wants a structured review of a generative AI workload against AWS best practices, including a Generative AI lens. Which tool fits?',
 ['AWS Well-Architected Tool','AWS Artifact','Amazon Macie','Amazon Polly'],
 'The Well-Architected Tool reviews workloads against the pillars, with specialized lenses such as Machine Learning and Generative AI.'],
['上线前，架构师希望依据 AWS 最佳实践（包括生成式 AI 透镜）对某生成式 AI 工作负载进行结构化评审。哪个工具合适？',
 ['AWS Well-Architected Tool','AWS Artifact','Amazon Macie','Amazon Polly'],
 'Well-Architected Tool 按各支柱评审工作负载，并提供机器学习、生成式 AI 等专用透镜。']);
Q('5.2','single',[0],
['The operations team wants an alert when the number of model invocations or errors suddenly spikes. Which service provides this?',
 ['Amazon CloudWatch alarms','AWS Artifact','AWS Config rules only','Amazon Textract'],
 'CloudWatch collects Bedrock and SageMaker metrics and can alarm on thresholds.'],
['运维团队希望在模型调用次数或错误数突然激增时收到告警。哪个服务提供这一功能？',
 ['Amazon CloudWatch 告警','AWS Artifact','仅 AWS Config 规则','Amazon Textract'],
 'CloudWatch 收集 Bedrock 和 SageMaker 的指标，并可按阈值告警。']);
Q('5.2','match',[],
['Match each data governance strategy to an example.',
 [['Lifecycle','Move old training data to S3 Glacier, then delete it after five years'],['Residency','Keep EU customer data only in EU Regions'],['Retention','Keep audit logs for seven years because regulators require it'],['Logging','Record every access to the training dataset']],
 'These strategies are listed in Task 5.2.'],
['将每项数据治理策略与示例匹配。',
 [['生命周期','把旧训练数据移到 S3 Glacier，五年后删除'],['驻留','欧盟客户数据只保存在欧盟区域'],['保留','因监管要求将审计日志保存七年'],['日志','记录对训练数据集的每一次访问']],
 '这些策略列在任务 5.2 中。']);
})();
