/* Third question set: ordering and matching practice. Append-only: add new questions at the end. */
(function(){
function Q(k,t,en,zh){AIF.qs.push({k:k,d:'d'+k.charAt(0),t:t,a:[],en:{q:en[0],o:en[1],x:en[2]},zh:{q:zh[0],o:zh[1],x:zh[2]}});}

/* ---------- ordering ---------- */
Q('1.1','order',
['Put the uses of a dataset\'s three splits in the order they happen.',
 ['Fit the model parameters on the training set','Tune hyperparameters and pick a model on the validation set','Report the final, unbiased score on the test set'],
 'Train first, tune on validation, and touch the test set only once at the end.'],
['按发生顺序排列数据集三个划分的用途。',
 ['在训练集上拟合模型参数','在验证集上调超参数并选模型','在测试集上报告最终的无偏分数'],
 '先训练，再用验证集调优，最后只用一次测试集。']);
Q('1.2','order',
['A contact center analyzes customer sentiment on calls. Put the steps in order.',
 ['Record the customer call','Convert the speech to text with Amazon Transcribe','Detect sentiment in the text with Amazon Comprehend','Store the results in Amazon S3','Show sentiment trends on a dashboard'],
 'Audio must become text before an NLP service can analyze it.'],
['联络中心分析通话中的客户情绪。请按顺序排列步骤。',
 ['录制客户通话','用 Amazon Transcribe 把语音转成文字','用 Amazon Comprehend 识别文本情感','把结果存入 Amazon S3','在仪表板上展示情绪趋势'],
 '音频必须先变成文字，NLP 服务才能分析。']);
Q('1.3','order',
['Put these MLOps steps for releasing a new model version in order.',
 ['Register the new version in SageMaker Model Registry','Get the version approved','Deploy it to an endpoint','Monitor it with SageMaker Model Monitor','Retrain when drift is detected'],
 'Register → approve → deploy → monitor → retrain is the MLOps release loop.'],
['请按顺序排列发布新模型版本的 MLOps 步骤。',
 ['在 SageMaker Model Registry 中注册新版本','获得该版本的审批','部署到端点','用 SageMaker Model Monitor 监控','发现漂移时重新训练'],
 '注册 → 审批 → 部署 → 监控 → 再训练，是 MLOps 的发布循环。']);
Q('2.1','order',
['Put these stages of the foundation model lifecycle in order.',
 ['Select and prepare the data','Pre-train the model','Fine-tune the model','Evaluate the model','Deploy the model'],
 'Data comes first; evaluation happens before deployment; feedback then feeds the next cycle.'],
['请按顺序排列基础模型生命周期的各个阶段。',
 ['选择并准备数据','预训练模型','微调模型','评估模型','部署模型'],
 '数据先行；部署前要先评估；之后的反馈进入下一轮循环。']);
Q('2.1','order',
['Put the steps of one ReAct agent cycle in order.',
 ['Reason about what to do next','Call a tool, such as an API','Observe the tool\'s result','Decide whether the goal is met or another step is needed'],
 'ReAct = reason → act → observe, repeated until the task is done.'],
['请按顺序排列 ReAct 智能体一个循环的步骤。',
 ['推理下一步该做什么','调用工具，例如 API','观察工具返回的结果','判断目标是否完成，还是需要下一步'],
 'ReAct = 推理 → 行动 → 观察，重复直到任务完成。']);
Q('2.3','order',
['Put the steps to build a RAG assistant with Amazon Bedrock Knowledge Bases in order.',
 ['Upload the documents to Amazon S3','Create the knowledge base, choosing an embeddings model and a vector store','Sync the data source to ingest the documents','Call RetrieveAndGenerate from the application'],
 'Data first, then the knowledge base, then ingestion, then queries.'],
['请按顺序排列用 Amazon Bedrock 知识库构建 RAG 助手的步骤。',
 ['把文档上传到 Amazon S3','创建知识库，选择嵌入模型和向量库','同步数据源以导入文档','在应用中调用 RetrieveAndGenerate'],
 '先有数据，再建知识库，然后导入，最后查询。']);
Q('3.2','order',
['Put these prompt-versioning steps with Amazon Bedrock Prompt Management in order.',
 ['Write a draft prompt','Test variants against an evaluation set','Publish a new version','Point the production app at that version','Roll back if the metrics drop'],
 'Draft → test → version → release → roll back when needed.'],
['请按顺序排列使用 Amazon Bedrock Prompt Management 的提示版本管理步骤。',
 ['编写提示草稿','用评估集测试不同写法','发布新版本','让生产应用指向该版本','指标下降时回滚'],
 '草稿 → 测试 → 发版 → 上线 → 必要时回滚。']);
Q('3.3','order',
['Put the steps to fine-tune and use a model in Amazon Bedrock in order.',
 ['Prepare labeled JSONL training data in S3','Create a model customization job','Evaluate the custom model','Set up inference: buy Provisioned Throughput or deploy on-demand if supported','Invoke the custom model from the app'],
 'Data → training job → evaluation → inference capacity → use.'],
['请按顺序排列在 Amazon Bedrock 中微调并使用模型的步骤。',
 ['在 S3 中准备有标签的 JSONL 训练数据','创建模型定制任务','评估定制模型','配置推理：购买预置吞吐量，或在支持时按需部署','在应用中调用定制模型'],
 '数据 → 训练任务 → 评估 → 推理容量 → 使用。']);
Q('3.4','order',
['Put the steps of choosing a model with a structured evaluation in order.',
 ['Define success criteria and metrics','Build an evaluation dataset','Run evaluation jobs on the candidate models','Compare the results','Choose the model that meets the criteria at the lowest cost'],
 'Decide what "good" means before you measure anything.'],
['请按顺序排列通过结构化评估选择模型的步骤。',
 ['确定成功标准和指标','构建评估数据集','对候选模型运行评估任务','比较结果','选择满足标准且成本最低的模型'],
 '先定义什么算“好”，再开始衡量。']);
Q('4.1','order',
['A loan model shows bias against one group. Put the response in order.',
 ['Measure the bias with SageMaker Clarify','Investigate the training data with subgroup analysis','Collect or rebalance data for the affected group','Retrain the model','Monitor bias drift with SageMaker Model Monitor'],
 'Measure, find the cause, fix the data, retrain, then keep watching.'],
['某贷款模型对某一群体存在偏见。请按顺序排列应对步骤。',
 ['用 SageMaker Clarify 衡量偏差','用子群体分析排查训练数据','为受影响群体收集或重新平衡数据','重新训练模型','用 SageMaker Model Monitor 监控偏差漂移'],
 '衡量、找原因、修数据、重训，然后持续监控。']);
Q('5.1','order',
['Put the steps to prepare sensitive documents for a RAG knowledge base in order.',
 ['Scan the S3 bucket with Amazon Macie','Mask or remove the PII that was found','Encrypt the bucket with an AWS KMS key','Ingest the documents into the knowledge base'],
 'Find sensitive data before it can reach the model; protect it before ingestion.'],
['请按顺序排列为 RAG 知识库准备敏感文档的步骤。',
 ['用 Amazon Macie 扫描 S3 存储桶','对发现的 PII 进行掩码或删除','用 AWS KMS 密钥加密存储桶','把文档导入知识库'],
 '在数据接触模型前先找出敏感信息，并在导入前做好保护。']);
Q('5.2','order',
['Put the steps of an AI governance cycle in order.',
 ['Write the AI use policy','Train the team on it','Deploy AI systems with the required controls','Review them on a schedule','Update the policy based on the findings'],
 'Governance is a loop: policy → people → controls → review → improve.'],
['请按顺序排列 AI 治理循环的步骤。',
 ['制定 AI 使用政策','对团队进行培训','按要求的控制措施部署 AI 系统','定期审查','根据发现更新政策'],
 '治理是一个循环：政策 → 人员 → 控制 → 审查 → 改进。']);

/* ---------- matching ---------- */
Q('1.1','match',
['Match each learning type to what it learns from.',
 [['Supervised learning','Labeled examples with the right answers'],['Unsupervised learning','Unlabeled data, to find groups or structure'],['Reinforcement learning','Rewards and penalties from trial and error'],['Self-supervised learning','Labels created from the data itself, such as the next word']],
 'The type of learning is defined by where the "answer" comes from.'],
['将每种学习类型与其学习来源匹配。',
 [['监督学习','带正确答案的有标签示例'],['无监督学习','无标签数据，用于发现分组或结构'],['强化学习','试错中的奖励与惩罚'],['自监督学习','从数据本身生成的标签，如下一个词']],
 '学习类型取决于“答案”从哪里来。']);
Q('1.1','match',
['Match each SageMaker AI inference option to the workload it suits.',
 [['Real-time','Steady traffic that needs millisecond responses'],['Serverless','Intermittent traffic; scale to zero between bursts'],['Asynchronous','Payloads up to 1 GB and processing up to an hour'],['Batch transform','Scoring a whole dataset offline']],
 'Match latency needs and traffic shape to the option.'],
['将每种 SageMaker AI 推理方式与适合的工作负载匹配。',
 [['实时推理','流量稳定、需要毫秒级响应'],['无服务器推理','流量间歇，空闲时缩容到零'],['异步推理','负载最大 1 GB、处理最长 1 小时'],['批量转换','离线对整个数据集打分']],
 '根据延迟要求和流量形态选择方式。']);
Q('1.3','match',
['Match each metric to when it matters most.',
 [['Precision','False positives are costly'],['Recall','False negatives are costly'],['F1 score','You need a balance on imbalanced data'],['RMSE','Measuring errors when predicting numbers']],
 'Precision and recall trade off; F1 balances them; RMSE is for regression.'],
['将每个指标与最重要的使用场景匹配。',
 [['精确率','误报代价高'],['召回率','漏报代价高'],['F1 分数','在不平衡数据上需要兼顾两者'],['RMSE','衡量数值预测的误差']],
 '精确率与召回率此消彼长；F1 兼顾两者；RMSE 用于回归。']);
Q('2.1','match',
['Match each generative AI term to its meaning.',
 [['Token','A unit of text the model reads and writes'],['Embedding','A vector of numbers that captures meaning'],['Chunking','Splitting documents into smaller passages'],['Context window','The maximum tokens a model handles per request']],
 'These four terms appear together in most RAG questions.'],
['将每个生成式 AI 术语与其含义匹配。',
 [['Token','模型读写文本的单位'],['嵌入','表示语义的一组数字向量'],['分块','把文档切成较小的段落'],['上下文窗口','模型单次请求能处理的最大 Token 数']],
 '这四个术语在大多数 RAG 题目中同时出现。']);
Q('2.2','match',
['Match each generative AI limitation to its best mitigation.',
 [['Hallucination','Ground answers with RAG and show citations'],['Nondeterminism','Lower the temperature and use prompt templates'],['Weak arithmetic','Let the model call a calculator tool'],['Low interpretability','Use an interpretable model where each decision must be explained']],
 'Each limitation has a specific control.'],
['将每个生成式 AI 局限与最佳缓解方法匹配。',
 [['幻觉','用 RAG 提供依据并展示引用'],['非确定性','调低温度并使用提示模板'],['算术能力弱','让模型调用计算器工具'],['可解释性差','在每个决策都需解释时使用可解释模型']],
 '每种局限都有对应的控制手段。']);
Q('3.1','match',
['Match each inference parameter to what it controls.',
 [['Temperature','How random the token choice is'],['Top-P','Sampling from the smallest set reaching a cumulative probability'],['Maximum tokens','A hard cap on output length'],['Stop sequence','A string that ends generation']],
 'Randomness, candidate pool, length and stopping point are separate controls.'],
['将每个推理参数与其控制内容匹配。',
 [['温度','选择 Token 的随机程度'],['Top-P','从累计概率达到阈值的最小集合中采样'],['最大 Token 数','输出长度的硬上限'],['停止序列','出现即结束生成的字符串']],
 '随机性、候选范围、长度和停止点是彼此独立的控制项。']);
Q('3.1','match',
['Match each vector store to the situation it suits best.',
 [['Amazon OpenSearch Service','Hybrid keyword and semantic search at scale'],['Amazon Aurora PostgreSQL (pgvector)','Vectors stored next to existing relational data'],['Amazon Neptune Analytics','GraphRAG over relationships between entities'],['Amazon S3 Vectors','Very large, rarely queried vector sets at low cost']],
 'All four can back Bedrock Knowledge Bases.'],
['将每种向量存储与最适合的场景匹配。',
 [['Amazon OpenSearch Service','大规模的关键词 + 语义混合搜索'],['Amazon Aurora PostgreSQL (pgvector)','把向量和现有关系数据放在一起'],['Amazon Neptune Analytics','基于实体关系的 GraphRAG'],['Amazon S3 Vectors','超大规模、很少查询、低成本的向量集']],
 '这四种都可以作为 Bedrock 知识库的存储。']);
Q('3.3','match',
['Match each training method to the data it needs.',
 [['Continued pre-training','Large amounts of unlabeled domain text'],['Fine-tuning','Labeled prompt and response pairs'],['RLHF','Human rankings of model responses'],['Distillation','Responses generated by a larger teacher model']],
 'The data type is often the clue in exam questions.'],
['将每种训练方法与所需数据匹配。',
 [['持续预训练','大量无标签领域文本'],['微调','有标签的提示-回答对'],['RLHF','人类对模型回答的排序'],['蒸馏','由更大的教师模型生成的回答']],
 '数据类型往往是考题中的线索。']);
Q('4.1','match',
['Match each Amazon Bedrock Guardrails policy to what it does.',
 [['Denied topics','Refuses whole subjects you describe in plain language'],['Sensitive information filters','Detects and masks or blocks PII'],['Contextual grounding check','Blocks answers not supported by the source'],['Word filters','Blocks specific words and phrases']],
 'Know which policy solves which problem.'],
['将每项 Amazon Bedrock 护栏策略与其作用匹配。',
 [['拒绝话题','拒绝你用自然语言描述的整个话题'],['敏感信息过滤器','检测 PII 并掩码或拦截'],['上下文依据检查','拦截缺乏来源依据的回答'],['词语过滤器','屏蔽特定词语和短语']],
 '要清楚哪项策略解决哪类问题。']);
Q('4.2','match',
['Match each transparency tool to what it provides.',
 [['SageMaker Model Cards','Documentation of your own model\'s purpose, training and evaluation'],['SageMaker Clarify','Feature attributions (SHAP) and bias reports'],['AWS AI Service Cards','AWS\'s documentation of its own AI services'],['Bedrock Model Evaluation','Side-by-side comparisons of models on your criteria']],
 'Model Cards are yours; AI Service Cards are AWS\'s.'],
['将每个透明度工具与其提供的内容匹配。',
 [['SageMaker Model Cards','记录你自己模型的用途、训练和评估'],['SageMaker Clarify','特征归因 (SHAP) 和偏差报告'],['AWS AI Service Cards','AWS 为自家 AI 服务编写的文档'],['Bedrock 模型评估','按你的标准并排比较模型']],
 'Model Cards 是你的；AI Service Cards 是 AWS 的。']);
Q('5.1','match',
['Match each security service to the job it does in an AI system.',
 [['Amazon Macie','Find PII in S3 before training or ingestion'],['AWS PrivateLink','Reach Bedrock without crossing the internet'],['AWS KMS','Control the keys that encrypt data at rest'],['AWS Secrets Manager','Store and rotate API keys and credentials']],
 'These four appear constantly in Domain 5.'],
['将每个安全服务与其在 AI 系统中的作用匹配。',
 [['Amazon Macie','在训练或导入前查找 S3 中的 PII'],['AWS PrivateLink','不经公网访问 Bedrock'],['AWS KMS','管理静态数据加密所用的密钥'],['AWS Secrets Manager','存储并轮换 API 密钥和凭证']],
 '这四个服务在领域 5 中反复出现。']);
Q('5.2','match',
['Match each Generative AI Security Scoping Matrix scope to an example.',
 [['Scope 1: Consumer app','Staff use a free public chatbot website'],['Scope 3: Pre-trained models','An app calls a Claude model on Amazon Bedrock with RAG'],['Scope 4: Fine-tuned models','A Nova model is fine-tuned on company claims data'],['Scope 5: Self-trained models','A bank pre-trains its own model from scratch']],
 'Ownership and responsibility grow from Scope 1 to Scope 5.'],
['将生成式 AI 安全范围矩阵的每个范围与示例匹配。',
 [['范围 1：消费级应用','员工使用免费的公共聊天网站'],['范围 3：预训练模型','应用通过 Amazon Bedrock 调用 Claude 模型并使用 RAG'],['范围 4：微调模型','用公司理赔数据微调 Nova 模型'],['范围 5：自训练模型','银行从零预训练自己的模型']],
 '从范围 1 到范围 5，所有权和责任逐步增加。']);
})();
