/* CLF-C02 extras: services map (the official in-scope list), flashcards, glossary and the 7-day plan. */
(function(){
/* ---------------- Services: [name, cat, what en, pick-when en, what zh, pick-when zh] ---------------- */
var S = [
/* compute, containers, serverless */
['Amazon EC2','compute','Resizable virtual servers (instances) in many families: general purpose, compute, memory, storage optimized and accelerated.','You need full control of the OS and server.','可调整大小的虚拟服务器（实例），有通用型、计算优化型、内存优化型、存储优化型和加速计算型等多个系列。','需要完全控制操作系统和服务器。'],
['AWS Lambda','compute','Runs code in response to events without servers; pay per request and duration (up to 15 minutes per run).','Event-driven code, no servers to manage.','响应事件运行代码，无需服务器；按请求次数和运行时长付费（每次最长 15 分钟）。','事件驱动的代码，无需管理服务器。'],
['AWS Fargate','compute','Serverless compute engine for containers on Amazon ECS and Amazon EKS.','Run containers without managing EC2 instances.','面向 Amazon ECS 和 Amazon EKS 容器的无服务器计算引擎。','运行容器而无需管理 EC2 实例。'],
['Amazon ECS','compute','AWS’s fully managed container orchestration service.','Run Docker containers the AWS-native way.','AWS 的完全托管容器编排服务。','以 AWS 原生方式运行 Docker 容器。'],
['Amazon EKS','compute','Managed Kubernetes service.','You already use Kubernetes.','托管的 Kubernetes 服务。','已经在使用 Kubernetes。'],
['Amazon ECR','compute','Managed registry to store, share and deploy container images.','Store Docker images.','用于存储、共享和部署容器镜像的托管镜像仓库。','存储 Docker 镜像。'],
['AWS Elastic Beanstalk','compute','Upload code; it handles capacity, load balancing, scaling and health monitoring (PaaS).','Deploy a web app without managing infrastructure.','上传代码即可，由它处理容量、负载均衡、伸缩和健康监控（PaaS）。','部署 Web 应用而不管理基础设施。'],
['Amazon Lightsail','compute','Simple virtual private servers, databases and networking at a predictable monthly price.','Simple website or small app with easy pricing.','以可预测的月费提供简单的虚拟专用服务器、数据库和网络。','定价简单的网站或小型应用。'],
['AWS Batch','compute','Plans, schedules and runs batch computing jobs at any scale.','Thousands of batch jobs.','以任意规模规划、调度和运行批量计算作业。','成千上万个批处理作业。'],
['AWS Outposts','compute','AWS-managed racks and servers that run AWS services in your own data centre.','Low latency to on-premises systems or local data processing.','在你自己的数据中心中运行 AWS 服务、由 AWS 管理的机架和服务器。','需要与本地系统低延迟通信或在本地处理数据。'],
/* storage */
['Amazon S3','storage','Object storage with 11 nines of durability, storage classes and lifecycle policies.','Backups, data lakes, static websites, media.','设计持久性为 11 个 9 的对象存储，提供存储类别和生命周期策略。','备份、数据湖、静态网站、媒体文件。'],
['Amazon S3 Glacier','storage','Low-cost archive storage classes: Instant Retrieval, Flexible Retrieval and Deep Archive.','Long-term archives and compliance retention.','低成本的归档存储类别：Instant Retrieval、Flexible Retrieval 和 Deep Archive。','长期归档和合规保留。'],
['Amazon EBS','storage','Persistent block storage volumes for EC2 instances in one AZ; snapshots for backup.','Boot volumes and databases on EC2.','供同一可用区内 EC2 实例使用的持久数据块存储卷；用快照备份。','EC2 上的启动卷和数据库。'],
['Amazon EFS','storage','Serverless, elastic NFS file system shared by many Linux instances across AZs.','Many instances need the same files at once.','可跨可用区供多台 Linux 实例共享的无服务器弹性 NFS 文件系统。','多台实例需要同时访问相同的文件。'],
['Amazon FSx','storage','Managed third-party file systems: Windows File Server, Lustre, NetApp ONTAP, OpenZFS.','Windows file shares or high-performance computing.','托管的第三方文件系统：Windows File Server、Lustre、NetApp ONTAP、OpenZFS。','Windows 文件共享或高性能计算。'],
['AWS Storage Gateway','storage','Hybrid storage giving on-premises apps access to cloud storage with a local cache (File, Volume, Tape Gateway).','On-premises apps using AWS storage.','混合存储，让本地应用通过本地缓存访问云存储（文件、卷、磁带网关）。','本地应用使用 AWS 存储。'],
['AWS Backup','storage','Centrally manages and automates backups across AWS services with backup plans.','One backup policy for EBS, RDS, DynamoDB, EFS and more.','通过备份计划集中管理并自动化各 AWS 服务的备份。','用一个备份策略覆盖 EBS、RDS、DynamoDB、EFS 等。'],
['AWS Elastic Disaster Recovery','storage','Continuously replicates servers to AWS for fast recovery.','Recover on-premises or cloud servers after a disaster.','持续把服务器复制到 AWS，以便快速恢复。','灾难后恢复本地或云中的服务器。'],
/* databases */
['Amazon RDS','db','Managed relational databases: MySQL, PostgreSQL, MariaDB, Oracle, SQL Server, Db2; Multi-AZ and read replicas.','Managed SQL database with less admin work.','托管的关系数据库：MySQL、PostgreSQL、MariaDB、Oracle、SQL Server、Db2；支持多可用区和只读副本。','运维工作更少的托管 SQL 数据库。'],
['Amazon Aurora','db','AWS-built MySQL- and PostgreSQL-compatible relational database with high performance and availability.','High-performance relational database.','AWS 自研、兼容 MySQL 和 PostgreSQL 的高性能、高可用关系数据库。','高性能关系数据库。'],
['Amazon DynamoDB','db','Serverless NoSQL key-value and document database with single-digit millisecond latency at any scale.','Massive scale, flexible schema, serverless.','无服务器的 NoSQL 键值和文档数据库，任何规模下都能提供个位数毫秒级延迟。','超大规模、灵活架构、无服务器。'],
['Amazon ElastiCache','db','In-memory caching with Valkey, Redis OSS or Memcached.','Cache queries, store sessions, reduce database load.','使用 Valkey、Redis OSS 或 Memcached 的内存缓存。','缓存查询、存储会话、减轻数据库负载。'],
['Amazon DocumentDB','db','Managed JSON document database compatible with MongoDB.','MongoDB workloads.','兼容 MongoDB 的托管 JSON 文档数据库。','MongoDB 工作负载。'],
['Amazon Neptune','db','Managed graph database for highly connected data.','Social networks, recommendations, fraud graphs.','用于高度关联数据的托管图数据库。','社交网络、推荐、欺诈关系图。'],
/* networking */
['Amazon VPC','net','Your logically isolated virtual network: subnets, route tables, gateways, security groups, network ACLs.','Isolate and control network traffic.','逻辑隔离的专属虚拟网络：子网、路由表、网关、安全组、网络 ACL。','隔离并控制网络流量。'],
['Amazon Route 53','net','Highly available DNS, domain registration, health checks and routing policies.','DNS, domain names, failover or latency routing.','高可用的 DNS、域名注册、健康检查和路由策略。','DNS、域名、故障转移或基于延迟的路由。'],
['Amazon CloudFront','net','Content delivery network that caches content at edge locations worldwide.','Speed up global delivery of websites and video.','在全球边缘站点缓存内容的内容分发网络。','加速网站和视频的全球分发。'],
['AWS Global Accelerator','net','Routes traffic over the AWS global network using static anycast IP addresses.','Improve global app availability and performance with fixed IPs.','使用静态任播 IP 地址，经由 AWS 全球网络路由流量。','用固定 IP 提升全球应用的可用性和性能。'],
['AWS Direct Connect','net','Dedicated private network connection from your premises to AWS.','Consistent performance, high bandwidth, no internet.','从你的场所到 AWS 的专用私有网络连接。','性能稳定、高带宽、不经过互联网。'],
['AWS VPN','net','Encrypted connections to AWS over the internet: Site-to-Site VPN and Client VPN.','Quick, encrypted connectivity.','通过互联网连接到 AWS 的加密连接：Site-to-Site VPN 和 Client VPN。','快速建立的加密连接。'],
['AWS Site-to-Site VPN','net','IPsec tunnels between your network and a VPC over the internet.','Connect an office or data centre quickly at low cost.','通过互联网在你的网络与 VPC 之间建立 IPsec 隧道。','快速、低成本地连接办公室或数据中心。'],
['AWS Client VPN','net','Managed VPN for individual users connecting to AWS or on-premises networks.','Remote employees connect securely.','供个人用户连接到 AWS 或本地网络的托管 VPN。','远程员工安全接入。'],
['AWS Transit Gateway','net','Central hub connecting many VPCs and on-premises networks.','Avoid a mesh of VPC peering connections.','连接多个 VPC 和本地网络的中心枢纽。','避免复杂的 VPC 对等连接网状结构。'],
['AWS PrivateLink','net','Private access to AWS and partner services through VPC endpoints, without the internet.','Keep service traffic off the public internet.','通过 VPC 终端节点私密访问 AWS 和合作伙伴服务，不经过互联网。','让服务流量不经过公共互联网。'],
['Amazon API Gateway','net','Create, publish, secure and monitor APIs at any scale.','Front door for serverless or HTTP APIs.','以任意规模创建、发布、保护和监控 API。','无服务器或 HTTP API 的前门。'],
/* security */
['AWS Identity and Access Management (IAM)','security','Users, groups, roles and policies that control access to AWS; MFA; free.','Who can do what in your account.','控制 AWS 访问的用户、组、角色和策略；支持 MFA；免费。','控制谁可以在账户中做什么。'],
['AWS IAM Identity Center','security','Single sign-on for the workforce across AWS accounts and applications.','Employees sign in once to many accounts.','为员工提供跨 AWS 账户和应用的单点登录。','员工登录一次即可访问多个账户。'],
['Amazon Cognito','security','Sign-up, sign-in and access control for web and mobile app users, including social login.','Customer identities for your app.','为 Web 和移动应用用户提供注册、登录和访问控制，包括社交登录。','应用的客户身份。'],
['AWS Directory Service','security','Managed Microsoft Active Directory in AWS, or connection to your on-premises AD.','Active Directory-aware workloads.','在 AWS 中运行的托管 Microsoft Active Directory，或连接到你的本地 AD。','依赖 Active Directory 的工作负载。'],
['AWS Resource Access Manager (AWS RAM)','security','Share AWS resources (such as subnets or Transit Gateways) across accounts.','Share resources within your organization.','在账户之间共享 AWS 资源（例如子网或 Transit Gateway）。','在组织内共享资源。'],
['AWS Artifact','security','On-demand AWS compliance reports (SOC, PCI, ISO) and agreements (BAA).','Auditors need AWS compliance documents.','按需获取 AWS 合规报告（SOC、PCI、ISO）和协议（BAA）。','审计人员需要 AWS 合规文档。'],
['AWS Key Management Service (AWS KMS)','security','Create and control encryption keys used across AWS services.','Encryption at rest with managed keys.','创建和控制在各 AWS 服务中使用的加密密钥。','使用托管密钥进行静态加密。'],
['AWS CloudHSM','security','Dedicated, single-tenant hardware security modules in your VPC.','Regulations require keys in your own dedicated HSM.','在你的 VPC 中提供专用的单租户硬件安全模块。','法规要求把密钥放在专用 HSM 中。'],
['AWS Certificate Manager (ACM)','security','Provisions and renews SSL/TLS certificates for AWS services.','HTTPS certificates for load balancers and CloudFront.','为 AWS 服务配置和续订 SSL/TLS 证书。','为负载均衡器和 CloudFront 提供 HTTPS 证书。'],
['AWS Secrets Manager','security','Stores and automatically rotates secrets such as database passwords and API keys.','Credentials that must rotate automatically.','存储并自动轮换数据库密码和 API 密钥等机密。','需要自动轮换的凭证。'],
['Amazon GuardDuty','security','Threat detection that analyses CloudTrail, VPC Flow Logs and DNS logs.','Detect malicious activity or compromised accounts.','分析 CloudTrail、VPC 流日志和 DNS 日志的威胁检测服务。','检测恶意活动或被盗用的账户。'],
['Amazon Inspector','security','Automated vulnerability scanning for EC2, container images and Lambda, plus network reachability.','Find software vulnerabilities (CVEs).','对 EC2、容器镜像和 Lambda 进行自动漏洞扫描，并检查网络可达性。','查找软件漏洞（CVE）。'],
['Amazon Macie','security','Discovers and protects sensitive data such as PII in Amazon S3.','Find personal data in S3 buckets.','发现并保护 Amazon S3 中的 PII 等敏感数据。','在 S3 存储桶中查找个人数据。'],
['Amazon Detective','security','Investigates security findings using graph analysis of log data.','Find the root cause of a finding.','利用日志数据的图分析调查安全发现。','查找安全发现的根本原因。'],
['AWS Security Hub','security','Aggregates security findings and runs best-practice checks across accounts.','One view of security posture.','汇总安全发现，并跨账户运行最佳实践检查。','统一查看安全态势。'],
['AWS Shield','security','DDoS protection: Standard is automatic and free; Advanced adds response team and cost protection.','Protect against DDoS attacks.','DDoS 防护：Standard 自动且免费；Advanced 增加响应团队和成本保护。','防护 DDoS 攻击。'],
['AWS WAF','security','Web application firewall filtering HTTP(S) requests: SQL injection, XSS, IP and geo rules, rate limits.','Block malicious web requests.','筛选 HTTP(S) 请求的 Web 应用防火墙：SQL 注入、XSS、IP 和地理规则、速率限制。','拦截恶意 Web 请求。'],
['AWS Firewall Manager','security','Centrally manages WAF, Shield Advanced, security groups and Network Firewall across accounts.','Consistent firewall rules across an organization.','跨账户集中管理 WAF、Shield Advanced、安全组和 Network Firewall。','在整个组织中保持一致的防火墙规则。'],
/* management and governance */
['AWS Management Console','mgmt','Web-based interface for accessing and managing AWS.','Explore, learn, one-time tasks.','访问和管理 AWS 的基于 Web 的界面。','探索、学习、一次性任务。'],
['AWS CloudFormation','mgmt','Infrastructure as code: provision resources from JSON/YAML templates as stacks.','Repeatable, version-controlled environments.','基础设施即代码：根据 JSON/YAML 模板以堆栈形式配置资源。','可重复、受版本控制的环境。'],
['AWS Auto Scaling','mgmt','Scales multiple resources (EC2, ECS, DynamoDB, Aurora) to follow demand.','Elasticity across several resource types.','让多种资源（EC2、ECS、DynamoDB、Aurora）随需求伸缩。','在多种资源类型上实现弹性。'],
['Amazon CloudWatch','mgmt','Metrics, logs, dashboards and alarms for resources and applications.','Monitor performance and trigger alarms.','针对资源和应用的指标、日志、仪表板和告警。','监控性能并触发告警。'],
['AWS CloudTrail','mgmt','Records API calls and account activity: who did what, when and from where.','Auditing and investigating changes.','记录 API 调用和账户活动：谁在何时何地做了什么。','审计和调查变更。'],
['AWS Config','mgmt','Records resource configurations and history, and evaluates compliance with rules.','How did this resource change? Is it compliant?','记录资源配置及其历史，并根据规则评估合规情况。','这个资源是怎样变化的？是否合规？'],
['AWS Organizations','mgmt','Manage multiple accounts centrally: OUs, service control policies and consolidated billing.','Multi-account governance and one bill.','集中管理多个账户：组织单位、服务控制策略和整合账单。','多账户治理和单一账单。'],
['AWS Control Tower','mgmt','Sets up and governs a secure multi-account environment (landing zone) with guardrails.','Quickly set up a well-governed multi-account setup.','通过防护措施设置并治理安全的多账户环境（着陆区）。','快速搭建治理良好的多账户环境。'],
['AWS Systems Manager','mgmt','Operate servers at scale: patching, Run Command, Session Manager, inventory, Parameter Store.','Patch and manage fleets of servers.','大规模运维服务器：打补丁、Run Command、Session Manager、资产清单、Parameter Store。','为大批服务器打补丁和进行管理。'],
['AWS Service Catalog','mgmt','Catalogue of approved, pre-configured products that teams can launch.','Self-service with governance.','由经批准、预先配置好的产品组成的目录，供团队启动。','受治理的自助服务。'],
['AWS Trusted Advisor','mgmt','Best-practice checks: cost optimization, performance, security, fault tolerance, service quotas.','Recommendations to improve your account.','最佳实践检查：成本优化、性能、安全性、容错能力、服务配额。','获取改进账户的建议。'],
['AWS Health Dashboard','mgmt','Service status and personalized events that affect your resources.','Is an AWS issue affecting me?','服务状态以及影响你资源的个性化事件。','AWS 的问题是否影响到我？'],
['AWS Compute Optimizer','mgmt','Machine learning recommendations to rightsize EC2, EBS, Lambda and more.','Find over-provisioned resources.','基于机器学习为 EC2、EBS、Lambda 等提供合理调整大小的建议。','找出配置过度的资源。'],
['AWS License Manager','mgmt','Manage and track software licences (such as BYOL) across AWS and on premises.','Stay compliant with licence terms.','跨 AWS 和本地管理和跟踪软件许可证（例如 BYOL）。','遵守许可证条款。'],
['Service Quotas','mgmt','View and request increases to service limits from one place.','Hit a limit and need more.','在一个地方查看服务限额并申请提高。','达到限额，需要更多。'],
['AWS Well-Architected Tool','mgmt','Review workloads against the six Well-Architected pillars and track improvements.','Architecture review against best practices.','对照六大 Well-Architected 支柱审查工作负载并跟踪改进。','按最佳实践进行架构审查。'],
/* finance and support */
['AWS Budgets','finance','Custom cost and usage budgets with alerts on actual or forecast spend, plus budget actions.','Alert me before I overspend.','自定义成本和用量预算，针对实际或预测支出发出告警，并支持预算操作。','在超支之前提醒我。'],
['AWS Cost Explorer','finance','Visualize and analyse past costs and usage, forecast, and get RI and Savings Plans recommendations.','Where did my money go?','可视化并分析过去的成本和用量、进行预测，并获取预留实例和节省计划建议。','我的钱花在哪里了？'],
['AWS Cost and Usage Reports','finance','The most detailed line-item billing data, delivered to Amazon S3.','Granular billing analysis with Athena or Quick Sight.','最详细的逐项账单数据，交付到 Amazon S3。','用 Athena 或 Quick Sight 进行细粒度的账单分析。'],
['AWS Marketplace','finance','Catalogue to find, buy and deploy third-party software, data and services, billed through AWS.','Buy pre-built third-party software.','查找、购买和部署第三方软件、数据和服务的目录，通过 AWS 计费。','购买现成的第三方软件。'],
['AWS Support','finance','Support plans: Basic, Business Support+, Enterprise Support (designated TAM) and Unified Operations.','Technical help and guidance from AWS.','Support 计划：Basic、Business Support+、Enterprise Support（指定 TAM）和 Unified Operations。','获得 AWS 的技术帮助和指导。'],
/* analytics */
['Amazon Athena','analytics','Serverless SQL queries directly on data in Amazon S3; pay per query.','Query S3 data with SQL, no servers.','无服务器，直接对 Amazon S3 中的数据运行 SQL 查询；按查询付费。','用 SQL 查询 S3 数据，无需服务器。'],
['Amazon Kinesis','analytics','Collect and process real-time streaming data.','Clickstreams, IoT telemetry, live logs.','收集和处理实时流数据。','点击流、物联网遥测、实时日志。'],
['AWS Glue','analytics','Serverless ETL and the Glue Data Catalog.','Prepare, transform and catalogue data.','无服务器 ETL 和 Glue 数据目录。','准备、转换和编目数据。'],
['Amazon Quick Sight','analytics','Business intelligence dashboards and visualizations.','Dashboards for business users.','商业智能仪表板和可视化。','面向业务用户的仪表板。'],
['Amazon Redshift','analytics','Petabyte-scale data warehouse for SQL analytics.','Complex analytical queries on large datasets.','用于 SQL 分析的 PB 级数据仓库。','对大型数据集进行复杂的分析查询。'],
['Amazon EMR','analytics','Managed big data frameworks such as Apache Spark and Hadoop.','Run Spark or Hadoop at scale.','托管的 Apache Spark、Hadoop 等大数据框架。','大规模运行 Spark 或 Hadoop。'],
['Amazon OpenSearch Service','analytics','Search, log analytics and observability.','Full-text search or log analysis.','搜索、日志分析和可观测性。','全文搜索或日志分析。'],
/* machine learning */
['Amazon SageMaker AI','ml','Build, train and deploy custom machine learning models.','Data scientists build their own models.','构建、训练和部署定制机器学习模型。','数据科学家构建自己的模型。'],
['Amazon Lex','ml','Conversational chatbots and voice bots.','Chatbot or voice assistant.','对话式聊天机器人和语音机器人。','聊天机器人或语音助手。'],
['Amazon Polly','ml','Text to lifelike speech.','Read text aloud.','把文本转换为逼真的语音。','朗读文本。'],
['Amazon Transcribe','ml','Speech to text.','Transcribe calls or create subtitles.','把语音转换为文字。','转录通话或生成字幕。'],
['Amazon Translate','ml','Neural machine translation between languages.','Translate content.','语言之间的神经机器翻译。','翻译内容。'],
['Amazon Comprehend','ml','Natural language processing: sentiment, entities, key phrases, PII.','Understand meaning in text.','自然语言处理：情感、实体、关键短语、PII。','理解文本的含义。'],
['Amazon Rekognition','ml','Image and video analysis: objects, faces, text, unsafe content.','Analyse images or video.','图像和视频分析：物体、人脸、文字、不安全内容。','分析图像或视频。'],
['Amazon Textract','ml','Extracts text, forms and tables from scanned documents.','Read data from scanned forms.','从扫描文档中提取文字、表单和表格。','从扫描表单中读取数据。'],
['Amazon Q','ml','Generative AI-powered assistant, such as Amazon Q Developer for building on AWS. Amazon Q Business is closed to new customers (successor: Amazon Quick).','Generative AI assistant for developers on AWS.','由生成式 AI 驱动的助手，例如用于在 AWS 上构建的 Amazon Q Developer。Amazon Q Business 已不再向新客户开放（后继产品：Amazon Quick）。','面向 AWS 开发人员的生成式 AI 助手。'],
/* migration */
['AWS Application Discovery Service','migration','Discovers on-premises servers, configuration and dependencies.','Plan which servers move together.','发现本地服务器、配置和依赖关系。','规划哪些服务器要一起迁移。'],
['Migration Evaluator','migration','Builds a data-driven business case with projected AWS costs.','Justify the migration with numbers.','构建基于数据、包含预计 AWS 成本的业务案例。','用数据论证迁移的合理性。'],
['AWS Migration Hub','migration','Central place to discover, plan and track migrations.','Track migration progress in one place.','集中发现、规划和跟踪迁移的位置。','在一个地方跟踪迁移进度。'],
['AWS Application Migration Service','migration','Automated lift-and-shift: replicates servers and launches them on EC2.','Rehost servers quickly.','自动化直接迁移：复制服务器并在 EC2 上启动。','快速重新托管服务器。'],
['AWS Database Migration Service (AWS DMS)','migration','Migrates databases with minimal downtime and continuous replication.','Move a database while it keeps running.','以最短停机时间迁移数据库，并持续复制变更。','在数据库保持运行的同时迁移它。'],
['AWS Schema Conversion Tool (AWS SCT)','migration','Converts database schema and code between engines.','Different source and target engines.','在不同引擎之间转换数据库架构和代码。','源引擎与目标引擎不同。'],
/* apps, integration, dev tools, EUC, IoT */
['Amazon SQS','apps','Fully managed message queue that decouples components.','Buffer work so nothing is lost.','实现组件解耦的完全托管消息队列。','缓冲任务，避免丢失。'],
['Amazon SNS','apps','Publish/subscribe messaging: push to email, SMS, mobile, Lambda, SQS.','Send notifications to many subscribers.','发布/订阅消息：推送到电子邮件、短信、移动设备、Lambda、SQS。','向多个订阅方发送通知。'],
['Amazon EventBridge','apps','Serverless event bus routing events with rules, plus a scheduler.','Event-driven architecture or scheduled tasks.','用规则路由事件的无服务器事件总线，并提供调度器。','事件驱动架构或计划任务。'],
['AWS Step Functions','apps','Visual workflows that orchestrate services and Lambda functions.','Coordinate multi-step processes.','编排服务和 Lambda 函数的可视化工作流。','协调多步骤流程。'],
['Amazon Connect','apps','Cloud contact centre with phone and chat.','Set up a contact centre quickly.','提供电话和聊天的云联络中心。','快速搭建联络中心。'],
['Amazon Simple Email Service (Amazon SES)','apps','Sends transactional, marketing and notification email at scale.','Application email.','大规模发送事务性、营销和通知邮件。','应用发送的电子邮件。'],
['AWS CLI','apps','Command line tool to manage AWS services and write scripts.','Automate tasks from a terminal.','管理 AWS 服务和编写脚本的命令行工具。','从终端自动化任务。'],
['AWS CodeBuild','apps','Managed build service: compile, test and package code.','Build and test without build servers.','托管构建服务：编译、测试和打包代码。','无需构建服务器即可构建和测试。'],
['AWS CodePipeline','apps','Continuous delivery that automates build, test and deploy stages.','Automated release pipeline.','自动执行构建、测试和部署阶段的持续交付服务。','自动化发布管道。'],
['AWS X-Ray','apps','Traces requests through distributed applications.','Find bottlenecks in microservices.','跟踪请求在分布式应用中的路径。','找出微服务中的瓶颈。'],
['Amazon WorkSpaces','apps','Managed virtual desktops (Windows or Linux).','Desktops for remote employees.','托管的虚拟桌面（Windows 或 Linux）。','为远程员工提供桌面。'],
['Amazon AppStream 2.0','apps','Streams desktop applications to a browser. Now named Amazon WorkSpaces Applications.','Run one app on any device.','把桌面应用流式传输到浏览器。现名 Amazon WorkSpaces Applications。','在任何设备上运行某个应用。'],
['Amazon WorkSpaces Secure Browser','apps','Secure browser access to internal websites and SaaS apps. Closing to new customers on 29 October 2026.','Contractors access internal web apps safely.','安全地通过浏览器访问内部网站和 SaaS 应用。2026 年 10 月 29 日起不再向新客户开放。','承包商安全访问内部 Web 应用。'],
['AWS Amplify','apps','Build, deploy and host full-stack web and mobile apps.','Quickly ship a web or mobile app.','构建、部署和托管全栈 Web 和移动应用。','快速发布 Web 或移动应用。'],
['AWS IoT Core','apps','Securely connects IoT devices and routes their messages to AWS services.','Connect and manage IoT devices.','安全地连接物联网设备，并把它们的消息路由到 AWS 服务。','连接和管理物联网设备。']
];
S.forEach(function(s){CLF.svc.push({n:s[0],c:s[1],en:{w:s[2],p:s[3]},zh:{w:s[4],p:s[5]}});});

/* ---------------- Flashcards: [domain, Q en, A en, Q zh, A zh] ---------------- */
var C = [
['d1','Name the six advantages of cloud computing.','Trade fixed for variable expense; benefit from economies of scale; stop guessing capacity; increase speed and agility; stop spending on data centres; go global in minutes.','云计算的六大优势是什么？','用可变成本取代固定成本；受益于规模经济；无需再猜测容量；提高速度和敏捷性；不再为数据中心花钱；几分钟内实现全球部署。'],
['d1','Elasticity vs scalability?','Scalability: the ability to grow to handle more load. Elasticity: capacity automatically follows demand up and down.','弹性与可扩展性的区别？','可扩展性：为应对更多负载而增长的能力；弹性：容量自动随需求上下变化。'],
['d1','High availability vs fault tolerance?','High availability: minimal downtime (e.g. multiple AZs). Fault tolerance: keeps running with no interruption when a component fails.','高可用性与容错的区别？','高可用性：停机时间最少（例如多可用区）；容错：组件出故障时仍不间断地运行。'],
['d1','What does agility mean in the cloud?','Resources in minutes and cheap experiments, so teams innovate faster.','云中的敏捷性是什么意思？','几分钟即可获得资源，试验成本低，团队可以更快创新。'],
['d1','Name the six Well-Architected pillars.','Operational excellence, security, reliability, performance efficiency, cost optimization, sustainability.','Well-Architected 的六大支柱是什么？','卓越运营、安全性、可靠性、性能效率、成本优化、可持续性。'],
['d1','"Perform operations as code" belongs to which pillar?','Operational excellence.','“将运维操作代码化”属于哪个支柱？','卓越运营。'],
['d1','"Automatically recover from failure" belongs to which pillar?','Reliability.','“自动从故障中恢复”属于哪个支柱？','可靠性。'],
['d1','"Use serverless architectures" and "go global in minutes" belong to which pillar?','Performance efficiency.','“使用无服务器架构”和“几分钟内实现全球部署”属于哪个支柱？','性能效率。'],
['d1','"Adopt a consumption model" belongs to which pillar?','Cost optimization.','“采用按使用量付费的模式”属于哪个支柱？','成本优化。'],
['d1','"Implement a strong identity foundation" belongs to which pillar?','Security.','“建立坚实的身份基础”属于哪个支柱？','安全性。'],
['d1','Which pillar is about minimizing environmental impact?','Sustainability.','哪个支柱关注最大限度地减少环境影响？','可持续性。'],
['d1','Name the six AWS CAF perspectives.','Business, People, Governance (business capabilities); Platform, Security, Operations (technical capabilities).','AWS CAF 的六个视角是什么？','业务、人员、治理（业务能力）；平台、安全性、运营（技术能力）。'],
['d1','Name the four AWS CAF business outcomes.','Reduced business risk; improved ESG performance; increased revenue; increased operational efficiency.','AWS CAF 的四项业务成果是什么？','降低业务风险；提升 ESG 绩效；增加收入；提高运营效率。'],
['d1','Rehost vs replatform vs refactor?','Rehost: move unchanged. Replatform: small optimizations (e.g. move to RDS). Refactor: re-architect to cloud native.','重新托管、更换平台与重构的区别？','重新托管：原样迁移；更换平台：做少量优化（例如改用 RDS）；重构：重新架构为云原生。'],
['d1','Repurchase, retain, retire, relocate?','Repurchase: switch to SaaS. Retain: keep for now. Retire: turn off. Relocate: move VMware to VMware Cloud on AWS.','重新购买、保留、停用、迁移位置分别是什么？','重新购买：改用 SaaS；保留：暂时保留；停用：关闭；迁移位置：把 VMware 迁移到 VMware Cloud on AWS。'],
['d1','Which service performs lift-and-shift server migration?','AWS Application Migration Service.','哪项服务执行服务器的直接迁移？','AWS Application Migration Service。'],
['d1','Which service builds a migration business case?','Migration Evaluator.','哪项服务构建迁移业务案例？','Migration Evaluator。'],
['d1','Which service discovers on-premises servers and dependencies?','AWS Application Discovery Service.','哪项服务发现本地服务器及其依赖关系？','AWS Application Discovery Service。'],
['d1','Fixed vs variable cost?','Fixed (CapEx): paid up front regardless of use. Variable (OpEx): pay for what you use.','固定成本与可变成本的区别？','固定成本（资本支出）：无论是否使用都要预先支付；可变成本（运营支出）：按使用量付费。'],
['d1','BYOL vs license included?','BYOL: use licences you own (may need Dedicated Hosts). License included: licence cost built into the hourly price.','自带许可证与随附许可证的区别？','自带许可证：使用你已拥有的许可证（可能需要专属主机）；随附许可证：许可证费用已包含在小时价格中。'],
['d1','What is rightsizing?','Matching instance types and sizes to actual workload needs to avoid paying for unused capacity.','什么是合理调整大小？','让实例类型和大小与工作负载的实际需求相匹配，避免为未使用的容量付费。'],
['d1','What goes into on-premises TCO?','Hardware, facilities, power, cooling, network, licences, IT labour and refresh cycles.','本地部署的 TCO 包括什么？','硬件、设施、电力、制冷、网络、许可证、IT 人工以及硬件更新周期。'],
['d1','Which program funds and guides migrations?','AWS Migration Acceleration Program (MAP).','哪个计划为迁移提供资金和指导？','AWS 迁移加速计划（MAP）。'],
['d2','Shared responsibility in one line?','AWS: security OF the cloud. Customer: security IN the cloud.','用一句话概括责任共担？','AWS 负责云本身的安全；客户负责云中的安全。'],
['d2','Who patches the guest OS on EC2? On RDS?','EC2: the customer. RDS: AWS.','谁为 EC2 上的客户机操作系统打补丁？RDS 呢？','EC2：客户；RDS：AWS。'],
['d2','Name the three shared controls.','Patch management, configuration management, awareness and training.','三项共享控制是什么？','补丁管理、配置管理、意识和培训。'],
['d2','What always stays the customer’s responsibility?','Their data, its classification and who can access it (IAM).','什么始终是客户的责任？','他们的数据、数据分类以及谁可以访问数据（IAM）。'],
['d2','Where do you download SOC and PCI reports?','AWS Artifact.','在哪里下载 SOC 和 PCI 报告？','AWS Artifact。'],
['d2','CloudTrail vs CloudWatch vs Config?','CloudTrail: who did what (API calls). CloudWatch: metrics, logs, alarms. Config: resource configuration history and compliance.','CloudTrail、CloudWatch 与 Config 的区别？','CloudTrail：谁做了什么（API 调用）；CloudWatch：指标、日志、告警；Config：资源配置历史和合规情况。'],
['d2','GuardDuty vs Inspector?','GuardDuty: threat detection from logs. Inspector: vulnerability scanning of EC2, images and Lambda.','GuardDuty 与 Inspector 的区别？','GuardDuty：从日志中检测威胁；Inspector：扫描 EC2、镜像和 Lambda 中的漏洞。'],
['d2','Which service finds PII in S3?','Amazon Macie.','哪项服务在 S3 中查找 PII？','Amazon Macie。'],
['d2','Which service investigates the root cause of findings?','Amazon Detective.','哪项服务调查安全发现的根本原因？','Amazon Detective。'],
['d2','Which service aggregates security findings across accounts?','AWS Security Hub.','哪项服务跨账户汇总安全发现？','AWS Security Hub。'],
['d2','KMS vs CloudHSM?','KMS: managed, multi-tenant key service. CloudHSM: dedicated, single-tenant HSM you control.','KMS 与 CloudHSM 的区别？','KMS：托管的多租户密钥服务；CloudHSM：由你控制的专用单租户 HSM。'],
['d2','What does ACM provide?','Free public SSL/TLS certificates (with integrated services) and automatic renewal.','ACM 提供什么？','免费的公有 SSL/TLS 证书（与集成服务一起使用时）和自动续订。'],
['d2','Encryption in transit vs at rest?','In transit: data moving over a network (TLS, VPN). At rest: stored data (S3, EBS, RDS with KMS).','传输中加密与静态加密的区别？','传输中：网络中传输的数据（TLS、VPN）；静态：存储的数据（使用 KMS 的 S3、EBS、RDS）。'],
['d2','Shield Standard vs Shield Advanced?','Standard: automatic, free, common DDoS. Advanced: paid, Shield Response Team, cost protection.','Shield Standard 与 Shield Advanced 的区别？','Standard：自动、免费，防护常见 DDoS；Advanced：付费，提供 Shield 响应团队和成本保护。'],
['d2','What does AWS WAF block?','Malicious HTTP(S) requests: SQL injection, cross-site scripting, bad IPs, countries, request floods.','AWS WAF 拦截什么？','恶意的 HTTP(S) 请求：SQL 注入、跨站脚本、恶意 IP、特定国家、请求洪水。'],
['d2','Which service manages firewall rules across all accounts?','AWS Firewall Manager.','哪项服务跨所有账户管理防火墙规则？','AWS Firewall Manager。'],
['d2','Root user best practices?','Strong password, MFA, no access keys, lock away credentials, use only for root-only tasks.','根用户的最佳实践？','强密码、MFA、不创建访问密钥、妥善保管凭证、只用于必须由根用户执行的任务。'],
['d2','Name three root-only tasks.','Change root email or password (standalone account), close the account, restore IAM user permissions. Also: S3 MFA delete, GovCloud signup.','举出三项只有根用户能执行的任务。','更改根用户电子邮件或密码（独立账户）、关闭账户、恢复 IAM 用户权限。还有：S3 MFA 删除、注册 GovCloud。'],
['d2','What is the principle of least privilege?','Grant only the permissions needed to do the job.','什么是最低权限原则？','只授予完成工作所需的权限。'],
['d2','IAM user vs group vs role?','User: a person or app with long-term credentials. Group: a set of users sharing policies. Role: assumed for temporary credentials.','IAM 用户、组与角色的区别？','用户：拥有长期凭证的人员或应用；组：共享策略的一组用户；角色：通过代入获取临时凭证。'],
['d2','Best way to give an EC2 app access to S3?','Attach an IAM role to the instance (never hard-code access keys).','让 EC2 上的应用访问 S3 的最佳方式？','为实例附加 IAM 角色（切勿硬编码访问密钥）。'],
['d2','Secrets Manager vs Parameter Store?','Secrets Manager: automatic rotation, per-secret price. Parameter Store: configuration and secrets, standard tier free, no built-in rotation.','Secrets Manager 与 Parameter Store 的区别？','Secrets Manager：自动轮换，按机密收费；Parameter Store：存储配置和机密，标准层免费，无内置轮换。'],
['d2','IAM Identity Center vs Cognito?','Identity Center: workforce SSO to AWS accounts. Cognito: customer sign-in for your apps.','IAM Identity Center 与 Cognito 的区别？','Identity Center：员工单点登录 AWS 账户；Cognito：你的应用的客户登录。'],
['d2','What is federation?','Users authenticated by an external identity provider (SAML or OIDC) access AWS through roles.','什么是联合？','由外部身份提供商（SAML 或 OIDC）验证的用户通过角色访问 AWS。'],
['d2','IAM credential report vs access advisor?','Credential report: every user’s password, key and MFA status. Access advisor: services used and when.','IAM 凭证报告与访问顾问的区别？','凭证报告：每个用户的密码、密钥和 MFA 状态；访问顾问：使用过哪些服务以及使用时间。'],
['d2','What does a service control policy (SCP) do?','Sets the maximum permissions for accounts in an organization or OU, even for administrators.','服务控制策略（SCP）的作用是什么？','为组织或 OU 中的账户设置最大权限，即使是管理员也受限制。'],
['d2','Where do you find security bulletins and guidance?','AWS Security Center, AWS Security Blog, Knowledge Center, re:Post.','在哪里查找安全公告和指导？','AWS 安全中心、AWS 安全博客、知识中心、re:Post。'],
['d2','Which service continuously checks your resources against compliance rules?','AWS Config, with rules and conformance packs.','哪项服务持续根据合规规则检查你的资源？','AWS Config，借助规则和一致性包。'],
['d3','Console vs CLI vs SDK vs IaC?','Console: visual, one-off. CLI: scripts. SDK: application code. IaC (CloudFormation, CDK): repeatable environments.','控制台、CLI、SDK 与 IaC 的区别？','控制台：可视化、一次性任务；CLI：脚本；SDK：应用代码；IaC（CloudFormation、CDK）：可重复的环境。'],
['d3','Cloud vs hybrid vs on-premises deployment?','Cloud: all in AWS. Hybrid: connects cloud and on-premises. On-premises: your data centre (e.g. AWS Outposts).','云、混合与本地部署的区别？','云：全部在 AWS 中；混合：连接云和本地；本地部署：你的数据中心（例如 AWS Outposts）。'],
['d3','Region vs Availability Zone vs edge location?','Region: geographic area with 3+ AZs. AZ: one or more isolated data centres. Edge location: caching and DNS near users.','区域、可用区与边缘站点的区别？','区域：包含 3 个以上可用区的地理区域；可用区：一个或多个隔离的数据中心；边缘站点：在用户附近提供缓存和 DNS。'],
['d3','Four factors for choosing a Region?','Compliance, proximity to customers, available services, pricing.','选择区域的四个因素？','合规、与客户的距离、可用的服务、价格。'],
['d3','Multi-AZ vs multi-Region?','Multi-AZ: survive a data centre failure (high availability). Multi-Region: disaster recovery, global latency, data sovereignty.','多可用区与多区域的区别？','多可用区：承受数据中心故障（高可用性）；多区域：灾难恢复、全球低延迟、数据主权。'],
['d3','Local Zones vs Wavelength vs Outposts?','Local Zones: AWS in big cities. Wavelength: inside 5G networks. Outposts: in your own data centre.','本地扩展区、Wavelength 与 Outposts 的区别？','本地扩展区：AWS 部署在大城市；Wavelength：部署在 5G 网络中；Outposts：部署在你自己的数据中心。'],
['d3','EC2 families by workload?','General purpose: balanced. Compute optimized: CPU-heavy. Memory optimized: in-memory data. Storage optimized: local I/O. Accelerated: GPUs.','按工作负载划分的 EC2 系列？','通用型：均衡；计算优化型：CPU 密集；内存优化型：内存数据；存储优化型：本地 I/O；加速计算型：GPU。'],
['d3','ECS vs EKS vs Fargate?','ECS: AWS container orchestration. EKS: managed Kubernetes. Fargate: serverless compute for both.','ECS、EKS 与 Fargate 的区别？','ECS：AWS 容器编排；EKS：托管的 Kubernetes；Fargate：两者都可用的无服务器计算。'],
['d3','Lambda key facts?','Event-driven, serverless, pay per request and duration, up to 15 minutes per run.','Lambda 的关键事实？','事件驱动、无服务器、按请求次数和时长付费、每次最长运行 15 分钟。'],
['d3','Auto scaling vs load balancing?','Auto scaling changes how many instances run. A load balancer spreads traffic across them and checks health.','弹性伸缩与负载均衡的区别？','弹性伸缩改变运行实例的数量；负载均衡器在实例之间分配流量并检查健康状况。'],
['d3','ALB vs NLB vs GWLB?','ALB: layer 7 HTTP routing. NLB: layer 4, extreme performance, static IP. GWLB: third-party appliances.','ALB、NLB 与 GWLB 的区别？','ALB：第 7 层 HTTP 路由；NLB：第 4 层、极致性能、静态 IP；GWLB：第三方设备。'],
['d3','RDS vs Aurora vs DynamoDB?','RDS: managed relational engines. Aurora: AWS-built high-performance relational. DynamoDB: serverless NoSQL key-value.','RDS、Aurora 与 DynamoDB 的区别？','RDS：托管的关系引擎；Aurora：AWS 自研的高性能关系数据库；DynamoDB：无服务器 NoSQL 键值数据库。'],
['d3','Which database is in-memory?','Amazon ElastiCache (Valkey, Redis OSS, Memcached).','哪种数据库基于内存？','Amazon ElastiCache（Valkey、Redis OSS、Memcached）。'],
['d3','DocumentDB vs Neptune?','DocumentDB: MongoDB-compatible documents. Neptune: graph (connected data).','DocumentDB 与 Neptune 的区别？','DocumentDB：兼容 MongoDB 的文档数据库；Neptune：图数据库（关联数据）。'],
['d3','DMS vs SCT?','DMS moves data with minimal downtime. SCT converts schemas between different engines.','DMS 与 SCT 的区别？','DMS 以最短停机时间迁移数据；SCT 在不同引擎之间转换架构。'],
['d3','Security group vs network ACL?','Security group: instance level, stateful, allow only. NACL: subnet level, stateless, allow and deny.','安全组与网络 ACL 的区别？','安全组：实例级别、有状态、只有允许规则；网络 ACL：子网级别、无状态、有允许和拒绝规则。'],
['d3','Internet gateway vs NAT gateway?','Internet gateway: two-way internet for public subnets. NAT gateway: outbound-only internet for private subnets.','互联网网关与 NAT 网关的区别？','互联网网关：为公有子网提供双向互联网访问；NAT 网关：为私有子网提供仅出站的互联网访问。'],
['d3','VPN vs Direct Connect?','VPN: encrypted over the internet, quick to set up. Direct Connect: dedicated private line, consistent performance.','VPN 与 Direct Connect 的区别？','VPN：经互联网加密、建立快速；Direct Connect：专用私有线路、性能稳定。'],
['d3','CloudFront vs Global Accelerator?','CloudFront caches content at the edge. Global Accelerator routes traffic over the AWS network with static IPs.','CloudFront 与 Global Accelerator 的区别？','CloudFront 在边缘缓存内容；Global Accelerator 使用静态 IP，经由 AWS 网络路由流量。'],
['d3','What does Route 53 do?','DNS, domain registration, health checks and routing policies (latency, failover, weighted, geolocation).','Route 53 的作用是什么？','DNS、域名注册、健康检查和路由策略（延迟、故障转移、加权、地理位置）。'],
['d3','Object vs block vs file storage?','Object: S3. Block: EBS and instance store. File: EFS (Linux) and FSx (Windows, Lustre and more).','对象、数据块与文件存储的区别？','对象：S3；数据块：EBS 和实例存储；文件：EFS（Linux）和 FSx（Windows、Lustre 等）。'],
['d3','EBS vs instance store?','EBS: persistent, survives stop. Instance store: very fast but temporary; lost on stop or terminate.','EBS 与实例存储的区别？','EBS：持久，实例停止后仍保留；实例存储：速度极快但为临时性，实例停止或终止时丢失。'],
['d3','Which S3 class for unknown access patterns?','S3 Intelligent-Tiering.','访问模式未知时用哪种 S3 存储类别？','S3 Intelligent-Tiering。'],
['d3','Cheapest S3 class for long-term archives?','S3 Glacier Deep Archive (retrieval within hours).','用于长期归档最便宜的 S3 存储类别？','S3 Glacier Deep Archive（数小时内取回）。'],
['d3','What do S3 Lifecycle policies do?','Move objects to cheaper classes and delete them on a schedule.','S3 生命周期策略的作用是什么？','按计划把对象转移到更便宜的存储类别并删除它们。'],
['d3','Storage Gateway vs AWS Backup?','Storage Gateway: on-premises apps use cloud storage with a local cache. Backup: central backup policies across AWS services.','Storage Gateway 与 AWS Backup 的区别？','Storage Gateway：本地应用通过本地缓存使用云存储；Backup：跨 AWS 服务的集中备份策略。'],
['d3','Transcribe vs Polly vs Translate?','Transcribe: speech → text. Polly: text → speech. Translate: language → language.','Transcribe、Polly 与 Translate 的区别？','Transcribe：语音 → 文字；Polly：文字 → 语音；Translate：语言 → 语言。'],
['d3','Comprehend vs Textract vs Rekognition?','Comprehend: meaning of text. Textract: text and tables from documents. Rekognition: images and video.','Comprehend、Textract 与 Rekognition 的区别？','Comprehend：文本含义；Textract：从文档中提取文字和表格；Rekognition：图像和视频。'],
['d3','Lex vs SageMaker AI?','Lex: build chatbots. SageMaker AI: build, train and deploy your own models.','Lex 与 SageMaker AI 的区别？','Lex：构建聊天机器人；SageMaker AI：构建、训练和部署你自己的模型。'],
['d3','Athena vs Redshift vs EMR?','Athena: serverless SQL on S3. Redshift: data warehouse. EMR: Spark and Hadoop clusters.','Athena、Redshift 与 EMR 的区别？','Athena：对 S3 运行无服务器 SQL；Redshift：数据仓库；EMR：Spark 和 Hadoop 集群。'],
['d3','Kinesis vs Glue vs Quick Sight?','Kinesis: real-time streams. Glue: ETL and data catalogue. Quick Sight: BI dashboards.','Kinesis、Glue 与 Quick Sight 的区别？','Kinesis：实时流；Glue：ETL 和数据目录；Quick Sight：商业智能仪表板。'],
['d3','SQS vs SNS vs EventBridge?','SQS: queue (pull, decouple). SNS: pub/sub push notifications. EventBridge: event bus with rules and schedules.','SQS、SNS 与 EventBridge 的区别？','SQS：队列（拉取、解耦）；SNS：发布/订阅推送通知；EventBridge：带规则和调度的事件总线。'],
['d3','CodeBuild vs CodePipeline vs X-Ray?','CodeBuild: compile and test. CodePipeline: automate the release. X-Ray: trace requests.','CodeBuild、CodePipeline 与 X-Ray 的区别？','CodeBuild：编译和测试；CodePipeline：自动化发布；X-Ray：跟踪请求。'],
['d3','WorkSpaces vs AppStream 2.0 vs Secure Browser?','WorkSpaces: full desktops. AppStream 2.0 (now WorkSpaces Applications): single apps streamed. Secure Browser: internal websites only.','WorkSpaces、AppStream 2.0 与 Secure Browser 的区别？','WorkSpaces：完整桌面；AppStream 2.0（现名 WorkSpaces Applications）：流式传输单个应用；Secure Browser：只访问内部网站。'],
['d3','Connect vs SES?','Connect: cloud contact centre. SES: application email.','Connect 与 SES 的区别？','Connect：云联络中心；SES：应用电子邮件。'],
['d3','Amplify vs IoT Core?','Amplify: web and mobile apps. IoT Core: connect IoT devices.','Amplify 与 IoT Core 的区别？','Amplify：Web 和移动应用；IoT Core：连接物联网设备。'],
['d4','On-Demand vs Spot vs Reserved?','On-Demand: no commitment, no interruption. Spot: up to 90% off, can be interrupted. Reserved: 1–3 year commitment, up to 72% off.','按需型、竞价型与预留实例的区别？','按需型：无需承诺、不会中断；竞价型：最高节省 90%，可能被中断；预留：1–3 年承诺，最高节省 72%。'],
['d4','What makes Compute Savings Plans flexible?','A $/hour commitment that applies across EC2 families, sizes, Regions, OS, plus Fargate and Lambda.','Compute Savings Plans 的灵活性体现在哪里？','按“美元/小时”承诺，适用于不同 EC2 系列、大小、区域、操作系统，以及 Fargate 和 Lambda。'],
['d4','Dedicated Hosts vs Dedicated Instances?','Hosts: whole server, socket and core visibility (BYOL). Instances: dedicated hardware without host control.','专属主机与专用实例的区别？','专属主机：整台服务器，可见插槽和内核（BYOL）；专用实例：专用硬件，但无法控制主机。'],
['d4','What do Capacity Reservations give you?','Guaranteed capacity in one AZ, any duration, On-Demand price, no commitment.','容量预留能为你提供什么？','在一个可用区中保证容量，任意时长，按需价格，无需承诺。'],
['d4','Standard vs Convertible RIs?','Standard: biggest discount, can be sold. Convertible: smaller discount, can be exchanged.','标准与可转换预留实例的区别？','标准：折扣最大，可以出售；可转换：折扣较小，可以兑换。'],
['d4','Which data transfer is free?','Data into AWS from the internet.','哪种数据传输免费？','从互联网传入 AWS 的数据。'],
['d4','Budgets vs Cost Explorer vs Pricing Calculator?','Budgets: alerts (future). Cost Explorer: analysis (past). Pricing Calculator: estimates (before building).','Budgets、Cost Explorer 与定价计算器的区别？','Budgets：告警（未来）；Cost Explorer：分析（过去）；定价计算器：估算（构建之前）。'],
['d4','What is the most detailed billing data?','AWS Cost and Usage Report, delivered to S3.','最详细的账单数据是什么？','AWS 成本和使用情况报告，交付到 S3。'],
['d4','Benefits of consolidated billing?','One bill, combined usage for volume tiers, shared RI and Savings Plans discounts, no extra cost.','整合账单的益处？','一张账单、合并用量以享受批量阶梯价格、共享预留实例和节省计划折扣、不额外收费。'],
['d4','How do cost allocation tags work?','Tag resources, then activate the tags in Billing so they appear in Cost Explorer and the CUR.','成本分配标签如何使用？','为资源打标签，然后在账单中激活这些标签，使其出现在 Cost Explorer 和 CUR 中。'],
['d4','Which support plan includes a designated TAM?','Enterprise Support (and Unified Operations above it).','哪个 Support 计划包含指定的 TAM？','Enterprise Support（以及更高级别的 Unified Operations）。'],
['d4','What does Basic Support include?','Account and billing help, docs, re:Post, Health Dashboard, core Trusted Advisor checks. No technical cases.','Basic Support 包含什么？','账户和账单帮助、文档、re:Post、Health Dashboard、Trusted Advisor 核心检查。不能提交技术支持案例。'],
['d4','Trusted Advisor categories?','Cost optimization, performance, security, fault tolerance, service quotas (plus operational excellence).','Trusted Advisor 的类别？','成本优化、性能、安全性、容错能力、服务配额（另有卓越运营）。'],
['d4','Who handles abuse reports such as spam from AWS IPs?','The AWS Trust & Safety team.','谁处理来自 AWS IP 的垃圾邮件等滥用举报？','AWS 信任与安全团队。'],
['d4','ISV vs system integrator?','ISV: builds software that runs on AWS. SI: helps customers design, migrate and run workloads.','独立软件供应商与系统集成商的区别？','独立软件供应商：开发运行在 AWS 上的软件；系统集成商：帮助客户设计、迁移和运行工作负载。'],
['d4','Knowledge Center vs re:Post vs Prescriptive Guidance?','Knowledge Center: answers to common support questions. re:Post: community Q&A. Prescriptive Guidance: proven migration and modernization patterns.','知识中心、re:Post 与规范指引的区别？','知识中心：常见支持问题的解答；re:Post：社区问答；规范指引：经过验证的迁移和现代化模式。']
];
C.forEach(function(c){CLF.cards.push({d:c[0],en:{q:c[1],a:c[2]},zh:{q:c[3],a:c[4]}});});

/* ---------------- Glossary: [term en, definition en, term zh, definition zh] ---------------- */
var G = [
['Agility','Being able to try things quickly and cheaply because resources are available in minutes.','敏捷性','由于几分钟即可获得资源，可以快速、低成本地进行尝试。'],
['Elasticity','Acquiring resources when you need them and releasing them when you do not.','弹性','在需要时获取资源，在不需要时释放资源。'],
['High availability','Designing a system to keep running with minimal downtime, for example across multiple AZs.','高可用性','把系统设计为以最少的停机时间持续运行，例如跨多个可用区部署。'],
['Fault tolerance','Continuing to operate without interruption when a component fails.','容错','在组件出故障时仍能不间断地运行。'],
['Economies of scale','Lower prices made possible by AWS’s very large aggregate usage.','规模经济','由于 AWS 的总体用量巨大而得以实现的更低价格。'],
['Capital expenditure (CapEx)','Up-front spending on physical assets such as servers and data centres.','资本支出（CapEx）','在服务器和数据中心等实物资产上的预先支出。'],
['Operational expenditure (OpEx)','Ongoing spending on services you use, such as pay-as-you-go cloud resources.','运营支出（OpEx）','在所使用服务上的持续支出，例如按需付费的云资源。'],
['Total cost of ownership (TCO)','All direct and indirect costs of running infrastructure over time.','总拥有成本（TCO）','长期运行基础设施的所有直接和间接成本。'],
['Rightsizing','Matching resource types and sizes to actual workload needs.','合理调整大小','让资源类型和大小与工作负载的实际需求相匹配。'],
['BYOL','Bring your own license: using software licences you already own on AWS.','自带许可证（BYOL）','在 AWS 上使用你已经拥有的软件许可证。'],
['AWS Well-Architected Framework','Best practices organized into six pillars for designing and running workloads.','AWS Well-Architected 框架','按六大支柱组织的、用于设计和运行工作负载的最佳实践。'],
['AWS Cloud Adoption Framework (AWS CAF)','Guidance for cloud adoption organized into six perspectives.','AWS 云采用框架（AWS CAF）','按六个视角组织的云采用指导。'],
['7 Rs','Migration strategies: rehost, replatform, refactor, repurchase, retain, retire, relocate.','7 R','迁移策略：重新托管、更换平台、重构、重新购买、保留、停用、迁移位置。'],
['Shared responsibility model','AWS secures the cloud; customers secure what they put in it and how they configure it.','责任共担模式','AWS 保护云本身；客户保护他们放入云中的内容及其配置方式。'],
['Inherited control','A control fully handled by AWS that customers inherit, such as physical security.','继承控制','完全由 AWS 负责、客户可继承的控制，例如物理安全。'],
['Root user','The identity created with the AWS account, with complete access. Use only for root-only tasks.','根用户','创建 AWS 账户时生成的、拥有完全访问权限的身份。只用于必须由根用户执行的任务。'],
['IAM role','An identity with permissions that is assumed to get temporary credentials.','IAM 角色','一种带有权限、通过代入获取临时凭证的身份。'],
['IAM policy','A JSON document that allows or denies actions on resources.','IAM 策略','允许或拒绝对资源执行操作的 JSON 文档。'],
['Least privilege','Granting only the permissions needed to perform a task.','最低权限原则','只授予执行任务所需的权限。'],
['MFA','Multi-factor authentication: a second factor in addition to the password.','多重身份验证（MFA）','在密码之外再加一个验证因素。'],
['Federation','Letting users from an external identity provider access AWS through roles.','联合','让来自外部身份提供商的用户通过角色访问 AWS。'],
['Service control policy (SCP)','An AWS Organizations policy that sets the maximum permissions for accounts.','服务控制策略（SCP）','AWS Organizations 中为账户设置最大权限的策略。'],
['Encryption at rest','Protecting stored data by encrypting it.','静态加密','通过加密保护存储的数据。'],
['Encryption in transit','Protecting data moving over a network, for example with TLS.','传输中加密','保护通过网络传输的数据，例如使用 TLS。'],
['Compliance report','Third-party audit report about AWS controls, such as SOC 2, available in AWS Artifact.','合规报告','关于 AWS 控制措施的第三方审计报告，例如 SOC 2，可在 AWS Artifact 中获取。'],
['DDoS','Distributed denial of service: flooding a system with traffic to make it unavailable.','DDoS','分布式拒绝服务：用大量流量淹没系统使其不可用。'],
['Infrastructure as code (IaC)','Defining infrastructure in templates or code so it can be created repeatably.','基础设施即代码（IaC）','用模板或代码定义基础设施，以便可重复地创建。'],
['Hybrid deployment','Connecting cloud resources with on-premises infrastructure.','混合部署','把云资源与本地基础设施连接起来。'],
['Region','A geographic area with multiple isolated Availability Zones.','区域','包含多个相互隔离的可用区的地理区域。'],
['Availability Zone','One or more discrete data centres with redundant power and networking in a Region.','可用区','区域内一个或多个具有冗余电力和网络的独立数据中心。'],
['Edge location','A site close to users that caches content and serves DNS (CloudFront, Route 53).','边缘站点','靠近用户、缓存内容并提供 DNS 解析的站点（CloudFront、Route 53）。'],
['Data sovereignty','The requirement that data stays subject to the laws of the country where it is stored.','数据主权','数据须受其存储所在国家法律约束的要求。'],
['Disaster recovery','Restoring systems and data after a major outage, often in another Region.','灾难恢复','在重大故障后恢复系统和数据，通常在另一个区域中进行。'],
['Instance type','A combination of CPU, memory, storage and networking for an EC2 instance.','实例类型','EC2 实例的 CPU、内存、存储和网络组合。'],
['Serverless','Running code or services without provisioning or managing servers; pay for use.','无服务器','无需配置或管理服务器即可运行代码或服务；按使用量付费。'],
['Container','A package of an application and its dependencies that runs consistently anywhere.','容器','包含应用及其依赖项、可在任何地方一致运行的软件包。'],
['Auto scaling','Automatically changing the number of resources to match demand.','弹性伸缩','自动改变资源数量以匹配需求。'],
['Load balancer','Distributes traffic across multiple targets and routes only to healthy ones.','负载均衡器','把流量分配到多个目标，并只路由到健康的目标。'],
['Relational database','Stores data in tables with a fixed schema, queried with SQL.','关系数据库','以具有固定架构的表存储数据，使用 SQL 查询。'],
['NoSQL database','A non-relational database with flexible schemas, such as key-value or document.','NoSQL 数据库','具有灵活架构的非关系数据库，例如键值或文档数据库。'],
['Read replica','A read-only copy of a database used to scale read traffic.','只读副本','用于扩展读取流量的数据库只读副本。'],
['Multi-AZ','Running a standby or copies in another AZ for high availability.','多可用区','在另一个可用区中运行备用实例或副本以实现高可用性。'],
['Subnet','A range of IP addresses in one AZ inside a VPC; public or private.','子网','VPC 内位于一个可用区中的一段 IP 地址范围；分为公有和私有。'],
['Security group','A stateful, instance-level virtual firewall with allow rules only.','安全组','实例级别、有状态的虚拟防火墙，只有允许规则。'],
['Network ACL','A stateless, subnet-level firewall with allow and deny rules.','网络 ACL','子网级别、无状态的防火墙，有允许和拒绝规则。'],
['Object storage','Stores data as objects with metadata in buckets (Amazon S3).','对象存储','把数据作为带元数据的对象存储在存储桶中（Amazon S3）。'],
['Block storage','Stores data in fixed-size blocks, like a hard drive attached to an instance (Amazon EBS).','数据块存储','以固定大小的块存储数据，就像挂载到实例上的硬盘（Amazon EBS）。'],
['Instance store','Temporary block storage on the host; data is lost when the instance stops.','实例存储','主机上的临时数据块存储；实例停止时数据丢失。'],
['Storage class','An S3 tier with a price and access profile, such as Standard-IA or Glacier Deep Archive.','存储类别','具有特定价格和访问特征的 S3 层级，例如 Standard-IA 或 Glacier Deep Archive。'],
['Lifecycle policy','Rules that move objects to cheaper storage classes or delete them over time.','生命周期策略','随时间把对象转移到更便宜的存储类别或删除它们的规则。'],
['Durability','The likelihood that stored data is not lost; S3 is designed for 11 nines.','持久性','存储的数据不会丢失的可能性；S3 的设计为 11 个 9。'],
['ETL','Extract, transform and load: preparing data for analysis (AWS Glue).','ETL','提取、转换和加载：为分析准备数据（AWS Glue）。'],
['Decoupling','Separating components so they can scale and fail independently, often with queues.','解耦','把组件分开，使它们能够独立伸缩和发生故障，通常借助队列实现。'],
['On-Demand Instance','EC2 capacity paid by the second or hour with no commitment.','按需型实例','按秒或小时付费、无需承诺的 EC2 容量。'],
['Reserved Instance','A 1- or 3-year commitment to an instance configuration for a discount.','预留实例','为获得折扣而对某种实例配置做出的 1 年或 3 年承诺。'],
['Spot Instance','Spare EC2 capacity at a large discount that AWS can reclaim with two minutes’ notice.','竞价型实例','以大幅折扣提供的 EC2 闲置容量，AWS 可在提前两分钟通知后收回。'],
['Savings Plans','A 1- or 3-year $/hour usage commitment for a discount on compute.','AWS 节省计划','为获得计算折扣而做出的 1 年或 3 年“美元/小时”用量承诺。'],
['Dedicated Host','A physical server dedicated to you, with socket and core visibility.','专属主机','专供你使用的物理服务器，可见插槽和内核。'],
['Consolidated billing','One bill for all accounts in AWS Organizations, with combined usage discounts.','整合账单','AWS Organizations 中所有账户只需一张账单，并享受合并用量折扣。'],
['Cost allocation tag','An activated tag used to organize and track costs in billing reports.','成本分配标签','已激活、用于在账单报告中组织和跟踪成本的标签。'],
['Technical Account Manager (TAM)','A designated AWS technical contact for Enterprise-level support customers.','技术客户经理（TAM）','为企业级支持客户指定的 AWS 技术联系人。'],
['AWS Partner Network (APN)','The global community of AWS software and services partners.','AWS 合作伙伴网络（APN）','AWS 软件和服务合作伙伴组成的全球社区。']
];
G.forEach(function(g){CLF.gloss.push({en:{t:g[0],d:g[1]},zh:{t:g[2],d:g[3]}});});

/* ---------------- 7-day plan ---------------- */
CLF.plan = [
 {en:'Domain 1: cloud benefits and Well-Architected', zh:'领域 1：云的益处与 Well-Architected', items:[
  ['t:1.1','Read Task 1.1; say the six advantages out loud from memory','阅读任务 1.1，凭记忆大声说出六大优势'],
  ['t:1.2','Read Task 1.2; match one design principle to each pillar','阅读任务 1.2，为每个支柱对应一条设计原则'],
  ['t:1.3','Read Task 1.3: CAF perspectives, the 7 Rs, migration tools','阅读任务 1.3：CAF 视角、7 R、迁移工具'],
  ['t:1.4','Read Task 1.4: fixed vs variable cost, BYOL, rightsizing','阅读任务 1.4：固定与可变成本、BYOL、合理调整大小'],
  ['c:d1','Flip all Domain 1 flashcards','翻完领域 1 的全部闪卡']]},
 {en:'Domain 2 part 1: shared responsibility and governance', zh:'领域 2（上）：责任共担与治理', items:[
  ['t:2.1','Read Task 2.1; sort EC2, RDS, Lambda and S3 duties into AWS vs customer','阅读任务 2.1，把 EC2、RDS、Lambda 和 S3 的职责分到 AWS 和客户两边'],
  ['t:2.2','Read Task 2.2: Artifact, encryption, CloudTrail vs CloudWatch vs Config, security services','阅读任务 2.2：Artifact、加密、CloudTrail/CloudWatch/Config 对比、安全服务'],
  ['q:d2','Practice Domain 2 questions','练习领域 2 题目']]},
 {en:'Domain 2 part 2: access management and security resources', zh:'领域 2（下）：访问管理与安全资源', items:[
  ['t:2.3','Read Task 2.3; list the root-only tasks from memory','阅读任务 2.3，凭记忆列出只有根用户能执行的任务'],
  ['t:2.4','Read Task 2.4: WAF, Shield, Firewall Manager, Marketplace, Trusted Advisor','阅读任务 2.4：WAF、Shield、Firewall Manager、Marketplace、Trusted Advisor'],
  ['c:d2','Flip all Domain 2 flashcards','翻完领域 2 的全部闪卡']]},
 {en:'Domain 3 part 1: deployment, infrastructure, compute, databases', zh:'领域 3（上）：部署、基础设施、计算、数据库', items:[
  ['t:3.1','Read Task 3.1: console, CLI, SDK, IaC; deployment models','阅读任务 3.1：控制台、CLI、SDK、IaC；部署模型'],
  ['t:3.2','Read Task 3.2; draw Region → AZ → data centre, plus edge locations','阅读任务 3.2，画出区域 → 可用区 → 数据中心，以及边缘站点'],
  ['t:3.3','Read Task 3.3: EC2 families, containers, Lambda, auto scaling, load balancers','阅读任务 3.3：EC2 系列、容器、Lambda、弹性伸缩、负载均衡器'],
  ['t:3.4','Read Task 3.4: RDS, Aurora, DynamoDB, ElastiCache, DMS and SCT','阅读任务 3.4：RDS、Aurora、DynamoDB、ElastiCache、DMS 和 SCT']]},
 {en:'Domain 3 part 2: networking, storage, AI/ML, other services', zh:'领域 3（下）：网络、存储、AI/ML、其他服务', items:[
  ['t:3.5','Read Task 3.5; compare security groups and network ACLs','阅读任务 3.5，比较安全组和网络 ACL'],
  ['t:3.6','Read Task 3.6; order the S3 storage classes from hottest to coldest','阅读任务 3.6，把 S3 存储类别从热到冷排序'],
  ['t:3.7','Read Task 3.7: AI services and the analytics pipeline','阅读任务 3.7：AI 服务和分析数据流程'],
  ['t:3.8','Read Task 3.8: SQS vs SNS vs EventBridge, dev tools, end-user computing','阅读任务 3.8：SQS/SNS/EventBridge 对比、开发工具、终端用户计算'],
  ['q:d3','Practice Domain 3 questions','练习领域 3 题目']]},
 {en:'Domain 4: pricing, billing and support', zh:'领域 4：定价、账单与支持', items:[
  ['t:4.1','Read Task 4.1; pick the right purchase option for five scenarios','阅读任务 4.1，为五个场景选出合适的购买选项'],
  ['t:4.2','Read Task 4.2: Budgets vs Cost Explorer vs Pricing Calculator, tags','阅读任务 4.2：Budgets/Cost Explorer/定价计算器对比、标签'],
  ['t:4.3','Read Task 4.3: support plans, Trusted Advisor, APN, Trust & Safety','阅读任务 4.3：Support 计划、Trusted Advisor、APN、信任与安全团队'],
  ['c:d4','Flip all Domain 4 flashcards','翻完领域 4 的全部闪卡'],
  ['q:d4','Practice Domain 4 questions','练习领域 4 题目']]},
 {en:'Full review and mock exams', zh:'全面复习与模拟考试', items:[
  ['m:1','Take mock exam #1 and review every wrong answer','完成第 1 次模拟考试并复盘每道错题'],
  ['s:','Scan the Services map; cover the right column and recall it','浏览服务速查表，遮住右列进行回忆'],
  ['c:all','Flip every flashcard you have not marked "I know this"','翻完所有未标记“已掌握”的闪卡'],
  ['r:','Retry your Missed questions until the list is empty','重做“错题”列表，直到清空'],
  ['m:2','Take the full 65-question exam simulation; aim for an estimated 800 or higher','完成 65 题真实考试模拟，目标估算分 800 以上']]}
];
})();
